### ISSUE TITLE
Add Windows-Compatible Curl Commands to SSI Documentation

### ISSUE THREAD

**Issue by blackgirlbytes** [TBD54566975/developer.tbd.website#1005]
### Type

Content Issue

### Feedback

Our current documentation provides curl command examples that are compatible with Mac/Linux environments. However, I realized these commands do not work as intended on Windows after helping Hackathon participants who were struggling to run curl commands in our documentation.

This happens because Mac/Linux uses single quotes ('), but Windows uses double quotes (")

Ex: 
Works for Mac
```bash
curl -X PUT localhost:8080/v1/dids/key -d '{"keyType":"Ed25519"}'
```

Works for Windows
```bash
curl -X PUT localhost:8080/v1/dids/key -d "{\"keyType\":\"Ed25519\"}"
```

Pages that need to be updated:
- https://developer.tbd.website/docs/ssi/create-did
- https://developer.tbd.website/docs/ssi/create-credentials
- https://developer.tbd.website/docs/ssi/credential-issuance-service
- https://developer.tbd.website/docs/ssi/revoke-credentials
- https://developer.tbd.website/docs/ssi/verify-credentials
- https://developer.tbd.website/docs/ssi/verifiable-presentations
- https://developer.tbd.website/docs/ssi/credential-manifests
- https://developer.tbd.website/docs/ssi/presentation-requests
- https://developer.tbd.website/docs/ssi/well-known-did

### Screenshots

Paste relevant images or screenshots here
<img width="1089" alt="Screenshot 2023-11-15 at 1 19 42 PM" src="https://github.com/TBD54566975/developer.tbd.website/assets/22990146/ef4b64b1-9076-4a9d-b1df-0904c1d2b2e7">

**Comment by samejima-san** [comment]
here for the assignment!

**Comment by blackgirlbytes** [comment]
Here's my idea of how to approach this..You can create tabs which will switch between Mac and Windows commands to look like this: 



- convert the md file into an mdx file
- import the Tabs component - https://docusaurus.io/docs/markdown-features/tabs

You can do something like this:

```
---
sidebar_position: 3
title: Create a DID
hide_title: true
---
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';

# Create a Decentralized Identifier (DID)

In the world of SSI, [DIDs](/docs/web5/learn/decentralized-identifiers) are used to identify any subject (e.g., a person, organization, thing, data model, abstract entity, etc.). In this tutorial we'll show you how to create a DID using the [SSI Service](https://github.com/TBD54566975/ssi-service). 

:::info
## Prerequisites

Follow guide to [Clone & Run SSI Service](run-ssi-service).
:::

## Create DID

To create your DID, run the following request:

<Tabs
  defaultValue="mac"
  values={[
    { label: 'Mac', value: 'mac', },
    { label: 'Windows', value: 'windows', },
  ]}>
  <TabItem value="mac">



curl -X PUT localhost:8080/v1/dids/key -d '{"keyType":"Ed25519"}'


</TabItem>
<TabItem value="windows">

curl -X PUT localhost:8080/v1/dids/key -d "{\"keyType\":\"Ed25519\"}"

</TabItem>
</Tabs>

```

**Comment by blackgirlbytes** [comment]
Also you can probably turn the Tabs component into a reusable component in our application where you just have to pass in the Windows curl command and Mac curl commands as props

**Comment by ALRubinger** [comment]
@blackgirlbytes Would you mind an update or close here if no longer valid?

**Comment by angiejones** [comment]
[PR here](https://github.com/TBD54566975/developer.tbd.website/pull/1028). Needs to be refactored to use the newer Shnip structure

**Comment by blackgirlbytes** [comment]
SSI documentation was removed, so I'm closing this issue.
