### ISSUE TITLE
Automate retraining of AskGPT - ChatGPT bot

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/developer.tbd.website#1044]
Investigate how and get this automated.

**Comment by ALRubinger** [comment]
@leordev uncovered this is a larger scope of work, bumping to Phase 6

**Comment by ALRubinger** [comment]
@leordev has a Google Doc assessing this; to put that info linkable here when ready

**Comment by leordev** [comment]
https://docs.google.com/document/d/1qcs4rarIJAGDpQioPlupg3WHd07Pr1FRuPrXwRZFxZU/edit#heading=h.lti90vagnbwr

**Comment by ALRubinger** [comment]
^^ Above is TBD internal only for now, folks - we'll get it out there when we can :)

**Comment by ALRubinger** [comment]
Going to be handled through new vendor.
