### ISSUE TITLE
[FEEDBACK]: 

### ISSUE THREAD

**Issue by sunday4me** [TBD54566975/developer.tbd.website#1051]
### Type

Docs Bug Report

### Feedback

Tell us what you're seeing!
The code snippet is not in the provided space or div 

### Screenshots

Paste relevant images or screenshots here

### developer.tbd.website URL

https://developer.tbd.website/docs/web5/build/apps/dinger-tutorial/

**Comment by kohasummons** [comment]
@sunday4me 

Hi! This issue does not give any information. Would you like to delete or update it?

**Comment by angiejones** [comment]
not enough info
