### ISSUE TITLE
Enhancing Code Snippet system

### ISSUE THREAD

**Issue by dayhaysoos** [TBD54566975/developer.tbd.website#1067]
## Current State

The code snippet system in our Docusaurus setup is functional and meets our current needs. It allows runnable code within the documentation and provides readable content for developers.

### How It Works

- We maintain a `code-snippets` directory.
- Functions are written inside this directory.
- Running `pnpm start`, test commands, or build commands triggers a Node script.
- This script compiles code snippets from each folder into a JSON map for later reference.

While this system works, it's not without its flaws.

## Issues and Considerations

There are several key issues and considerations for future development:

1. **Scalability**: The JSON file will grow exponentially over time, raising concerns about long-term scalability.
2. **Language Support**: Currently, we do not support multiple programming languages.
3. **Developer Experience**: As we introduce more languages and SDKs, the developer experience may degrade.

## Questions and Potential Enhancements

To address these issues, we need to consider the following:

- **Eliminating the JSON Map**: 
  - Is it feasible to remove the JSON map to improve the developer experience?
  - What alternative approaches can we consider?

- **Testing Suites for Multiple Languages**: 
  - How can we leverage testing suites to handle multiple languages effectively?
  - What organizational changes will be necessary to accommodate this?

- **Adjusting Release Processes**: 
  - What modifications will be needed in our release processes to support multiple languages?
  - How can these adjustments be implemented efficiently?

- **Making this reusable**:
- We want this for multiple projects, it may make sense to put this together as an installable npm package

### Turning the System into an npm Package 

Given the potential need to reuse this technology across multiple projects, packaging the code snippet system as an npm module would offer significant benefits in terms of distribution, maintenance, and upgradeability.

#### Steps and Considerations (High Level):

1. **Modularization:**
   - Ensure the system is modular with a well-defined API for easy integration into different projects.

2. **Configurability:**
   - Allow customization through configuration options to adapt to various project structures and requirements.
   - Possibly include a CLI set up step

3. **Documentation:**
   - Provide comprehensive documentation, including installation instructions, usage examples, and contribution guidelines.

4. **Testing and Compatibility:**
   - Include extensive tests to ensure functionality across different environments.
   - Ensure compatibility with multiple Node.js versions.

5. **Performance Optimization:**
   - Focus on performance and scalability, especially considering large-scale usage.

6. **Open Source and Community Engagement:**
    - Consider open-sourcing the package to encourage community contributions.

### Addressing Scalability and Other Concerns (a little more detail)

1. **Scalability with JSON Map:**
   - Explore using a database or API service instead of a static JSON file.
     -  Perhaps Mongo would be a good choice due to the way it stores data using JSON
   - Implement lazy loading for code snippets. (Leo's idea)

2. **Multiple Language Support:**
   - Organize snippets in language-specific subfolders.
   - Use different testing suites for each language.

3. **Developer Experience:**
   - Provide clear documentation and automated scripts for common tasks and checks.
   - Should consider using a CLI for initial configuration and possibly adding more snippets?

4. **Release Process Adjustments:**
   - Implement snippet versioning tied to SDK or API versions.
   - Integrate snippet testing into the CI/CD pipeline.

5. **Alternative to JSON Map:**
   - Consider dynamically generating the snippet map as needed. (Leo's idea)
6. **Languages that need consideration:**
  - Kotlin, Swift, JS
  - Kotlin example: https://jetbrains.github.io/kotlin-playground/examples/ 
  - 

This proposal aims to transform the code snippet system into a more scalable, efficient, and user-friendly tool, adaptable to various projects and evolving needs.

## Seeking Input

I'm looking for feedback and suggestions on how to tackle these challenges. Any insights or experiences with similar systems would be greatly appreciated.

**Comment by ALRubinger** [comment]
@dayhaysoos Noting our discussion today about: componentize this for reuse?

**Comment by ALRubinger** [comment]
Very useful description; especially liking the shift to externalizing this work as an NPM module for reuse as we consider impls in other sites.

@dayhaysoos what else in our docs system is now baked into the Dev Site? Aside from code snippets, are there other features we've built powering guides/examples/etc?

**Comment by leordev** [comment]
I'd like to add as an input that you might research how other docusaurus (or even other generic document portals powered by other JS frameworks) projects are implementing testable snippets. It really sounds like a regular use case and I would be surprised if we are the first ones doing it this way.

From there you might uncover better ideas or even find reusable libraries that can help our new improvements!

**Comment by dayhaysoos** [comment]
> Very useful description; especially liking the shift to externalizing this work as an NPM module for reuse as we consider impls in other sites.
> 
> @dayhaysoos what else in our docs system is now baked into the Dev Site? Aside from code snippets, are there other features we've built powering guides/examples/etc?

The only thing I can think of is scripts that makes sure that versions are propagated across projects in the monorepo, but I'm not really sure how that can be distributed from a library.

@leordev 
Noted! Tbh I can't really find anything that supports testable snippets but I will continue doing my research

**Comment by andresuribe87** [comment]
@dayhaysoos Kotlin has a playground. You can see an example of runnable snippets in https://jetbrains.github.io/kotlin-playground/examples/

**Comment by dayhaysoos** [comment]
Updating here with some finds.

Python has this: https://docs.python.org/3/library/doctest.html

JavaScript has a version of that as well: https://www.npmjs.com/package/doctest

This might be what powers the new system under the hood, need to spend time reading through docs

**Comment by dayhaysoos** [comment]
For reference:

https://www.sticksnglue.com/2022-03-04-the-documentation-dream/

Interesting takes here:

Create a docusaurus plugin
look into codegen
