### ISSUE TITLE
Remove @tbdex-js api reference

### ISSUE THREAD

**Issue by leordev** [TBD54566975/developer.tbd.website#1077]
When we merge this: https://github.com/TBD54566975/tbdex-js/pull/116

We need to do the following in our developer website:

1. expose a link to https://tbd54566975.github.io/tbdex-js in our [API Reference Guides](https://developer.tbd.website/docs/api) page
2. forward any tbdex-js api reference to the new https://tbd54566975.github.io/tbdex-js address:
  - ![image](https://github.com/TBD54566975/developer.tbd.website/assets/6147142/78bcd3fb-49d6-48f1-920d-7fef6b263c74)
  - The ExchangesApi link should point to https://tbd54566975.github.io/tbdex-js/interfaces/_tbdex_http_server.ExchangesApi.html
4. remove our https://developer.tbd.website/docs/tbdex/api-reference folder

**Comment by angiejones** [comment]
ok sounds good

**Comment by Pratham271** [comment]
Can i work on it

**Comment by leordev** [comment]
The PR is already merged! So you are good to work on this! I really appreciate the offer! :)

**Comment by angiejones** [comment]
> Can i work on it

hey, thank you! here's all that needs to be done:

- add card on [API Reference page](https://developer.tbd.website/docs/api)
- Change tbDEX → API Reference on navbar to point to external page (kinda tricky)
- Update link in [Message Types guide](https://developer.tbd.website/docs/tbdex/message-types) to point to external page
- Update link in [Anatomy of a PFI guide](https://developer.tbd.website/docs/tbdex/pfi/anatomy-of-a-pfi) to point to external page
- Update link in [Creating Quotes guide](https://developer.tbd.website/docs/tbdex/pfi/creating-quotes) to point to external page

**Comment by Pratham271** [comment]
which card I have to add on [API Reference page](https://developer.tbd.website/docs/api)

**Comment by Pratham271** [comment]
tbDEX → API Reference should point to this https://tbd54566975.github.io/tbdex-js link right?

**Comment by Pratham271** [comment]
Update link in [Message Types guide](https://developer.tbd.website/docs/tbdex/message-types) to point to external page
Update link in [Anatomy of a PFI guide](https://developer.tbd.website/docs/tbdex/pfi/anatomy-of-a-pfi) to point to external page
Update link in [Creating Quotes guide](https://developer.tbd.website/docs/tbdex/pfi/creating-quotes) to point to external page
tell me the links to which I have to point to these

**Comment by angiejones** [comment]
> which card I have to add on [API Reference page](https://developer.tbd.website/docs/api)

tbDEX JS SDK
