### ISSUE TITLE
Issue while choosing node version

### ISSUE THREAD

**Issue by 0Armaan025** [TBD54566975/developer.tbd.website#1088]
<img width="960" alt="image" src="https://github.com/TBD54566975/developer.tbd.website/assets/104704093/4a0cb8f1-669e-4db4-a61f-f45aa6e81dfe">

Hey there!
It's me, Armaan and while opening the npm 19+ version choice box on the website, I am getting this issue, might be a design problem.

I hope this will be fixed soon or it's just a problem with my device?

Website link: https://developer.tbd.website/api/web5-js/

Thanks and regards,
Armaan.

**Comment by acekyd** [comment]
Tried across multiple browsers and devices - unable to replicate on my end as well.

**Comment by ALRubinger** [comment]
@acekyd Would you validate you can't reproduce and close if so?
