### ISSUE TITLE
Reactify QuickStart and Ensure it's Tested

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/developer.tbd.website#1093]
Move QuickStart from vanilla JS into React in a way it can have automated tests consistent with the rest of the examples suite.

When done, remove the manual testing step in the [release process template](https://github.com/TBD54566975/developer.tbd.website/edit/main/.github/ISSUE_TEMPLATE/web5-upgrade.yaml).

Related: 
* #1002
* #997

**Comment by dayhaysoos** [comment]
Just spoke with @blackgirlbytes about this!  Gave us the thumbs up (but will update with feedback/concerns if any pop up)

I will be documenting the changes to be done later

**Comment by dayhaysoos** [comment]
## Reactifying

Currently, the quickstart being surfaced on the docs site is being done in vanilla JavaScript. It's extremely messy this way and it gets hard to update/maintain over time. Switching all of the logic to be done with React will make things much easier to read.

## Testing

I'm thinking we should keep a lot of the functions that interact with the Web5 API the same (more or less) and we export them from the file directly. We can import them into the Vitest suite in a `__tests__` directory at the `src` level of the project.

These are the following functions that will be getting tested:

- [ ] `create DID`
- [ ] `create Record`
- [ ] `read Record`
- [ ] `update Record`
- [ ] `delete Record`
