### ISSUE TITLE
Add Code Snippets and Tests for VC Fan Membership Tutorial

### ISSUE THREAD

**Issue by angiejones** [TBD54566975/developer.tbd.website#1100]
https://developer.tbd.website/docs/web5/build/verifiable-credentials/fan-club-vc

**Comment by Pratham271** [comment]
I would like to work on it if you can explain me a little more of what to do

**Comment by ALRubinger** [comment]
@acekyd Would you mind having a look?

**Comment by angiejones** [comment]
snippets and tests covered
