### ISSUE TITLE
Add snippet on how to create a did:dht identifier 

### ISSUE THREAD

**Issue by mahoekst** [TBD54566975/developer.tbd.website#1116]
### Type

Docs Bug Report

### Feedback

It would be nice to have a little sample how to create a did:dht like this:

`//did:dht
import { DidDhtMethod } from '@web5/dids'

//Creates a DID using the DHT method and publishes the DID Document to the DHT  
const didDht = await DidDhtMethod.create({ publish: true });

//DID and its associated data which can be exported and used in different contexts/apps
const portableDID = JSON.stringify(didDht);

//DID string
const did = didDht.did;

//DID Document
const didDocument = JSON.stringify(didDht.document);

//Cryptographic keys associated with DID
const keys = JSON.stringify(didDht.keySet);

//Primary form of a DID. more info: https://www.w3.org/TR/did-core/#dfn-canonicalid
const canonicalId = didDht.canonicalId;

console.log(didDht);`

### Screenshots

Paste relevant images or screenshots here

**Comment by michaelneale** [comment]
will need a package.json to try this like this: 

```
{
  "name": "diddht-try",
  "dependencies": {
    "@web5/dids": "^0.2.4"
  },
  "type" : "module"
}
``` then `npm install` - and `node index.js`

**Comment by mahoekst** [comment]
Never mind, you already have it https://developer.tbd.website/docs/web5/build/decentralized-identifiers/how-to-create-did
