### ISSUE TITLE
Test and Add Kotlin Code snippets to code snippet system

### ISSUE THREAD

**Issue by blackgirlbytes** [TBD54566975/developer.tbd.website#1163]
### Type

Docs Bug Report

### Feedback

Right now, I'm hard coding our kotlin code snippets to reach our goal of educating devs about our multi language SDKs, but need to add them to the Bluehawk integration/ new code snippet system

### Screenshots

Paste relevant images or screenshots here

**Comment by ALRubinger** [comment]
@blackgirlbytes With #1176 your dependency should be clear to work on this

**Comment by blackgirlbytes** [comment]
thank you!!!! getting these done now! @ALRubinger
