### ISSUE TITLE
[FEEDBACK]: pnpm command missing 

### ISSUE THREAD

**Issue by JenErsoz-Jones** [TBD54566975/developer.tbd.website#1165]
### Type

Content Issue

### Feedback

Hello, I've been following the tutorial page Https://developer.tbd.website/docs/web5/build/apps/todo-app-tutorial/#getting-the-skeleton-app however on the page where it says download the necessary packages by running these commands pnpm install pnpm run dev. The pnpm run dev command throws an err_pnpm_no_script missing script:Dev exception

### Screenshots

Paste relevant images or screenshots here

### developer.tbd.website URL

Https://developer.tbd.website/docs/web5/build/apps/todo-app-tutorial/#getting-the-skeleton-app

### Browser

Chrome

### Relevant log output

```shell
ERR_PNPM_NO_SCRIPT Missing script: dev
```

**Comment by ALRubinger** [comment]
@angiejones will you please triage?

**Comment by ALRubinger** [comment]
@dayhaysoos to investigate via the instructions on https://developer.tbd.website/docs/web5/build/apps/todo-app-tutorial/#getting-the-skeleton-app and see if we need to update

**Comment by ALRubinger** [comment]
@dayhaysoos says: "should be pnpm run start"

**Comment by blackgirlbytes** [comment]
I believe this works now -- closing to clean up issues
