### ISSUE TITLE
Add VerifiablePresentation.create() for JS 

### ISSUE THREAD

**Issue by blackgirlbytes** [TBD54566975/developer.tbd.website#1205]
### Type

Docs Bug Report

### Feedback

Once this PR is merged, we need to update our docs for verifiable presentation submissions
https://github.com/TBD54566975/web5-js/pull/382

### Screenshots

Paste relevant images or screenshots here

**Comment by angiejones** [comment]
@blackgirlbytes is this one done already?

**Comment by blackgirlbytes** [comment]
@angiejones no :(. Anything with VPs in JS is currently in an alpha release of web5/credentials. As soon as they do a credentials 0.4.3, we can update the docs for this.
