### ISSUE TITLE
Import snippets from compiled code

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/developer.tbd.website#1266]
Caught this section of imports:

https://github.com/TBD54566975/developer.tbd.website/blob/main/site/testsuites/testsuite-kotlin/src/test/kotlin/docs/web5/build/decentralizedidentifiers/HowToCreateDidTest.kt#L65

```
  @Test
  fun `imports for creating Did`() {
    val requiredImports =
        """
        // :snippet-start: requiredDidImportsKt
//did:dht
import web5.sdk.dids.methods.dht.DidDht
import web5.sdk.dids.methods.dht.CreateDidDhtOptions

//did:key
import web5.sdk.dids.methods.key.DidKey

// key manager
import web5.sdk.crypto.InMemoryKeyManager
      // :snippet-end:
        """
  }
```

Why not put snippets in the import statements at the top of the file? Those will get refactoring updates and are checked by the compiler so they'll stay accurate. Then we can remove test methods which duplicate these import statements in untested comments.

**Comment by ALRubinger** [comment]
And is this pattern followed throughout the suite?

**Comment by acekyd** [comment]
This was done because the Kotlin suite threw errors as a result of having `// :snippet-start: xxx` at the top of the file. Was the issue I was having [here](https://discord.com/channels/937858703112155166/949067751803191397/1203010269542883438) that led to following this approach. Happy to find a working alternative. @ALRubinger

**Comment by ALRubinger** [comment]
Ah so we need Shnip support sounds like? Figured there's gotta be a reason; thanks. I'm curious so will ask @dayhaysoos if he's got a plan yet. We should get y'all this support IMO.

**Comment by acekyd** [comment]
That would be great! @ALRubinger. Thank you

**Comment by dayhaysoos** [comment]
I think this was wrapped up yeah? Going to close
