### ISSUE TITLE
Shnip isn't preserving whitespace as written

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/developer.tbd.website#1301]
Ensure Shnip has consistency in whitespace handling between what was written and what's surfaced in docs

**Comment by ALRubinger** [comment]
Example from @blackgirlbytes: https://developer.tbd.website/docs/web5/build/verifiable-credentials/fan-club-vc/#create-dids

**Comment by ALRubinger** [comment]
@dayhaysoos Flagging urgency; needs to be in place for workshops by midweek

**Comment by dayhaysoos** [comment]
Fixed here.

https://github.com/TBD54566975/developer.tbd.website/pull/1324

There seemed to be an instance where spacing wasn't 100% correct on Swift but can't replicate. Keeping an eye on swift snippets moving forward
