### ISSUE TITLE
[FEEDBACK]: ssi.benri.io. Old post links are not working. 

### ISSUE THREAD

**Issue by mscanepa** [TBD54566975/developer.tbd.website#1356]
### Type

Content Issue

### Feedback

All posts related to Benri hosting a playground or console for experimenting with SSI contain some links that are not working, specifically https://ssi.benri.io/ and the https://console.benri.io. I'm not sure if the tool has been moved to another URL or if it has been deprecated.

### Screenshots

Paste relevant images or screenshots here
![Seleccionado marzo 26 2024 12:09:42](https://github.com/TBD54566975/developer.tbd.website/assets/16478045/23cb6a74-ded1-4bca-853b-0ccfaf0dcb73)
![Seleccionado marzo 26 2024 12:11:54](https://github.com/TBD54566975/developer.tbd.website/assets/16478045/352f4128-66e0-4df6-82b2-6b0091bdd4eb)

### developer.tbd.website URL

https://developer.tbd.website/blog/ssi-console/

### Browser

N/A

**Comment by angiejones** [comment]
thank you! The SSI Playground has been deprecated
