### ISSUE TITLE
[FEEDBACK]: add info on how to access privateData in RFQs and order processing

### ISSUE THREAD

**Issue by michaelneale** [TBD54566975/developer.tbd.website#1379]
### Type

Suggestion to Improve

### Feedback

on https://developer.tbd.website/docs/tbdex/wallet/send-rfq 
and https://developer.tbd.website/docs/tbdex/pfi/processing-orders

there is mention of salted hashes of the payin.out data and how it is private. 
I think on the second link at least it should be mentioned how to get data out of an RFQ when processing an order: 

something like: 
```typescript
rfq.privateData.payin.paymentDetails['cc_number']
```

for how to get at data when processing an order on server side. 

### Screenshots

Paste relevant images or screenshots here

### developer.tbd.website URL

https://developer.tbd.website/docs/tbdex/pfi/processing-orders

**Comment by angiejones** [comment]
Should do the same for RFQs
