### ISSUE TITLE
Upgrade from `docker-compose` to `docker compose`

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/developer.tbd.website#1524]
We have failing builds, for instance [here](https://github.com/TBD54566975/developer.tbd.website/actions/runs/10222941596/job/28288432471#step:6:1):

```
Run docker-compose up -d dwn-server
/home/runner/work/_temp/e9e06126-d177-[4](https://github.com/TBD54566975/developer.tbd.website/actions/runs/10222941596/job/28288432471#step:6:5)c36-b22c-0ffc6a710f1d.sh: line 1: docker-compose: command not found
Error: Process completed with exit code 127.
```

This is likely a symptom of an issue we've seen before in #1368, from GitHub [deprecating](https://github.com/orgs/community/discussions/116610) `v1` of Docker Compose.

Raised by @angiejones and holding up the team through failed builds and PRs.

Upgrade and resolve.

**Comment by blackgirlbytes** [comment]
Closing as this looks like it was solved
