### ISSUE TITLE
Text icon card QA

### ISSUE THREAD

**Issue by tallneil** [TBD54566975/developer.tbd.website#1543]
PR: https://github.com/TBD54566975/developer.tbd.website/pull/1513/files
Figma: https://www.figma.com/design/vzQz0IgCT37UxdEbgn1nPw/%F0%9F%8C%95-tbd-web---reviews?node-id=5983-75049&t=NFD8dZ7oBt20OalL-1

---

change border width to 1px

https://github.com/TBD54566975/developer.tbd.website/blob/edca22ee0754f8fd0ece8c63e0d3acd278b2abf9/site-new/src/components/TextIconCard.tsx#L44

current: `border-2`
expected: `border-1`

---

the purple theme of the text icon card should use `tbd-purple-tint-2` instead of `tbd-purple`. it's a little confusing bc the yellow and teal themes don't use tints, but purple does.

https://github.com/TBD54566975/developer.tbd.website/blob/edca22ee0754f8fd0ece8c63e0d3acd278b2abf9/site-new/src/components/TextIconCard.tsx#L21

**Comment by dayhaysoos** [comment]
Hey @tallneil, just FYI there is not `border-1` class so I need to do this instead: `border-[1px]`

**Comment by tallneil** [comment]
https://github.com/TBD54566975/developer.tbd.website/pull/1562
