### ISSUE TITLE
Fix Typos in Developer Website's Open Source Section on Front Page

### ISSUE THREAD

**Issue by taniashiba** [TBD54566975/developer.tbd.website#1553]
# Fix Typos in Developer Website's Open Source Section on Front Page

## 🚀 Goal
We want to ensure our website's different pages don't have any mistakes.

## 🤔 Background
This issue focuses specifically on fixing typos across our general website pages. Your contributions here make a difference!

## 🤝 How You Can Contribute
We've broken it down into specific typos for you to address. Every contribution counts!

### **❗You must only assign yourself one task at a time to give everyone a chance to participate.❗**
You may assign yourself your next task after your current task is reviewed & accepted.
1. /open-source Page
    - [ ] Remove extra space before comma in "Apache License 2.0 ,"
![image](https://github.com/user-attachments/assets/3f7c1feb-9e3f-4e9f-8763-6d9bd607d97f)
2. Make sure all tests are passing.

## 🌟 Resources
- [Developer Website](https://developer.tbd.website/)

## Getting Started
1. Comment ".take" on this issue to get assigned
2. Fork the repository and create a new branch for this task
3. Follow the tasks outlined above
4. Submit a pull request with your changes
6. Respond to any feedback during the review process

## Questions?
If you have any questions or need clarification, please comment on this issue or join our [Discord](https://discord.gg/tbd) community.

Happy coding! 🎉

**Comment by KiranBaliga** [comment]
Please assign me this task as a part of hacktoberfest. 

.take

**Comment by jmahey-05** [comment]
.take
