### ISSUE TITLE
Create Feedback Survey for Hacktoberfest Participants & Write Blog Post on TBD Hacktoberfest Experience

### ISSUE THREAD

**Issue by taniashiba** [TBD54566975/developer.tbd.website#1558]
# Create Feedback Survey for Hacktoberfest Participants

## 🚀 Goal
Create a survey to help yourself and other participants in this year's Hacktoberfest give us direct feedback for next year. To be sent out after Hacktoberfest ends.

## 🤔 Background
This issue focuses specifically on creating and formatting an easy-to-complete survey. Your contributions here will help developers go through that our documentation easier!

## 🤝 How You Can Contribute
We've broken it down into smaller tasks. Every contribution counts!

### **❗You must only assign yourself one task at a time to give everyone a chance to participate.❗**
You may assign yourself your next task after your current task is reviewed & accepted.
- [x] Develop up to 6 key questions for participants to answer.
- [x] Make sure each question covers a different aspect of Hacktoberfest. (For example: Projects, Rewards, Incentives, Nice to Haves, etc.)
- [x] Create survey in shareable Google Form format.
- [ ] Submit PR with link to form for our review.

Blog instructions
- [x] You must host your content on your own website or channel.
- [ ] Add your content information directly to the `site/src/externalContributors.json` file in the repository.
- [ ] Save your image in the `site/static/image/external-contributor/` directory, ensuring the image is in a **16:9 ratio**.
- [ ] Create a pull request with your changes for review.
- [ ] Link your submitted PR in a comment here to count towards Hacktoberfest.

Your contribution in `externalContributors.json` must include:
- [ ] Type: Video, Blog, Social (please choose the appropriate one)
- [ ] Thumbnail: the path to your image, e.g., `/img/external-contributor/yourimage.png`
- [ ] Title: the title of your content
- [ ] Link: a direct link to your content
- [ ] Your name

Here’s an example of the JSON format to follow:

```json
[
    {
        "type": "blog",
        "thumbnail": "/img/external-contributor/yourimage.png",
        "title": "Exploring Web5",
        "link": "https://linktoyourcontent.com/web5-post",
        "contributor": "Your Name"
    }
]
```

Available `type` options:
- Video
- Blog
- Social

## 🌟 Resources
- [ ] [Our Blogs](https://developer.tbd.website/blog/)
- [ ] [Our YouTube channel](https://www.youtube.com/@tbd.videos)

## Getting Started
1. Comment ".take" on this issue to get assigned
2. Fork the repository and create a new branch for this task
3. Follow the tasks outlined above
4. Submit a pull request with your changes
5. Respond to any feedback during the review process

## Questions?
If you have any questions or need clarification, please comment on this issue or join our [Discord](https://discord.gg/tbd) community.

Happy coding! 🎉

**Comment by Ankitv003** [comment]
.take

**Comment by Ankitv003** [comment]
should i share the google form link here, how do i open a pr?

**Comment by taniashiba** [comment]
I don't think we want to collect their email addresses, what matters is the feedback. As for submitting a PR, let me get back to you on that!

**Comment by taniashiba** [comment]
Hi again @Ankitv003 - would you mind sharing the Google Form link here for review? I will confer with the team on how you can submit this as part of a PR, and if there are any other requirements to close out this task.

In the meantime, are there other tasks you are looking to take on? Have you explored our other projects? Would love to know! 🥂

**Comment by Ankitv003** [comment]
https://forms.gle/Gex2Qf9wi8fSQoj39

Yeah, i have taken this issue , https://github.com/TBD54566975/tbd-examples/issues/85 , but it will take me some time to work on it , as it is my first time solving such an issue , also i have got an interview tomorrow, so i will work on it after that.

**Comment by taniashiba** [comment]
I like the form quite a bit! What I would love for you to do is write a blog post about your experience thus far for Hacktoberfest, include the form you created (not direct link, but reference to it) and I will bump this issue to a medium-sized task for doing so.

This allows you to submit a PR for this issue, and allows you to submit the form to us for additional points. I've updated the instructions below on how to, step by step, submit content.

**Comment by Ankitv003** [comment]
hey @taniashiba  i have completed my blog and i have a query about the form , i didn't understand the part where the form should be, do i add it in my blog itself ? 

also here is the draft of my blog , let me know if it's correct or do you need to make any revisions for the same?
https://medium.com/@ankitv78389/hacktoberfest-journey-1d3c4e48bee2

**Comment by taniashiba** [comment]
Hi @Ankitv003 - this is great. To complete this task, please submit a PR with your blog post by following the additional **blog post instructions** above! This way your content can be spotlighted on our website and you can properly get points for your contribution. No need to add the form to the blog post unless you'd like to discuss it in some form that you'd like!

**Comment by Ankitv003** [comment]
So , what should I do with the form , do I discard it and just submit the blog by following the above instructions? @taniashiba

**Comment by taniashiba** [comment]
Hi @Ankitv003 - The form may be discarded, as I've already recorded it! It will be shared with participants, minus some changes, next week with you as the community member spotlighted for creating it to solicit feedback from Hacktoberfest participants!

To close this PR, yes simply submit your blog by following the above instructions and I will close and award the points. <3 Thank you for your patience and hard work!

**Comment by Ankitv003** [comment]
Okay, will do! Thanks for bearing with me through all those questions, @taniashiba 😅😄.

**Comment by Ankitv003** [comment]
in this  step "Save your image in the site/static/image/external-contributor/ directory, ensuring the image is in a 16:9 ratio."
we need to add the thumbnail of the blog right?
