### ISSUE TITLE
Fix Typos in DIF Hackathon: Top 3 Winners! Blog Post

### ISSUE THREAD

**Issue by taniashiba** [TBD54566975/developer.tbd.website#1560]
# Fix Typos in DIF Hackathon: Top 3 Winners! Blog Post

## 🚀 Goal
We want to ensure our website's blog posts don't have any mistakes.

## 🤔 Background
This issue focuses specifically on fixing typos on one of our blog posts. Your contributions here make a difference!

## 🤝 How You Can Contribute
We've broken it down into specific typos for you to address. Every contribution counts!

### **❗You must only assign yourself one task at a time to give everyone a chance to participate.❗**
You may assign yourself your next task after your current task is reviewed & accepted.
1. Fix typos in DIF Hackathon: Top 3 Winners! blog
    - [ ] Fix "sponor" to be "sponsor"
![image](https://github.com/user-attachments/assets/a886df78-90e3-4d30-9dba-e765ab628e04)
    - [ ] Fix "Github" to be "GitHub"
![image](https://github.com/user-attachments/assets/9be2df4d-6a5c-48cd-ab6a-a1289f9259f5)
8. Make sure all tests are passing.

## 🌟 Resources
- [DIF Hackathon: Top 3 Winners! Blog Post](https://developer.tbd.website/blog/2024-01-09-dif-hackathon-winners)
- [Blog, Developer Website](https://developer.tbd.website/blog)

## Getting Started
1. Comment ".take" on this issue to get assigned
2. Fork the repository and create a new branch for this task
3. Follow the tasks outlined above
4. Submit a pull request with your changes
5. Respond to any feedback during the review process

## Questions?
If you have any questions or need clarification, please comment on this issue or join our [Discord](https://discord.gg/tbd) community.

Happy coding! 🎉

**Comment by aniketh-varma** [comment]
.take

**Comment by blackgirlbytes** [comment]
Hey @aniketh-varma I noticed you're assigned to 8 issues and they're all typo issues. While we appreciate the enthusiasm, we kindly ask that you finish an issue before assigning yourself a new one. We want to give everyone a chance to be able to make their first contributions to open source. So, I'll leave you assigned to ticket #1578 , but I will unassign you from the rest.

If you finish that ticket, then you can assign yourself to a new one! Thank you
