### ISSUE TITLE
Fix Typos in Developer Website's tbDEX SDK Section on Front Page

### ISSUE THREAD

**Issue by taniashiba** [TBD54566975/developer.tbd.website#1569]
# Fix Typos in Developer Website's tbDEX SDK Section on Front Page

## 🚀 Goal
We want to ensure our website's different pages don't have any mistakes.

## 🤔 Background
This issue focuses specifically on fixing typos on the front page of our website. Your contributions here make a difference!

## 🤝 How You Can Contribute
We've broken it down into specific typos for you to address. Every contribution counts!

### **❗You must only assign yourself one task at a time to give everyone a chance to participate.❗**
You may assign yourself your next task after your current task is reviewed & accepted.
1. Front Page
    - [ ] Fix "instutition" typo to "institution" in tbDEX SDK text box.
![image](https://github.com/user-attachments/assets/68221e8c-0dd8-4323-837e-5b9f6eb7ee9e)
2. Make sure all tests are passing.

## 🌟 Resources
- [Developer Website](https://developer.tbd.website/)

## Getting Started
1. Comment ".take" on this issue to get assigned
2. Fork the repository and create a new branch for this task
3. Follow the tasks outlined above
4. Submit a pull request with your changes
6. Respond to any feedback during the review process

## Questions?
If you have any questions or need clarification, please comment on this issue or join our [Discord](https://discord.gg/tbd) community.

Happy coding! 🎉

**Comment by Adjoa** [comment]
.take

**Comment by Adjoa** [comment]
.take
