### ISSUE TITLE
Fix Casing in Developer Website's Projects Section on Front Page

### ISSUE THREAD

**Issue by taniashiba** [TBD54566975/developer.tbd.website#1570]
# Fix Casing in Developer Website's Projects Section on Front Page

## 🚀 Goal
We want to ensure our website's different pages don't have any mistakes.

## 🤔 Background
This issue focuses specifically on fixing typos in the projects page of our website. Your contributions here make a difference!

## 🤝 How You Can Contribute
We've broken it down into specific typos for you to address. Every contribution counts!

### **❗You must only assign yourself one task at a time to give everyone a chance to participate.❗**
You may assign yourself your next task after your current task is reviewed & accepted.
1. /projects Page
    - [ ] Update casing from "TBDEX" to "tbDEX"
![image](https://github.com/user-attachments/assets/66d747d4-f76d-4495-93d4-f33b8543232b)
2. Make sure all tests are passing.

## 🌟 Resources
- [Developer Website](https://developer.tbd.website/)

## Getting Started
1. Comment ".take" on this issue to get assigned
2. Fork the repository and create a new branch for this task
3. Follow the tasks outlined above
4. Submit a pull request with your changes
6. Respond to any feedback during the review process

## Questions?
If you have any questions or need clarification, please comment on this issue or join our [Discord](https://discord.gg/tbd) community.

Happy coding! 🎉

**Comment by pateldivyesh1323** [comment]
.take

**Comment by blackgirlbytes** [comment]
Hi @pateldivyesh1323 these issues are not ready yet. They're specifically made for Hacktoberfest, which happens in October, so the .take comment won't work just yet. You can circle back to our repo in October to pick up issues. Thank you!

**Comment by aniketh-varma** [comment]
.take

**Comment by blackgirlbytes** [comment]
Hey @aniketh-varma I noticed you're assigned to 8 issues and they're all typo issues. While we appreciate the enthusiasm, we kindly ask that you finish an issue before assigning yourself a new one. We want to give everyone a chance to be able to make their first contributions to open source. So, I'll leave you assigned to ticket #1578 , but I will unassign you from the rest.

If you finish that ticket, then you can assign yourself to a new one! Thank you

**Comment by aniketh-varma** [comment]
Hi @blackgirlbytes, apologies for assigning multiple tickets to myself. I wasn't aware that we have to work on a single ticket at a time. I will finish off one ticket and then move on to another. Thanks!

**Comment by taniashiba** [comment]
An additional notice has been added for your and everyone else's reference to all tasks & subtasks on taking one ticket at a time. @aniketh-varma Keep in mind that your current task must be reviewed & approved before you can take your next one! 

@pateldivyesh1323 I noticed you commented a month ago about this task, letting you know Hacktoberfest has started!! and you are able to take this task if you wish. Please read the guidelines above on how to assign yourself a task. Please assign yourself one task at a time.
