### ISSUE TITLE
Fix Typos in 7 Unexpected Ways Verifiable Credentials Are Used Today Blog Post

### ISSUE THREAD

**Issue by taniashiba** [TBD54566975/developer.tbd.website#1572]
# Fix Typos in 7 Unexpected Ways Verifiable Credentials Are Used Today Blog Post

## 🚀 Goal
We want to ensure our website's blog posts don't have any mistakes.

## 🤔 Background
This issue focuses specifically on fixing typos across on one of our blogs. Your contributions here make a difference!

## 🤝 How You Can Contribute
We've broken it down into specific typos for you to address. Every contribution counts!

### **❗You must only assign yourself one task at a time to give everyone a chance to participate.❗**
You may assign yourself your next task after your current task is reviewed & accepted.
1. Fix typos in 7 Unexpected Ways Verifiable Credentials Are Used Today Blog Post:
-  [ ] Change "Verifiable Credentials seem niche." to "Verifiable Credentials seems niche." to represent the singular concept
![image](https://github.com/user-attachments/assets/cef4323a-3988-4a95-8ef5-976aab48c23b)
2. Make sure all tests are passing.

## 🌟 Resources
- [7 Unexpected Ways Verifiable Credentials Are Used Today Blog Post](https://developer.tbd.website/blog/7-ways-we-use-vcs-today)
- [Blog, Developer Website](https://developer.tbd.website/blog)

## Getting Started
1. Comment ".take" on this issue to get assigned
2. Fork the repository and create a new branch for this task
4. Follow the tasks outlined above
5. Submit a pull request with your changes
6. Respond to any feedback during the review process

## Questions?
If you have any questions or need clarification, please comment on this issue or join our [Discord](https://discord.gg/tbd) community.

Happy coding! 🎉

**Comment by aniketh-varma** [comment]
.take

**Comment by blackgirlbytes** [comment]
Hey @aniketh-varma I noticed you're assigned to 8 issues and they're all typo issues. While we appreciate the enthusiasm, we kindly ask that you finish an issue before assigning yourself a new one. We want to give everyone a chance to be able to make their first contributions to open source. So, I'll leave you assigned to ticket #1578 , but I will unassign you from the rest.

If you finish that ticket, then you can assign yourself to a new one! Thank you

**Comment by Nabhel** [comment]
.take
