### ISSUE TITLE
Fix Typos in Beyond Blockchain: How Web5 Enables Fully Decentralized Apps Blog Post

### ISSUE THREAD

**Issue by taniashiba** [TBD54566975/developer.tbd.website#1573]
# Fix Typos in Beyond Blockchain: How Web5 Enables Fully Decentralized Apps Blog Post

## 🚀 Goal
We want to ensure our website's blog posts don't have any mistakes.

## 🤔 Background
This issue focuses specifically on fixing typos on one of our blog posts. Your contributions here make a difference!

## 🤝 How You Can Contribute
We've broken it down into specific typos for you to address. Every contribution counts!

### **❗You must only assign yourself one task at a time to give everyone a chance to participate.❗**
You may assign yourself your next task after your current task is reviewed & accepted.
1. Fix typos for Beyond Blockchain: How Web5 Enables Fully Decentralized Apps blog:
    - [ ] Fix "tenant" to be "tenet"    
![image](https://github.com/user-attachments/assets/e03b7f80-8475-4274-9d34-9f0df7e51aac)
    - [ ] Fix "the the tbDEX" to be "the tbDEX"
![image](https://github.com/user-attachments/assets/6e53b401-dc83-4887-86b7-f529602dece8)
2. Make sure all tests are passing.

## 🌟 Resources
- [Beyond Blockchain: How Web5 Enables Fully Decentralized Apps Blog Post](https://developer.tbd.website/blog/decentralized-apps)
- [Blog, Developer Website](https://developer.tbd.website/blog)

## Getting Started
1. Comment ".take" on this issue to get assigned
2. Fork the repository and create a new branch for this task
3. Follow the tasks outlined above
4. Submit a pull request with your changes
5. Respond to any feedback during the review process

## Questions?
If you have any questions or need clarification, please comment on this issue or join our [Discord](https://discord.gg/tbd) community.

Happy coding! 🎉

**Comment by aniketh-varma** [comment]
.take

**Comment by aniketh-varma** [comment]
.take

**Comment by blackgirlbytes** [comment]
Hey @aniketh-varma I noticed you're assigned to 8 issues and they're all typo issues. While we appreciate the enthusiasm, we kindly ask that you finish an issue before assigning yourself a new one. We want to give everyone a chance to be able to make their first contributions to open source. So, I'll leave you assigned to ticket #1578 , but I will unassign you from the rest.

If you finish that ticket, then you can assign yourself to a new one! Thank you

**Comment by Ankitv003** [comment]
no problem @EbonyLouis 😊🚀!

**Comment by Ankitv003** [comment]
hey @EbonyLouis , i want to contribute in javascript and react, do you have any issues for that ?

**Comment by taniashiba** [comment]
Hey @Ankitv003 - we actually have several projects including JS issues. 

Here are some suggestions:
- https://github.com/TBD54566975/tbd-examples/issues/81
- https://github.com/TBD54566975/incubation-dcx/issues/142
- https://github.com/csuwildcat/fllw/issues/7
- https://github.com/csuwildcat/aliased/issues/4

You can also view all participating repos here: https://github.com/orgs/TBD54566975/projects/44

Hope that helps 🥰🎃 happy hacking!
