### ISSUE TITLE
Fix Typos in API Reference Guides page

### ISSUE THREAD

**Issue by taniashiba** [TBD54566975/developer.tbd.website#1578]
# Fix Typos in API Reference Guides page

## 🚀 Goal
We want to ensure our website's documentation don't have any mistakes.

## 🤔 Background
This issue focuses specifically on fixing typos in one of our docs. Your contributions here make a difference!

## 🤝 How You Can Contribute
We've broken it down into specific typos for you to address. Every contribution counts!

### **❗You must only assign yourself one task at a time to give everyone a chance to participate.❗**
You may assign yourself your next task after your current task is reviewed & accepted.
1. Fix typos in API Reference Guides [page](https://developer.tbd.website/docs/api)
    - [ ] Fix "instutition" to be "institution"
![image](https://github.com/user-attachments/assets/65debf19-62ae-45a5-8b17-97ce0c36755c)
    - [ ] Fix "Self Sovereign Identity" to be "Self-Sovereign Identity" for consistency
![image](https://github.com/user-attachments/assets/1e8874c7-cc7d-4a2c-9139-f4791eccaab9)
2. Make sure all tests are passing.

## 🌟 Resources
- [API References Guides page](https://developer.tbd.website/docs/api)
- [Docs, Developer Website](https://developer.tbd.website/docs/)

## Getting Started
1. Comment ".take" on this issue to get assigned
2. Fork the repository and create a new branch for this task
3. Follow the tasks outlined above
4. Submit a pull request with your changes
5. Respond to any feedback during the review process

## Questions?
If you have any questions or need clarification, please comment on this issue or join our [Discord](https://discord.gg/tbd) community.

Happy coding! 🎉

**Comment by aniketh-varma** [comment]
.take

**Comment by blackgirlbytes** [comment]
Hey @aniketh-varma I noticed you're assigned to 8 issues and they're all typo issues. While we appreciate the enthusiasm, we kindly ask that you finish an issue before assigning yourself a new one. We want to give everyone a chance to be able to make their first contributions to open source. So, I'll leave you assigned to this ticket, but I will unassign you from the rest. 

If you finish this ticket, then you can assign yourself to a new one! Thank you

#1560 
#1569
#1570
#1572
#1573
#1575
#1576
#1577
#1578

**Comment by blackgirlbytes** [comment]
Hey @aniketh-varma I noticed you're assigned to 8 issues and they're all typo issues. While we appreciate the enthusiasm, we kindly ask that you finish an issue before assigning yourself a new one. We want to give everyone a chance to be able to make their first contributions to open source. So, I'll leave you assigned to ticket #1578 , but I will unassign you from the rest.

If you finish that ticket, then you can assign yourself to a new one! Thank you
