### ISSUE TITLE
Create Discord Slash Command That Lists TBD Social Links 

### ISSUE THREAD

**Issue by taniashiba** [TBD54566975/developer.tbd.website#1579]
# Create Discord Slash Command That Brings Up Social Links for TBD

## 🚀 Goal
We want to share our social links at ease by simply typing /socials or !socials in our community Discord.

## 🤔 Background
This issue focuses specifically on creating a command that brings up a specific message.

## 🤝 How You Can Contribute
We've broken it down below into several steps.

### **❗You must only assign yourself one task at a time to give everyone a chance to participate.❗**
You may assign yourself your next task after your current task is reviewed & accepted.
1. Create slash command using the word "socials"
2. In message that pops up, be sure to include the following links:
- Include all of our links from our linktree: https://linktr.ee/tbdevs
3. Make sure command is set to public.
4. Gain "Discord Contributor" role from Tania for our community Discord.
5. Make sure you manually test slash command is working.

## 🌟 Resources
- [Discord](https://discord.gg/tbd)

## Getting Started
1. Comment ".take" on this issue to get assigned
2. Fork the repository and create a new branch for this task
6. Follow the tasks outlined above
7. Submit a pull request with your changes
8. Respond to any feedback during the review process

## Questions?
If you have any questions or need clarification, please comment on this issue or join our [Discord](https://discord.gg/tbd) community.

Happy coding! 🎉

**Comment by darshitdudhaiya** [comment]
Hi @taniashiba 
I'd like to work on this issue. I believe my skills. i would be a good fit for this task.

Please let me know if I can be assigned to this issue.

**Comment by blackgirlbytes** [comment]
Hey @darshitdudhaiya! Hacktoberfest is now live, so if you wanted to try this issue, you should be able to to self-assign the issue to yourself. Please read the issue to learn how to self-assign an issue.

Thank you!

**Comment by darshitdudhaiya** [comment]
.take

**Comment by aniketh-varma** [comment]
Hi @blackgirlbytes @taniashiba, can I pick this issue if its not being worked on?

**Comment by taniashiba** [comment]
Hi @aniketh-varma -- as this issue is currently assigned to someone, you can't take this issue. However, there are other possible Discord functions we could add as tasks. If this is something you'd be interested, let me know and I will develop them for you.

**Comment by aniketh-varma** [comment]
Sure @taniashiba, I would love to work on such issues. I wanted to pick this one since I thought it has been inactive for a couple of days.

**Comment by aniketh-varma** [comment]
Hi @taniashiba, this issue seems to have been inactive for a long time. Can I start working on it?

**Comment by taniashiba** [comment]
Hi @aniketh-varma - I think that's appropriate since it's been 2 weeks. Let me assign it to you!

**Comment by aniketh-varma** [comment]
@taniashiba, I just wanted to confirm the approach. Are we looking to create a bot for this purpose, or can we integrate an existing Discord App that can help us solve this issue?
I noticed that we have the Carl-bot (named `tbd-bot`), and found out that they have a feature for this (https://docs.carl.gg/#/tagstriggers?id=tags). Will something like this be of any help to us?
Thanks!

**Comment by taniashiba** [comment]
Hi @aniketh-varma - I checked in on this and realized that we can already do this, so I'll be closing it out as a task since there's no need to build a bot. And adding the slash commands would require copy on my end. Feel free to explore our wide variety of other tasks!
