### ISSUE TITLE
Fix Typos in What Are VCs Page

### ISSUE THREAD

**Issue by taniashiba** [TBD54566975/developer.tbd.website#1582]
# Fix Typos in What Are VCs Page

## 🚀 Goal
We want to ensure our website's documentation don't have any mistakes.

## 🤔 Background
This issue focuses specifically on fixing typos across our docs. Your contributions here make a difference!

## 🤝 How You Can Contribute
We've broken it down into specific typos for you to address. Every contribution counts!

### **❗You must only assign yourself one task at a time to give everyone a chance to participate.❗**
You may assign yourself your next task after your current task is reviewed & accepted.
1. Fix Typos What Are VCs [page](https://developer.tbd.website/docs/web5/verifiable-credentials/what-are-vcs)
    - [ ] Fix "Affinidi Pet. Ltd" to be "Affinidi Pte. Ltd"
![image](https://github.com/user-attachments/assets/e4f9395a-0d56-4a7b-9723-fbafd0d777ee)
    - [ ] Fix "made up story" to be "made-up story"
![image](https://github.com/user-attachments/assets/840997e4-8097-4dc3-9962-393c5f2695dd)
    - [ ] Fix "employer(verifier)" to be "employer (verifier)" (space before parentheses)
![image](https://github.com/user-attachments/assets/994fdf2e-77bf-4a2c-8d92-8826b5bf9b93)
    - [ ] Fix "pubic-private key pair" to be "public-private key pair"
![image](https://github.com/user-attachments/assets/370b4738-80a6-4d49-b3a8-4a41ca013d2e)
    - [ ] Change "now verified payload" to be "now-verified payload"
![image](https://github.com/user-attachments/assets/cfbfc9f0-b5d5-4f50-a2b6-4817ce643cc8)
    - [ ] Capitalize "Looking to play around with verifiable credentials yourself?" to be "Looking to play around with Verifiable Credentials yourself?" for consistency
![image](https://github.com/user-attachments/assets/896b0edb-fcec-4a7a-8055-7b442290490d)
2. Make sure all tests are passing.

## 🌟 Resources
- [What Are VCs page](https://developer.tbd.website/docs/web5/verifiable-credentials/what-are-vcs)
- [Docs, Developer Website](https://developer.tbd.website/docs/)

## Getting Started
1. Comment ".take" on this issue to get assigned
2. Fork the repository and create a new branch for this task
3. Follow the tasks outlined above
4. Submit a pull request with your changes
5. Respond to any feedback during the review process

## Questions?
If you have any questions or need clarification, please comment on this issue or join our [Discord](https://discord.gg/tbd) community.

Happy coding! 🎉

**Comment by pateldivyesh1323** [comment]
.take
