### ISSUE TITLE
Fix Typos in Verify Credentials Page

### ISSUE THREAD

**Issue by taniashiba** [TBD54566975/developer.tbd.website#1584]
# Fix Typos in Verify Credentials Page

## 🚀 Goal
We want to ensure our website's documentation don't have any mistakes.

## 🤔 Background
This issue focuses specifically on fixing typos across our docs. Your contributions here make a difference!

## 🤝 How You Can Contribute
We've broken it down into specific typos for you to address. Every contribution counts!

### **❗You must only assign yourself one task at a time to give everyone a chance to participate.❗**
You may assign yourself your next task after your current task is reviewed & accepted.
1. Fix Typos in Verify Credentials [page](https://developer.tbd.website/docs/web5/verifiable-credentials/verify-vc)
    - [ ] Capitalize Verifiable Credentials (VC) for consistency
![image](https://github.com/user-attachments/assets/4d0050f7-2879-4363-969b-b797260b956d)
    - [ ] Capitalize Verifiable Presentations (VP) for consistency
![image](https://github.com/user-attachments/assets/d34cf2d2-c64e-4b91-bf2b-9123197ee471)
    - [ ] Change "multiple things" to "multiple elements" for accuracy
![image](https://github.com/user-attachments/assets/d155c5ef-ebc2-499e-9f31-06ffd0fd52f7)
2. Make sure all tests are passing.

## 🌟 Resources
- [Verify Credentials Page](https://developer.tbd.website/docs/web5/verifiable-credentials/verify-vc)
- [Docs, Developer Website](https://developer.tbd.website/docs/)

## Getting Started
1. Comment ".take" on this issue to get assigned
2. Fork the repository and create a new branch for this task
3. Follow the tasks outlined above
4. Submit a pull request with your changes
5. Respond to any feedback during the review process

## Questions?
If you have any questions or need clarification, please comment on this issue or join our [Discord](https://discord.gg/tbd) community.

Happy coding! 🎉

**Comment by aazam-gh** [comment]
.take

**Comment by EbonyLouis** [comment]
Thanks @aazam-gh 🎉!
