### ISSUE TITLE
Fix Typos in VC Workflow Page

### ISSUE THREAD

**Issue by taniashiba** [TBD54566975/developer.tbd.website#1586]
# Fix Typos in VC Workflow Page

## 🚀 Goal
We want to ensure our website's documentation don't have any mistakes.

## 🤔 Background
This issue focuses specifically on fixing typos across our docs. Your contributions here make a difference!

## 🤝 How You Can Contribute
We've broken it down into specific typos for you to address. Every contribution counts!

### **❗You must only assign yourself one task at a time to give everyone a chance to participate.❗**
You may assign yourself your next task after your current task is reviewed & accepted.
1. Fix Typos in VC Workflow [page](https://developer.tbd.website/docs/web5/verifiable-credentials/fan-club-vc)
    - [ ] Fix "identitfiers" to be "identifiers"
![image](https://github.com/user-attachments/assets/6bfbb20b-104e-4b03-bfd4-0615c0d18aa2)
    - [ ] Fix "satifies" to be "satisfies"
![image](https://github.com/user-attachments/assets/e9bcc29d-1a3a-4b86-a918-4f2db367d726)
2. Make sure all tests are passing.

## 🌟 Resources
- [VC Workflow Page](https://developer.tbd.website/docs/web5/verifiable-credentials/fan-club-vc)
- [Docs, Developer Website](https://developer.tbd.website/docs/)

## Getting Started
1. Comment ".take" on this issue to get assigned
2. Fork the repository and create a new branch for this task
3. Follow the tasks outlined above
4. Submit a pull request with your changes
5. Respond to any feedback during the review process

## Questions?
If you have any questions or need clarification, please comment on this issue or join our [Discord](https://discord.gg/tbd) community.

Happy coding! 🎉

**Comment by Siddharthgup** [comment]
.take

**Comment by blackgirlbytes** [comment]
Hey @Siddharthgup! Hacktoberfest is now live, so if you wanted to try assigning yourself to the issue again, please retry your comment, and you should get auto-assigned the issue.
