### ISSUE TITLE
Fix Typos in What Are DWNs Page

### ISSUE THREAD

**Issue by taniashiba** [TBD54566975/developer.tbd.website#1587]
# Fix Typos in What Are DWNs Page

## 🚀 Goal
We want to ensure our website's documentation don't have any mistakes.

## 🤔 Background
This issue focuses specifically on fixing typos across our docs. Your contributions here make a difference!

## 🤝 How You Can Contribute
We've broken it down into specific typos for you to address. Every contribution counts!

### **❗You must only assign yourself one task at a time to give everyone a chance to participate.❗**
You may assign yourself your next task after your current task is reviewed & accepted.
1. Fix Typos in What are DWNs [page](https://developer.tbd.website/docs/web5/decentralized-web-nodes/what-are-dwns)
    - [ ] Add space between "Identifer(DID)" to be "Identifier (DID)"
![image](https://github.com/user-attachments/assets/ad000116-a2de-4fb2-9b4a-97e37f930d75)
    - [ ] Change "up the application layer" to be "up to the application layer" ("to" for clarity)
![image](https://github.com/user-attachments/assets/21d69222-d048-4e2e-8787-e6f699a6472f)
2. Make sure all tests are passing.

## 🌟 Resources
- [What Are DWNs page](https://developer.tbd.website/docs/web5/decentralized-web-nodes/what-are-dwns)
- [Docs, Developer Website](https://developer.tbd.website/docs/)

## Getting Started
1. Comment ".take" on this issue to get assigned
2. Fork the repository and create a new branch for this task
3. Follow the tasks outlined above
4. Submit a pull request with your changes
5. Respond to any feedback during the review process

## Questions?
If you have any questions or need clarification, please comment on this issue or join our [Discord](https://discord.gg/tbd) community.

Happy coding! 🎉

**Comment by Lymah123** [comment]
.take

**Comment by EbonyLouis** [comment]
Thanks! @Lymah123
