### ISSUE TITLE
Fix Typos in Query DWN Records Page

### ISSUE THREAD

**Issue by taniashiba** [TBD54566975/developer.tbd.website#1588]
# Fix Typos in Query DWN Records Page

## 🚀 Goal
We want to ensure our website's documentation don't have any mistakes.

## 🤔 Background
This issue focuses specifically on fixing typos across our docs. Your contributions here make a difference!

## 🤝 How You Can Contribute
We've broken it down into specific typos for you to address. Every contribution counts!

### **❗You must only assign yourself one task at a time to give everyone a chance to participate.❗**
You may assign yourself your next task after your current task is reviewed & accepted.
1. Fix Typos in Query DWN Records [page](https://developer.tbd.website/docs/web5/decentralized-web-nodes/query-from-dwn)
    - [ ] Fix "publshedAscending" to be "publishedAscending"
![image](https://github.com/user-attachments/assets/63a30345-b1c3-42db-ad99-654121524958)
2. Make sure all tests are passing.

## 🌟 Resources
- [Query DWN Records Page](https://developer.tbd.website/docs/web5/decentralized-web-nodes/query-from-dwn)
- [Docs, Developer Website](https://developer.tbd.website/docs/)

## Getting Started
1. Comment ".take" on this issue to get assigned
2. Fork the repository and create a new branch for this task
3. Follow the tasks outlined above
4. Submit a pull request with your changes
5. Respond to any feedback during the review process

## Questions?
If you have any questions or need clarification, please comment on this issue or join our [Discord](https://discord.gg/tbd) community.

Happy coding! 🎉

**Comment by aniketh-varma** [comment]
.take
