### ISSUE TITLE
Fix Typos in Common Errors Page

### ISSUE THREAD

**Issue by taniashiba** [TBD54566975/developer.tbd.website#1589]
# Fix Typos in Common Errors Page

## 🚀 Goal
We want to ensure our website's documentation don't have any mistakes.

## 🤔 Background
This issue focuses specifically on fixing typos across our docs. Your contributions here make a difference!

## 🤝 How You Can Contribute
We've broken it down into specific typos for you to address. Every contribution counts!

### **❗You must only assign yourself one task at a time to give everyone a chance to participate.❗**
You may assign yourself your next task after your current task is reviewed & accepted.
1. Fix Typos in Common Errors [page](https://developer.tbd.website/docs/web5/decentralized-web-nodes/troubleshooting/common-errors)
    - [ ] Fix "functon" to be "function"
![image](https://github.com/user-attachments/assets/e6492cd1-e037-4e5f-8ad7-67ee37ad3f2e)
2. Make sure all tests are passing.

## 🌟 Resources
- [Common Errors Page](https://developer.tbd.website/docs/web5/decentralized-web-nodes/troubleshooting/common-errors)
- [Docs, Developer Website](https://developer.tbd.website/docs/)

## Getting Started
1. Comment ".take" on this issue to get assigned
2. Fork the repository and create a new branch for this task
3. Follow the tasks outlined above
4. Submit a pull request with your changes
5. Respond to any feedback during the review process

## Questions?
If you have any questions or need clarification, please comment on this issue or join our [Discord](https://discord.gg/tbd) community.

Happy coding! 🎉

**Comment by sudojarvis** [comment]
.talk

**Comment by patelharsh03** [comment]
.take

**Comment by ANIRUDH-333** [comment]
.take
