### ISSUE TITLE
Fix Typos in Creating Offerings Page

### ISSUE THREAD

**Issue by taniashiba** [TBD54566975/developer.tbd.website#1591]
# Fix Typos in Creating Offerings Page

## 🚀 Goal
We want to ensure our website's documentation don't have any mistakes.

## 🤔 Background
This issue focuses specifically on fixing typos across our docs. Your contributions here make a difference!

## 🤝 How You Can Contribute
We've broken it down into specific typos for you to address. Every contribution counts!

### **❗You must only assign yourself one task at a time to give everyone a chance to participate.❗**
You may assign yourself your next task after your current task is reviewed & accepted.
1. Fix Typos in Creating Offerings [page](https://developer.tbd.website/docs/tbdex/pfi/creating-offerings)
    - [ ] Change "a example" to be "an example"
![image](https://github.com/user-attachments/assets/4d3ba495-9d44-45d2-b8fb-40b3b1136d56)
2. Make sure all tests are passing.

## 🌟 Resources
- [Creating Offerings Page](https://developer.tbd.website/docs/tbdex/pfi/creating-offerings)
- [Docs, Developer Website](https://developer.tbd.website/docs/)

## Getting Started
1. Comment ".take" on this issue to get assigned
2. Fork the repository and create a new branch for this task
3. Follow the tasks outlined above
4. Submit a pull request with your changes
5. Respond to any feedback during the review process

## Questions?
If you have any questions or need clarification, please comment on this issue or join our [Discord](https://discord.gg/tbd) community.

Happy coding! 🎉

**Comment by imperialc0der** [comment]
.take

**Comment by taniashiba** [comment]
Hi @imperialc0der - I noticed you also assigned yourself the following task https://github.com/TBD54566975/developer.tbd.website/issues/1561

Within the issues above, it states that you must only take one issue at a time, and wait for your PR to be **reviewed** & **accepted** before taking on another issue. This is to give everyone a fair chance at participating, especially for tasks that don't require code. 

Is there a preference for one of these tasks you'd like to keep? After your first issue is reviewed & accepted, you're free to take on the next. I'd also highly encourage you to explore all our participating projects here: https://github.com/orgs/TBD54566975/projects/44
