### ISSUE TITLE
Fix Typos in Credential Issuance Page

### ISSUE THREAD

**Issue by taniashiba** [TBD54566975/developer.tbd.website#1594]
# Fix Typos in Credential Issuance Page

## 🚀 Goal
We want to ensure our website's documentation don't have any mistakes.

## 🤔 Background
This issue focuses specifically on fixing typos across our docs. Your contributions here make a difference!

## 🤝 How You Can Contribute
We've broken it down into specific typos for you to address. Every contribution counts!

### **❗You must only assign yourself one task at a time to give everyone a chance to participate.❗**
You may assign yourself your next task after your current task is reviewed & accepted.
1. Fix Typos in Credential Issuance [page](https://developer.tbd.website/docs/tbdex/issuer/vc-issuance)
    - [ ] Fix "implmented" to "implemented"
![image](https://github.com/user-attachments/assets/98e049e0-4bbb-404a-b866-9dcd7458bc09)
2. Make sure all tests are passing.

## 🌟 Resources
- [Credential Issuance Page](https://developer.tbd.website/docs/tbdex/issuer/vc-issuance)
- [Docs, Developer Website](https://developer.tbd.website/docs/)

## Getting Started
1. Comment ".take" on this issue to get assigned
2. Fork the repository and create a new branch for this task
3. Follow the tasks outlined above
4. Submit a pull request with your changes
5. Respond to any feedback during the review process

## Questions?
If you have any questions or need clarification, please comment on this issue or join our [Discord](https://discord.gg/tbd) community.

Happy coding! 🎉

**Comment by navacodes** [comment]
.take
