### ISSUE TITLE
Create Your Own Blog Comparing Different DID Methods

### ISSUE THREAD

**Issue by taniashiba** [TBD54566975/developer.tbd.website#1607]
# Create Your Own Blog Comparing Different DID Methods

## 🚀 Goal
Use what you learn about DID methods during Hacktoberfest to create a blog post on your site focused on different DID methods.

## 🤔 Background
This issue focuses specifically on creating your own content regarding Web5 / tbDEX topics. Your contributions here will help developers kickstart their Web5 projects!

## 🤝 How You Can Contribute
Follow the steps below to contribute your content directly to our repository.

### **❗You must only assign yourself one task at a time to give everyone a chance to participate.❗**
You may assign yourself another task after your current one is reviewed and accepted.

- [ ] You must host your content on your own website or channel.
- [ ] Add your content information directly to the `site/src/externalContributors.json` file in the repository.
- [ ] Save your image in the `site/static/image/external-contributor/` directory, ensuring the image is in a **16:9 ratio**.
- [ ] Create a pull request with your changes for review.
- [ ] Link your submitted PR in a comment here to count towards Hacktoberfest.

Your contribution in `externalContributors.json` must include:
- [ ] Type: Video, Blog, Social (please choose the appropriate one)
- [ ] Thumbnail: the path to your image, e.g., `/img/external-contributor/yourimage.png`
- [ ] Title: the title of your content
- [ ] Link: a direct link to your content
- [ ] Your name

Here’s an example of the JSON format to follow:

```json
[
    {
        "type": "blog",
        "thumbnail": "/img/external-contributor/yourimage.png",
        "title": "Exploring Web5",
        "link": "https://linktoyourcontent.com/web5-post",
        "contributor": "Your Name"
    }
]
```

Available `type` options:
- Video
- Blog
- Social

## 🌟 Resources
- [ ] [Our Blogs](https://developer.tbd.website/blog/)
- [ ] [Our YouTube channel](https://www.youtube.com/@tbd.videos)

## Getting Started
1. Comment ".take" on this issue to get assigned
2. Fork the repository and create a new branch for this task
3. Follow the tasks outlined above
4. Submit a pull request with your changes
5. Respond to any feedback during the review process

## Questions?
If you have any questions or need clarification, please comment on this issue or join our [Discord](https://discord.gg/tbd) community.

Happy coding! 🎉

**Comment by taniashiba** [comment]
Hi @Lymah123! We will start officially assigning tasks for Hacktoberfest when it officially starts, which is tomorrow October 1st. Circle back then and there should also be a .take command as well. Thank you for your patience & eagerness to contribute! ❤️

**Comment by Lymah123** [comment]
> Hi @Lymah123! We will start officially assigning tasks for Hacktoberfest when it officially starts, which is tomorrow October 1st. Circle back then and there should also be a .take command as well. Thank you for your patience & eagerness to contribute! ❤️

Noted @taniashiba. Thanks

**Comment by Lymah123** [comment]
.take

**Comment by blackgirlbytes** [comment]
Hey @Lymah123! Hacktoberfest is now live, so if you wanted to try assigning yourself to the issue again, please retry your comment, and you should get auto-assigned the issue.

**Comment by Lymah123** [comment]
.take

**Comment by EbonyLouis** [comment]
@Lymah123 The steps to complete this ticket have been updated. Instead of opening an issue, you can now add your content directly to our repo. If you have any questions after reviewing the updated instructions, feel free to reach out.

I'm happy to help!

**Comment by blackgirlbytes** [comment]
Hi @Lymah123, we've gotten a few questions about this, so I just want to inform you too! As you work ont his blog post, please make sure you talk about DIDs in the context of Web5.

Perhaps, you can include DID methods that the Web5 ecosystem supports for example:
- [did:dht](https://developer.tbd.website/docs/glossary#did-method---dht)
- [did: web](https://developer.tbd.website/docs/glossary#did-method---web)
- [did:jwk](https://developer.tbd.website/docs/glossary#did-method---jwk)

Here's a few other related resources:
- https://developer.tbd.website/blog/things-you-didnt-know-about-dids
- https://developer.tbd.website/blog/did-dht

**Comment by Lymah123** [comment]
Noted @blackgirlbytes , thanks for the info.
