### ISSUE TITLE
Create Your Own Blog About Standing Up A PFI

### ISSUE THREAD

**Issue by taniashiba** [TBD54566975/developer.tbd.website#1608]
# Create Your Own Blog About Standing Up A PFI

## 🚀 Goal
Use what you learn about standing up a Participating Financial Institution (PFI) to create content to teach others about this topic.

## 🤔 Background
This issue focuses specifically on creating your own content regarding Web5 & tbDEX topics. Your contributions here will help developers kickstart their projects!

## 🤝 How You Can Contribute
We've broken it down into smaller tasks. Every contribution counts!

### **❗You must only assign yourself one task at a time to give everyone a chance to participate.❗**
You may assign yourself your next task after your current task is reviewed & accepted.
- [ ] You must host your content on your own website or channel.
- [ ] Add your content information directly to the `site/src/externalContributors.json` file in the repository.
- [ ] Save your image in the `site/static/image/external-contributor/` directory, ensuring the image is in a **16:9 ratio**.
- [ ] Create a pull request with your changes for review.
- [ ] Link your submitted PR in a comment here to count towards Hacktoberfest.

Your contribution in `externalContributors.json` must include:
- [ ] Type: Video, Blog, Social (please choose the appropriate one)
- [ ] Thumbnail: the path to your image, e.g., `/img/external-contributor/yourimage.png`
- [ ] Title: the title of your content
- [ ] Link: a direct link to your content
- [ ] Your name

Here’s an example of the JSON format to follow:

```json
[
    {
        "type": "blog",
        "thumbnail": "/img/external-contributor/yourimage.png",
        "title": "Exploring Web5",
        "link": "https://linktoyourcontent.com/web5-post",
        "contributor": "Your Name"
    }
]
```

Available `type` options:
- Video
- Blog
- Social

## 🌟 Resources
- [PFI Liquidity Node on tbDEX](https://www.youtube.com/watch?v=jP7HqLM1CMo)
- [tbDEX 1.0](https://www.youtube.com/watch?v=MWMm513SCKA)
- [PFI Quickstart](https://developer.tbd.website/docs/tbdex/pfi-quickstart)
- [PFI overview](https://developer.tbd.website/docs/tbdex/pfi/overview)
- [Our Blogs](https://developer.tbd.website/blog/)
- [Our YouTube channel](https://www.youtube.com/@tbd.videos)

## Getting Started
1. Comment ".take" on this issue to get assigned
2. Fork the repository and create a new branch for this task
3. Follow the tasks outlined above
4. Submit a pull request with your changes
5. Respond to any feedback during the review process

## Questions?
If you have any questions or need clarification, please comment on this issue or join our [Discord](https://discord.gg/tbd) community.

Happy coding! 🎉

**Comment by Lymah123** [comment]
.take

**Comment by blackgirlbytes** [comment]
Hi @Lymah123! Thanks for picking this up. I saw that you were trying to grab the issue on DWNs, so I opened a new issue for you. Also please address the changes I requested in your last PR on #1800 before picking up more issues. Thank you!

**Comment by Lymah123** [comment]
> Hi @Lymah123! Thanks for picking this up. I saw that you were trying to grab the issue on DWNs, so I opened a new issue for you. Also please address the changes I requested in your last PR on #1800 before picking up more issues. Thank you!

Yes, thank you. I have addressed the changes you requested.
