### ISSUE TITLE
Create Your Own Blog About Your Experience in TBD Hacktoberfest

### ISSUE THREAD

**Issue by taniashiba** [TBD54566975/developer.tbd.website#1611]
# Create Your Own Blog About Your Experience in TBD Hacktoberfest

## 🚀 Goal
We want you to share your experience in Hacktoberfest with us in your own blog post.

## 🤔 Background
This issue focuses specifically on documenting and summarizing your experience during this year's Hacktoberfest in a blog post. Document the contributions you've made with us, what you learned, and what you'd like to see next year. Your contribution will help others learn and get excited for future hackathons!

## 🤝 How You Can Contribute
We've broken it down into smaller tasks. Every contribution counts!

### **❗You must only assign yourself one task at a time to give everyone a chance to participate.❗**
You may assign yourself your next task after your current task is reviewed & accepted.
- [ ] You must host your content on your own website or channel.
- [ ] Add your content information directly to the `site/src/externalContributors.json` file in the repository.
- [ ] Save your image in the `site/static/image/external-contributor/` directory, ensuring the image is in a **16:9 ratio**.
- [ ] Create a pull request with your changes for review.
- [ ] Link your submitted PR in a comment here to count towards Hacktoberfest.

Your contribution in `externalContributors.json` must include:
- [ ] Type: Video, Blog, Social (please choose the appropriate one)
- [ ] Thumbnail: the path to your image, e.g., `/img/external-contributor/yourimage.png`
- [ ] Title: the title of your content
- [ ] Link: a direct link to your content
- [ ] Your name

Here’s an example of the JSON format to follow:

```json
[
    {
        "type": "blog",
        "thumbnail": "/img/external-contributor/yourimage.png",
        "title": "Exploring Web5",
        "link": "https://linktoyourcontent.com/web5-post",
        "contributor": "Your Name"
    }
]
```

Available `type` options:
- Video
- Blog
- Social

## 🌟 Resources
- [ ] [Our Blogs](https://developer.tbd.website/blog/)
- [ ] [Our YouTube channel](https://www.youtube.com/@tbd.videos)

## Getting Started
1. Comment ".take" on this issue to get assigned
2. Fork the repository and create a new branch for this task
3. Follow the tasks outlined above
4. Submit a pull request with your changes
5. Respond to any feedback during the review process

## Questions?
If you have any questions or need clarification, please comment on this issue or join our [Discord](https://discord.gg/tbd) community.

Happy coding! 🎉

**Comment by Nabhel** [comment]
.take
