### ISSUE TITLE
Create Your Own Blog About Leveraging DRLs

### ISSUE THREAD

**Issue by taniashiba** [TBD54566975/developer.tbd.website#1613]
# Create Your Own Blog About Leveraging DRLs

## 🚀 Goal
We want you to share what you've learned about leveraging [Decentralized Resource Locators (DRLs)](https://developer.tbd.website/docs/web5/decentralized-web-nodes/access-data-with-drls) in your own blog post.

## 🤔 Background
This issue focuses specifically on creating a blog post to teach others about DRLs. Your contribution here will help developers learn about this topic!

## 🤝 How You Can Contribute
We've broken it down into smaller tasks. Every contribution counts!

### **❗You must only assign yourself one task at a time to give everyone a chance to participate.❗**
You may assign yourself your next task after your current task is reviewed & accepted.
- [ ] You must host your content on your own website or channel.
- [ ] Add your content information directly to the `site/src/externalContributors.json` file in the repository.
- [ ] Save your image in the `site/static/image/external-contributor/` directory, ensuring the image is in a **16:9 ratio**.
- [ ] Create a pull request with your changes for review.
- [ ] Link your submitted PR in a comment here to count towards Hacktoberfest.
- [ ] DRLs are Decentralized Resource Locators ..you can learn about them here: 
    - [ ] https://developer.tbd.website/docs/web5/decentralized-web-nodes/access-data-with-drls
    - [ ] https://github.com/TBD54566975/tbd-examples/blob/main/javascript/dwa-starter-react-vite/README.md

Your contribution in `externalContributors.json` must include:
- [ ] Type: Video, Blog, Social (please choose the appropriate one)
- [ ] Thumbnail: the path to your image, e.g., `/img/external-contributor/yourimage.png`
- [ ] Title: the title of your content
- [ ] Link: a direct link to your content
- [ ] Your name

Here’s an example of the JSON format to follow:

```json
[
    {
        "type": "blog",
        "thumbnail": "/img/external-contributor/yourimage.png",
        "title": "Exploring Web5",
        "link": "https://linktoyourcontent.com/web5-post",
        "contributor": "Your Name"
    }
]
```

Available `type` options:
- Video
- Blog
- Social

## 🌟 Resources
- [ ] [Decentralized Resource Locators Guide](https://developer.tbd.website/docs/web5/decentralized-web-nodes/access-data-with-drls)
- [ ] [Our Blogs](https://developer.tbd.website/blog/)
- [ ] [Our YouTube channel](https://www.youtube.com/@tbd.videos)

## Getting Started
This content task is part of Hacktoberfest! We welcome contributions from creators of all skill levels. Here's how you can get started:

1. Read the [contribution guidelines](#)
2. Read the [code of conduct](#)
3. Choose a content-specific task from the list above
4. Comment ".take" on the corresponding issue to get assigned the task
5. Fork the repository and create a new branch for your work
6. Make your changes and submit a pull request
7. Wait for review and address any feedback

## Questions?
If you have any questions or need clarification, please comment on this issue or join our [Discord](https://discord.gg/tbd) community.

Happy coding! 🎉

**Comment by KiranBaliga** [comment]
Please assign this task to me as a part of hacktoberfest 2024

**Comment by KiranBaliga** [comment]
.take

**Comment by KiranBaliga** [comment]
@taniashiba Please review the PR and action accordingly. Thank you!

**Comment by blackgirlbytes** [comment]
Hi @KiranBaliga!! Thanks for the contribution. The blog post is interesting.. but that's not the DRLs that we're referring to...DRLs are Decentralized Resource Locators.

Here's a few places you can learn about it:

https://developer.tbd.website/docs/web5/decentralized-web-nodes/access-data-with-drls
https://github.com/TBD54566975/tbd-examples/blob/main/javascript/dwa-starter-react-vite/README.md
https://www.youtube.com/live/Wh5Cndgcc_E?feature=shared
