### ISSUE TITLE
Create Your Own Blog About Resolving DIDs

### ISSUE THREAD

**Issue by taniashiba** [TBD54566975/developer.tbd.website#1614]
# Create Your Own Blog About Resolving DIDs

## 🚀 Goal
We want you to share what you've learned about resolving DIDs in your own blog post.

## 🤔 Background
This issue focuses specifically on creating a blog post to teach others about resolving DIDs. Your contribution here will help developers learn about this topic!

## 🤝 How You Can Contribute
We've broken it down into smaller tasks. Every contribution counts!

### **❗You must only assign yourself one task at a time to give everyone a chance to participate.❗**
You may assign yourself your next task after your current task is reviewed & accepted.
- [ ] You must host your content on your own website or channel.
- [ ] Add your content information directly to the `site/src/externalContributors.json` file in the repository.
- [ ] Save your image in the `site/static/image/external-contributor/` directory, ensuring the image is in a **16:9 ratio**.
- [ ] Create a pull request with your changes for review.
- [ ] Link your submitted PR in a comment here to count towards Hacktoberfest.

Your contribution in `externalContributors.json` must include:
- [ ] Type: Video, Blog, Social (please choose the appropriate one)
- [ ] Thumbnail: the path to your image, e.g., `/img/external-contributor/yourimage.png`
- [ ] Title: the title of your content
- [ ] Link: a direct link to your content
- [ ] Your name

Here’s an example of the JSON format to follow:

```json
[
    {
        "type": "blog",
        "thumbnail": "/img/external-contributor/yourimage.png",
        "title": "Exploring Web5",
        "link": "https://linktoyourcontent.com/web5-post",
        "contributor": "Your Name"
    }
]
```

Available `type` options:
- Video
- Blog
- Social

## 🌟 Resources
- [ ] [Our Blogs](https://developer.tbd.website/blog/)
- [ ] [Our YouTube channel](https://www.youtube.com/@tbd.videos)

## Getting Started
This content task is part of Hacktoberfest! We welcome contributions from creators of all skill levels. Here's how you can get started:

1. Read the [contribution guidelines](#)
2. Read the [code of conduct](#)
3. Choose a content-specific task from the list above
4. Comment ".take" on the corresponding issue to get assigned the task
5. Fork the repository and create a new branch for your work
6. Make your changes and submit a pull request
7. Wait for review and address any feedback

## Questions?
If you have any questions or need clarification, please comment on this issue or join our [Discord](https://discord.gg/tbd) community.

Happy coding! 🎉

**Comment by KiranBaliga** [comment]
Please assign this task to me as a part of hacktoberfest 2024

**Comment by taniashiba** [comment]
Hi @KiranBaliga! Thank you for commenting. We are assigning tasks tomorrow, October 1st, when Hacktoberfest officially starts! We will also be adding the ability to self assign for this purpose as well. Thank you for your diligence and patience! 🙏

**Comment by KiranBaliga** [comment]
.take

**Comment by blackgirlbytes** [comment]
Hey @KiranBaliga! Hacktoberfest is now live, so if you wanted to try assigning yourself to the issue again, please retry your comment, and you should get auto-assigned the issue.

**Comment by KiranBaliga** [comment]
.take

**Comment by Chrissiku** [comment]
.take
