### ISSUE TITLE
Create Your Own Blog About Key Management for DIDs

### ISSUE THREAD

**Issue by taniashiba** [TBD54566975/developer.tbd.website#1615]
# Create Your Own Blog About Key Management for DIDs

## 🚀 Goal
We want you to share what you've learned about key management in your own blog post.

## 🤔 Background
This issue focuses specifically on creating a blog post to teach others about DID key management. Your contribution here will help developers learn about this topic!

## 🤝 How You Can Contribute
Follow the steps below to contribute your content directly to our repository.

### **❗You must only assign yourself one task at a time to give everyone a chance to participate.❗**
You may assign yourself another task after your current one is reviewed and accepted.
- [ ] You must create your content from the context of Web5 / strictly about Web5, not Web3.
- [ ] You must host your content on your own website or channel.
- [ ] Add your content information directly to the `site/src/externalContributors.json` file in the repository.
- [ ] Save your image in the `site/static/image/external-contributor/` directory, ensuring the image is in a **16:9 ratio**.
- [ ] Create a pull request with your changes for review.
- [ ] Link your submitted PR in a comment here to count towards Hacktoberfest.

Your contribution in `externalContributors.json` must include:
- [ ] Type: Video, Blog, Social (please choose the appropriate one)
- [ ] Thumbnail: the path to your image, e.g., `/img/external-contributor/yourimage.png`
- [ ] Title: the title of your content
- [ ] Link: a direct link to your content
- [ ] Your name

Here’s an example of the JSON format to follow:

```json
[
    {
        "type": "blog",
        "thumbnail": "/img/external-contributor/yourimage.png",
        "title": "Exploring Web5",
        "link": "https://linktoyourcontent.com/web5-post",
        "contributor": "Your Name"
    }
]
```

Available `type` options:
- Video
- Blog
- Social

## 🌟 Resources
- [ ] [Our Blog on Key Management](https://developer.tbd.website/docs/web5/decentralized-identifiers/key-management/)
- [ ] [Our Blogs](https://developer.tbd.website/blog/)
- [ ] [Our YouTube channel](https://www.youtube.com/@tbd.videos)

## Getting Started
This content task is part of Hacktoberfest! We welcome contributions from creators of all skill levels. Here's how you can get started:

1. Read the [contribution guidelines](#)
2. Read the [code of conduct](#)
3. Choose a content-specific task from the list above
4. Comment ".take" on the corresponding issue to get assigned the task
5. Fork the repository and create a new branch for your work
6. Make your changes and submit a pull request
7. Wait for review and address any feedback

## Questions?
If you have any questions or need clarification, please comment on this issue or join our [Discord](https://discord.gg/tbd) community.

Happy coding! 🎉

**Comment by taniashiba** [comment]
Hello @KiranBaliga, thank you for your comment! As I mentioned in previous comments, we are officially assigning tasks for Hacktoberfest when it officially starts, which is tomorrow October 1st! Thank you so much for waiting in the meantime 🙏

**Comment by KiranBaliga** [comment]
.take

**Comment by blackgirlbytes** [comment]
Hey @KiranBaliga! Hacktoberfest is now live, so if you wanted to try assigning yourself to the issue again, please retry your comment, and you should get auto-assigned the issue. Also, I'd kindly ask that you finish one issue before you assign yourself a new issue. Thank you!

**Comment by KiranBaliga** [comment]
.take

**Comment by blackgirlbytes** [comment]
Hey @KiranBaliga I saw you assigned yourself to one issue already. We kindly ask that you finish an issue before you assign yourself to another issue. We want to give room for others to participate as well. Do you have a preference in one of the issues that you would like to get started on?

**Comment by KiranBaliga** [comment]
@blackgirlbytes I would like to work on this one first!

**Comment by EbonyLouis** [comment]
@KiranBaliga The steps to complete this ticket have been updated. Instead of opening an issue, you can now add your content directly to our repo. If you have any questions after reviewing the updated instructions, feel free to reach out.

I'm happy to help!

**Comment by KiranBaliga** [comment]
@EbonyLouis Please review the PR and action accordingly. Thank you!

**Comment by taniashiba** [comment]
Hi @KiranBaliga - In order to accept your submission, your blog post is meant to talk strictly within the context of and about Web5, not Web3. While we update our guidance for these tasks, would you please edit your post after you've reviewed DID Key Management from a Web5 context? Thank you so much! 🙏🖤

**Comment by KiranBaliga** [comment]
@taniashiba I have made the changes. Please review.
