### ISSUE TITLE
Update spacing in `tailwind.config.js`

### ISSUE THREAD

**Issue by tallneil** [TBD54566975/developer.tbd.website#1668]
I think there is a minor issue with spacing consistency. 
* in some places, Tailwind padding is used i.e. `p-4`. In other places, Twist padding is used i.e. `p-twist-core-spacing-12`. 
* Tailwind padding uses a 4px scale, and Twist padding uses a 3px scale. 

Twist spacers are defined in `tw-block.plugin.js`. Can these be used in `tailwind.config.js`? 
Tailwind docs: https://tailwindcss.com/docs/customizing-spacing

**Comment by TheVinaySagar** [comment]
Is this issue is open to contribute. I want to contribute. Can you please assign me this issue with hackotoberfest tag.

**Comment by blackgirlbytes** [comment]
hi @TheVinaySagar . This is not a hacktoberfest issue. You can check here for all our hacktoberfest issues: https://github.com/orgs/TBD54566975/projects/44

Hope his helps. Thank you!

**Comment by TheVinaySagar** [comment]
Thanks for reply, Please can you suggest me some issue because i am a beginner.

**Comment by blackgirlbytes** [comment]
Join our discord -- discord.gg/tbd so we can have a full conversation, but checkout the issues listed here. https://github.com/orgs/TBD54566975/projects/44?pane=issue&itemId=81763414&issue=TBD54566975%7Cdeveloper.tbd.website%7C1552

They are issues asking you to create blog posts about some of the technologies we're building at TBD.  @TheVinaySagar
