### ISSUE TITLE
Update purple theme in tailwind config

### ISSUE THREAD

**Issue by tallneil** [TBD54566975/developer.tbd.website#1782]
Design team has updated the purple color theme ramp: https://www.figma.com/design/vzQz0IgCT37UxdEbgn1nPw/%F0%9F%8C%95-tbd-web---reviews?node-id=5820-41017&t=af8j8cfpQwSssaSq-1

This addresses an issue where `purple-tint-2` was being used instead of `purple`, which led to unexpected colors being used in components.

**Comment by deauthe** [comment]
the link above seems to be invalid

**Comment by tallneil** [comment]
hi @deauthe, the Figma link is restricted to Block employees only

**Comment by deauthe** [comment]
:3
