### ISSUE TITLE
Create Your Own Blog About Decentralized Web Nodes (DWNs) (2)

### ISSUE THREAD

**Issue by blackgirlbytes** [TBD54566975/developer.tbd.website#1801]
# Create Your Own Blog About DWNs

## 🚀 Goal
Create your own blog post about DWNs on your website.

## 🤔 Background
This issue focuses specifically on spreading more awareness about decentralized web nodes (DWNs). Your contributions here will help you spread your knowledge across the web and to our community!

## 🤝 How You Can Contribute
Follow the steps below to contribute your content directly to our repository.

### **❗You must only assign yourself one task at a time to give everyone a chance to participate.❗**
You may assign yourself another task after your current one is reviewed and accepted.

- [ ] You must host your content on your own website or channel.
- [ ] Add your content information directly to the `site/src/externalContributors.json` file in the repository.
- [ ] Save your image in the `site/static/image/external-contributor/` directory, ensuring the image is in a **16:9 ratio**.
- [ ] Create a pull request with your changes for review.
- [ ] Link your submitted PR in a comment here to count towards Hacktoberfest.

Your contribution in `externalContributors.json` must include:
- [ ] Type: Video, Blog, Social (please choose the appropriate one)
- [ ] Thumbnail: the path to your image, e.g., `/img/external-contributor/yourimage.png`
- [ ] Title: the title of your content
- [ ] Link: a direct link to your content
- [ ] Your name

Here’s an example of the JSON format to follow:

```json
[
    {
        "type": "blog",
        "thumbnail": "/img/external-contributor/yourimage.png",
        "title": "Exploring Web5",
        "link": "https://linktoyourcontent.com/web5-post",
        "contributor": "Your Name"
    }
]
```

Available `type` options:
- Video
- Blog
- Social

## 🌟 Resources
- [What are DWNs](https://developer.tbd.website/docs/web5/decentralized-web-nodes/what-are-dwns)
- [Querying DWNs](https://developer.tbd.website/docs/web5/decentralized-web-nodes/query-from-dwn)
- [Writing to DWNs](https://developer.tbd.website/docs/web5/decentralized-web-nodes/write-to-dwn)
- [The Role of Protocols in DWNs](https://developer.tbd.website/docs/web5/decentralized-web-nodes/what-are-protocols)
- [Beyond Blockchain](https://developer.tbd.website/blog/decentralized-apps)
- [DWeb Deep Dive](https://www.youtube.com/watch?v=JVJVsm-93K8)
- [Google and DIF DWN](https://www.youtube.com/watch?v=M9c5CI3-4FM)
- [Super App built with Web5](https://www.youtube.com/watch?v=rKS77fqolM0)

## Getting Started
1. Comment ".take" on this issue to get assigned
2. Fork the repository and create a new branch for this task
3. Follow the tasks outlined above
4. Submit a pull request with your changes
5. Respond to any feedback during the review process

## Questions?
If you have any questions or need clarification, please comment on this issue or join our [Discord](https://discord.gg/tbd) community.

Happy coding! 🎉

**Comment by Lymah123** [comment]
> @Lymah123 if you wanted to assign yourself to this..I created this issue for you

Thank you @blackgirlbytes
