### ISSUE TITLE
Broken Example Links

### ISSUE THREAD

**Issue by nitro-neal** [TBD54566975/developer.tbd.website#265]
Example links here - https://developer.tbd.website/projects/ssi-sdk/readme/ - dont work - 

<img width="1519" alt="image" src="https://user-images.githubusercontent.com/5314059/181298002-1262a773-4725-455f-b05d-61f3bd1036d5.png">

https://developer.tbd.website/projects/ssi-sdk/example 
https://developer.tbd.website/projects/ssi-sdk/example/did
https://developer.tbd.website/projects/ssi-sdk/example/vc

**Comment by dayhaysoos** [comment]
I don't think these are on the site anymore
