### ISSUE TITLE
Bump docusaurus to stable 2.x release

### ISSUE THREAD

**Issue by mistermoe** [TBD54566975/developer.tbd.website#267]
[Stable Release Announcement](https://docusaurus.io/blog/2022/08/01/announcing-docusaurus-2.0#whats-new-in-20)

we're currently on [2.0.0-beta.18](https://github.com/TBD54566975/developer.tbd.website/blob/main/package.json#L20-L21). There will be a handful of breaking changes related to imports.

**Comment by ALRubinger** [comment]
Will be handled through tech debt payoff in #325
