### ISSUE TITLE
Add sidebar to Events page

### ISSUE THREAD

**Issue by angiejones** [TBD54566975/developer.tbd.website#276]
The Events page doesn't have a sidebar of events like Learn and Blog does. The structures are in place (e.g. event-sidebars.js), so need to figure out why it's not displaying.

**Comment by angiejones** [comment]
@dayhaysoos this is fixed, right?

**Comment by dayhaysoos** [comment]
@angiejones yes, but we're going to be revamping the Events page so it probably won't matter (unless you still want it there, we can talk about it). I think it's okay to close this in the mean time!
