### ISSUE TITLE
Fix metadata on Blog index

### ISSUE THREAD

**Issue by angiejones** [TBD54566975/developer.tbd.website#296]
On the [blog index page](https://developer.tbd.website/blog), the title of the page is 'What are Verifiable Credentials' (which is one of the individual blog posts). And when sharing the blog index page on social, it shows that same blog post and related image - which is incorrect

May have been introduced [here](https://github.com/TBD54566975/developer.tbd.website/pull/285#issuecomment-1270408170)

**Comment by EbonyLouis** [comment]
Fixed this [here](https://github.com/TBD54566975/developer.tbd.website/pull/701/commits/a9652cb9a6980d3ea57cd01ca89fbb8b457ecfca)
