### ISSUE TITLE
Add "Edit this Page" GitHub link to every doc

### ISSUE THREAD

**Issue by dayhaysoos** [TBD54566975/developer.tbd.website#301]

**Comment by danlourenco** [comment]
Hey @dayhaysoos , is this still an issue? I'm seeing the `<FeedbackWidget />` component present on every page under the Docs path, although it appears the link are broken.  Do you want me to take a stab at fixing the edit path in the Docusaurus config?

**Comment by dayhaysoos** [comment]
@danlourenco yes, actually, that'd be great! Lemme know if you have any questions. You can make a branch off of `main` for this

**Comment by Opssy** [comment]
@dayhaysoos  is this still an issue? I'd like to work on it

**Comment by Opssy** [comment]
okay, which of the branch should pull from

**Comment by dayhaysoos** [comment]
You can pull from main, but we have a convention for branching.

We name our branches with the issue number first, then the name would give a little context. So for this:

`issue-301/dynamic-edit-page` or something

**Comment by MoyosoreCodes** [comment]
@dayhaysoos has this been fixed, would like to work on it

**Comment by dayhaysoos** [comment]
closing as it was fixed.
