### ISSUE TITLE
Add minor touchups for Docs

### ISSUE THREAD

**Issue by angiejones** [TBD54566975/developer.tbd.website#319]
- lowercase tutorial directory
- add What is Web 5 resource to Getting Started page
- add ChatApp example link
- fix meta tags on moved tutorial

**Comment by dayhaysoos** [comment]
Hey Angie,

I've got the fixes you asked for on this PR:

https://github.com/TBD54566975/developer.tbd.website/pull/320

The only thing missing is the ChatApp example, do you have the URL for that or is that something that's a work in progress?

**Comment by nearlyjuly** [comment]
On the tutorial for manually issuing a verifiable credential the link to the jwt.io website goes to https://developer.tbd.website/docs/tutorials/jwt.io
