### ISSUE TITLE
[PROPOSAL] Refresh developer.tbd.website copy and structure

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/developer.tbd.website#326]
_Proposal issue for continued discussion and input before action. Current state: this is a first cut at encoding goals to design for._ 

# Refresh of developer.tbd.website

## Goal
Clarify the purpose of developer.tbd.website, and adapt the site contents and structure in service of that purpose.

We should be able to give Web5 Builders and Contributors a link to developer.tbd.website with no other info; and they have everything they need to quickly orient themselves and access their desired path (one of "Site Purpose", below).

## Gaps
The current site was born before Web5 was named and project readiness enabled folks to build Web5 applications. As we prepare to offer the community more tangible calls to action, the site must serve as a stronger single access point bringing together all open source programs, projects, documentation, and educational materials.

## Target Audience
As the name infers: _Developers_. Both:
* Web5 Application Builders
* Contributors to the Web5 Platform

## Site Purpose

Give developers everything they need to:
* Build Web5 Applications
  * "Get people from zero to a Web5 project in no time" - Nick 
* Contribute to the Web5 Platform and its projects
* Learn the concepts behind our approach and why they're important
  * Decentralization
  * Data self-sovereignty
  * Open source 
  * Technical concepts and their relevance
      * ie. DIDs, VCs,  
* Get connected with the community
* Understand tbDEX
    * Its importance in on- and off-ramps to digital money
    * How Web5 underpins tbDEX as an application

## Overall Principles
* Brand voice: bring more of the funky/fun vibe

## Home Page
* Most important things the Home Page should focus on (unordered in priority):
  * Hero headline 
  * Get Started
    * Create a new Web5 Application
    * Add Web5 to your web application  
  * Orient to Concepts
    * Decentralization
    * Data Self-Soverignty
  * Orient to Projects
    * Web5
    * tbDEX 
* "We’re building the next generation of the decentralized web – returning data back to users. You’re welcome to join."
  * Let's reframe this around the desired action: promoting Web5 as a decentralized application platform with self-sovereign identity, and inviting people to make applications on it. All that will take some care in copyediting :)

### Small Wins
* "Double-click" > say something else to mean "Learn more"; this is literally a single-click button - ALR
* Our Philosophy > "Our Open Philosophy", copy revisions to illustrate why this must be a public good and how it enables others to build value. - ALR

**Comment by ALRubinger** [comment]
@angiejones - We started an assessment of some things we could change to make the developer site more effective, and that led to a higher-level discussion about the site's purpose, who it serves, its relationship with tbd.website, and more. We captured some of those early thoughts to guide the discussions to come - and nothing on this moves until we've got you in the conversation and everyone's aligned.

@dayhaysoos @bobbilee19 My notes from our session earlier are in this issue description. Please offer corrections it it doesn't adequately capture the sentiments of the room. As above note w/ Angie, let's all move together on this.

**Comment by ALRubinger** [comment]
Trusted external feedback: "It's not clear what a Web5 app is".

I agree. Let's make certain we have clear, consistent narrative around decentralization and SSI principles and the WHYs:

* Why they matter
* Why doing them on your own is difficult
* Why Web5 as a Platform does the heavy lifting and gives you an easy app programming model to take advantage of private data, messaging, SSI - so you can focus on your app.

**Comment by taniashiba** [comment]
Proposal / Feedback @ALRubinger - Couldn't make a separate proposal, so a comment it is! 💯 

Establish Guiding Principles to overlay all work we do so the entire team can clearly look at every page on the site or within documentation through the lens of "Does this dead end?"

A habit to build to ensure a page does not dead-end a member / would-be-member's journey. Instead, continuing or adding to their current journey.

You can find common paths members take, build member habit to ask questions at x point in a given page, etc.

**Comment by ALRubinger** [comment]
Outdated
