### ISSUE TITLE
Create Inventory of Use Cases to cover in Documentation

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/developer.tbd.website#339]
Umbrella issue to capture ideas and community input for now. When we have the [info architecture set for documentation types](https://github.com/orgs/TBD54566975/projects/10/views/4?pane=issue&itemId=21193823), we can map these ideas into more actionable pieces (ie. a Tutorial for X, a Sample Application for Y).

Open to community input about what you'd like to learn!

**Comment by nearlyjuly** [comment]
Is it possible for more elements of web5 to be incorporated into the developer site, such as having a PWA/DWA (maybe for some of the tutorials or guides) and so on? I can see that issuing VCs is on the linked image there, so will the web wallet be incorporated too? The reason I ask, I've just been playing around seeing how much I can put into just an html page with js and I can retrieve DID document info and create/send messages to my locally hosted dwn. So it just makes me wonder what ways you're (tbd people) already using or playing around with things and can it be used as work goes along on the website?

**Comment by nearlyjuly** [comment]
For DIDs, it could be better to start with something like an in page resolve like this https://pastebin.com/vry2wi7H where someone can straight away see what the DID is and what the document shows. Then working through some of the entries (e.g. using it to verify a message) and then finally how to create one with SSI and/or a wallet.

**Comment by ALRubinger** [comment]
We're thinking:  Now that there is a use cases page, that's the inventory. :)

@bobbilee19 to link to where this page is (if it exists), and we can close from there if it's taken care of. Leaving this issue for now until we make sure it's reflected.

**Comment by ALRubinger** [comment]
@bobbilee19 ^ Status? Let's do one of:

1) Document how this is satisfied so we can close the issue
2) Unschedule from Phase 2 and handle later

**Comment by ALRubinger** [comment]
Bumping to Phase 3. Not Blocking Phase 2 release.

**Comment by bobbilee19** [comment]
@ALRubinger maybe this is something we work on with @EbonyLouis?

How to bring in use cases based on what we're seeing in the community being built or asked for AND surfacing use cases and examples that we come up with.

We also deleted the Use Case / Case Study page from the docs and we're just listing some here on the[ main opening page for web5](https://developer.tbd.website/docs/web5/)? is that the only place we have use cases highlighted?

**Comment by ALRubinger** [comment]
@bobbilee19 Yes, it is. And also something I think is firmly within the remit of DevRel to design an inventory of use cases the team feels should be addressed. That inventory will likely be informed with input of stakeholders like @EbonyLouis who has a great pulse on needs from the community, and OSE as they advise their readiness on what's coming available.

I do think an inventory of work items may live separately from the published materials on developer.tbd.website, though would be fantastic to surface in one place we can all see in public.

Do you have ideas for what mechanism you'd like to track these? A label for use cases as part of docs inventory in GitHub Issues on the dev site? Something else? Happy to stand up whatever public facing system for this works well for the team to organize things in a contributor-friendly way and keep you moving.

**Comment by EbonyLouis** [comment]
Yess, this goes along with my brainstorming event ticket that I have in Asana. I've put it off for July/August, to get Chris' event in. But essentially the community also would love to know what's possible and get a list of use cases. So this event will start with a shared brainstorming doc, where everyone will write their ideas down and then during the event elaborate on use cases/ add more. It then will live in an "idea-board" channel where we'll always have a running wishlist of web5/ssi apps, to constantly have a flow of ideas to choose from. 

This list could also live on the website.

**Comment by ALRubinger** [comment]
Outdated
