### ISSUE TITLE
Fix border styling to match the original site

### ISSUE THREAD

**Issue by dayhaysoos** [TBD54566975/developer.tbd.website#341]
The tooltip on the old side had a different style for the border when showing tool-tip content. Here is what it looked like before:

![Image](https://user-images.githubusercontent.com/1852675/223547694-82b6aca4-5b5b-4bdb-9e99-8a1815517ff9.png)

Here is what it looks like after paying off the tech debt:

![Image](https://user-images.githubusercontent.com/1852675/223547824-a2b90ea4-488b-41b7-8c55-46378e096ff6.png)

**Comment by ALRubinger** [comment]
2ced7eb5352336d4f505b90bc18506cc8f59f3c3
