### ISSUE TITLE
Purple, blue and yellow border image doesn't show on initial render

### ISSUE THREAD

**Issue by dayhaysoos** [TBD54566975/developer.tbd.website#342]
On first page load, the border is missing. Switching pages makes it show up again. Need it to show all the time.

**Comment by ALRubinger** [comment]
(in the footer):

![Image](https://user-images.githubusercontent.com/199891/227055989-633f3549-236f-4117-8df0-16063c8a2d9c.png)

**Comment by ALRubinger** [comment]
Descoping from Phase 2
