### ISSUE TITLE
Address inability to scroll to top one page change without janky solution

### ISSUE THREAD

**Issue by dayhaysoos** [TBD54566975/developer.tbd.website#343]
## Context

When navigating to other pages on the docs site, the site wouldn't scroll to the top on page load. This should be working by default without any weird solution. However, this was addressed by making a scrollToTop component in Docusaurus' `<Layout />` component.

The commit where this solution was put into place is here: https://github.com/TBD54566975/developer.tbd.website/pull/328/commits/8432f9acc2fbff6461eb6fd5837d02421bef1ae3

**Note**

If you remove this code, you'll notice it stops scrolling to the top on page load. To take things even further, by running `window.scrollTo(0,0)` inside dev tools, you'll notice it doesn't scroll to the top even though you are explicitly running a function that would do that on any website.

Not sure what this could mean, but documenting this just in case we come across any weird, related DOM issues.

**Comment by ALRubinger** [comment]
@dayhaysoos I think this was solved as part of #328, no?

**Comment by dayhaysoos** [comment]
Closing bc Kirah fixed this (ty kirah)
