### ISSUE TITLE
Glossary Page

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/developer.tbd.website#344]
To be reviewed w/ @bobbilee19 for validity before slating for work.

Kirah to provide a list (with input from OSE) of Concepts/Terms to know
Once that is complete, DevRel and OSE work together to complete and validate the content.

Aim for approval on this page by EOW Friday March 10. List of concepts/terms by EOW Friday 17 March.

**Comment by bobbilee19** [comment]
Here is the file for it, https://github.com/TBD54566975/docs-sitemap/blob/main/term-glossary.md, but soon I'll have a HackMD file to collaborate ideas listed here in the [READMe](https://github.com/TBD54566975/docs-sitemap/blob/main/README.md)

**Comment by bobbilee19** [comment]
Here is the HackMD file @kirahsapong https://hackmd.io/Y-EgFK51RH2oon3dpEPbIA
