### ISSUE TITLE
Docs Framework Analysis

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/developer.tbd.website#345]
For the "Docs" dection of the developer site, determine if an existing framework is best-suited as the base upon which to surface documentation.

Requirements:
* Authored in Markdown - our standard for docs 

Components to this analysis:
* Design and L&F components
* Process from authoring to publishing
* Maintenance and quality assurance

Agreed from coworking session: 
* If we were designing a docs-only site, the first place both @bobbilee19 and @dayhaysoos would start for a deep dive is GitBook
* So let's start there!
* 1) Stand up a GitBook instance for us to explore and play with features available to us
* 2) Investigate the technical implementation challenge of Docusaurus (the developer site) and GitBook being able to be surfaced to folks as one cohesive site. Is this: embed GitBook into the existing site? Run it as a standalone site, but unify it all under one domain`developer.tbd.website/docs` using Netlify redirects or other mechanisms?

Let's collaborate on this issue here @dayhaysoos and @bobbilee19 until we may break off individual tasks which stem from this work. @dayhaysoos, we may find it useful to carve off 1) and 2) from above as separate issues we can move forward, so go ahead!

This is slated as a stretch goal for Phase 2. It's important enough that it can't get dropped, but may move to final delivery in Phase 3 depending upon rate of progress.

**Comment by ALRubinger** [comment]
Considerations raised in discussion:

- Link checking - ensures no broken links. Done by platform or done through adding checks?
- Authoring environment as part of framework? Or link to contribute/edit this page on Git per typical contribution model?
- Extensibility - will the framework allow us to innovate on top with custom components, or will it be to opinionated/constrained to its model? 

Frameworks we've identified to inspect:

- [[GitBook](https://www.gitbook.com/)](https://www.gitbook.com/)
- [[Markdoc](https://markdoc.dev/)](https://markdoc.dev/)
- [[VitePress](https://vitepress.vuejs.org/)](https://vitepress.vuejs.org/)
- [[ReplIt](https://replit.com/)](https://replit.com/)

**Comment by ALRubinger** [comment]
I found this one today which looks super configurable, and available for our own hosting (unlike GitBook):

* [Retype](https://retype.com/)

@bobbilee19, have you put together a featureset you're looking for as requirements? That'll help w/ framework selection if GitBook ends up being an unfit integration w/ the developer site.

**Comment by dayhaysoos** [comment]
We decided we're going to focus on improving the current docusaurus site. Over the next 2 weeks I'll be working closely with @bobbilee19 on making sure the look meets her expectations and all parties are satisfied. 

Going to be making issues to document what this work will look like.

**Comment by ALRubinger** [comment]
Sounds great! Moving to Done 🤘🏻

**Comment by ALRubinger** [comment]
Conclusion in https://github.com/TBD54566975/developer.tbd.website/issues/348#issuecomment-1476949935
