### ISSUE TITLE
Blog has 'Edit this page' with 404 link

### ISSUE THREAD

**Issue by angiejones** [TBD54566975/developer.tbd.website#351]
All blog posts now have an 'Edit this page' link at the bottom of the page that leads to https://github.com/facebook/docusaurus/tree/main/packages/create-docusaurus/templates/shared/blog/2023-01-10-ssi-chat-gpt.md which gives a 404.

The 'Edit this page' label and link should be removed.

**Comment by dayhaysoos** [comment]
Noted - Going to look into this soon
