### ISSUE TITLE
Docs index page rework

### ISSUE THREAD

**Issue by dayhaysoos** [TBD54566975/developer.tbd.website#353]
Based on the conclusion of #348, we're looking to have a more customized index page for the`/docs`. To do this, we decided we'll be relying on a regular React component for that page, instead of Markdown.

Biggest inspiration is Expo docs:

https://docs.expo.dev/

Unfortunately, Docusaurus doesn't allow for the index page to be anything other than a Markdown file. To work around this, I'll be making a React component to be the pages content and importing it in the index markdown file to have the desired look and feel.

**Comment by angiejones** [comment]
is this still relevant or can we close?

**Comment by finn-tbd** [comment]
outdated
