### ISSUE TITLE
Add Content Type Support: Sandboxes/Playground

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/developer.tbd.website#354]
Define and support a new content type: sandbox/playground for Web5 Applications. 

Define process, where these live, and welcome them into the documentation suite w/ support/maintenance plan.

**Comment by ALRubinger** [comment]
* [Web5OMG](https://web5omg.com/) from @michaelneale 
* SSI Console from @kirahsapong 
* DID/ION Resolving Stuff from @decentralgabe 
* [Verifiable Credentials Display Widget](https://tbd54566975.github.io/web5-components/demo/VerifiableCredential/) from @dcrousso

**Comment by michaelneale** [comment]
I still like the idea of sandboxes in general - some of those ones may be out of date, but any way to let people play in the browser is a huge leap ahead.

**Comment by angiejones** [comment]
> I still like the idea of sandboxes in general - some of those ones may be out of date, but any way to let people play in the browser is a huge leap ahead.

definitely agree

**Comment by ALRubinger** [comment]
Same agreement. Should be in a unified repo where we can sanely manage maintenance, and give each a deployment on Netlify to show live.

**Comment by michaelneale** [comment]
I am a fan of codesandbox.io as well - but I am sure there are others. I tend to demo things there (and lets people fork/play).

**Comment by ALRubinger** [comment]
Yes @michaelneale -- a  provider for these would be great too, especially if we can find one which serves the needs of the various sandbox environments. A small survey should find us the differences between a few:

* codesandbox.io
* replit.com
* jsfiddle
* Codepen
* ...more

**Comment by michaelneale** [comment]
I agree @dayhaysoos - I use codesandbox most days and it is fine, easy to share, quick, and quite nice for js heavy things (gitpod is great for more backend-ey things).

**Comment by dayhaysoos** [comment]
Do we have a Block Codesandbox account? Is this something that we need to procure?

**Comment by michaelneale** [comment]
they are free for end users to use - especially when repo is open source, so not sure if one is needed.
