### ISSUE TITLE
Restore Web5 Project page and refactor Web5 Docs page

### ISSUE THREAD

**Issue by angiejones** [TBD54566975/developer.tbd.website#374]
The Web5 project page was refactored so that it could be reused as the Web5 docs page

These pages have different purposes and CTAs so should not be mirrored.

**Comment by ALRubinger** [comment]
Status on this, and linked commits if any?

**Comment by ALRubinger** [comment]
Moving to Phase 3, can't find context on work in progress or specifically what should be done.
