### ISSUE TITLE
Review Web5 Quickstart for added Interactive Stuff

### ISSUE THREAD

**Issue by dayhaysoos** [TBD54566975/developer.tbd.website#375]
The Web5 Quickstart page is almost ready and it would be great to get some feedback on the page.

Would like feedback on the following:

- The content itself, how can it improve?
- Style & Layout
- Any bugs?

TODO:

Need to merge the quickstart branch to get deploy

**Comment by ALRubinger** [comment]
This is now in the `phase-2` branch, a series of commits from me, @mistermoe, @dayhaysoos. Verified working and thus closing this - Interactive components are now in the Quickstart (w00t!)
