### ISSUE TITLE
DOCS: Define internal dev generation/collaboration process

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/developer.tbd.website#380]
* Write up workflow for surfacing Sample Apps / Examples / Sandbox applications and code to publishing and long-term maintenance w/ DevRel and Programs
* Automation?
* Is this a different process for content type?
* Does each content type end up in a new repo? For instance: `tbd-sample-apps`, `tbd-sandboxes`?
* How does publishing these relate to the documentation templates describing them?
* Can we align all these into repos that have a dependency on one version of Web5, therefore allowing us to version all the examples/samples/tutorials together and using the same version of Web5?

Probably is made more clear by nature of picking something like Yeeter or the [VC Sandbox](https://tbd54566975.github.io/web5-components/demo/VerifiableCredential/) and working through how it's documented and potentially found a new home. Right now all these excellent apps are scattered throughout the `TBD54566975` org.

**Comment by ALRubinger** [comment]
100% agree; there's been great discussions in larger and smaller groups on this. I see it as a handoff of materials seeded from OSE principally, with DevRel and Programs then tasked with making it happen. @bobbilee19 are you still looking to run point on converging these ideas into something we can write down in Markdown and put into developing norms? Or should another DRI take this on to synthesize the feedback points and propose a workflow?

**Comment by finn-tbd** [comment]
outdated
