### ISSUE TITLE
Add new images to learn DIDs file

### ISSUE THREAD

**Issue by bobbilee19** [TBD54566975/developer.tbd.website#382]

**Comment by ALRubinger** [comment]
Looking at deploy preview, these are done now, @dayhaysoos?

https://deploy-preview-365--tbd-website-developer.netlify.app/docs/web5/learn/decentralized-identifiers

![Image](https://user-images.githubusercontent.com/199891/232152610-d3431d82-49ef-439b-abe5-704c11a3dd5e.png)

If so, close?

**Comment by ALRubinger** [comment]
I think this is done based on latest deploy branch, so closing. @bobbilee19 and @dayhaysoos please re-open for Phase 3 if this isn't the case.
