### ISSUE TITLE
Redirect needed for Web5 PDF

### ISSUE THREAD

**Issue by angiejones** [TBD54566975/developer.tbd.website#386]
Old link https://developer.tbd.website/docs/Decentralized%20Web%20Platform%20-%20Public.pdf 
Needs to be redirected to https://developer.tbd.website/files/Decentralized-Web-Platform.pdf

**Comment by ALRubinger** [comment]
Is this a link referenced somewhere outside of the developer site, and we need a `netlify.toml` config to redirect this?

**Comment by ALRubinger** [comment]
Moving to Phase 3

**Comment by angiejones** [comment]
> @angiejones Is this a link referenced somewhere outside of the developer site, and we need a `netlify.toml` config to redirect this?

Page: https://developer.tbd.website/projects/web5

![image](https://user-images.githubusercontent.com/15972783/235510836-1dcbc9e4-3d28-41cc-a8cb-0727c9e6e9a5.png)

**Comment by angiejones** [comment]
it was referenced in some media sites and social media. this was found by Comms

**Comment by angiejones** [comment]
we've removed this button, however still adding the redirect since the link was shared externally

https://github.com/TBD54566975/developer.tbd.website/pull/514
