### ISSUE TITLE
Define PR and Push Strategy

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/developer.tbd.website#388]
We're ready for some more clear guidelines about who is pushing to `main` and therefore triggering production deploys. Looking to balance:

* Light process so simple fixes are not held up
* Content review so the accountable parties for their sections are the ones approving final PRs
* Technical review so those responsible for site infra are the ones approving those PRs

In other words, let's write up how we fulfill our TBD guiding principles of "align decision making with accountability".

This issue is a great place to discuss how we're thinking about DRIs for different aspects of the site. Then let's elect who should be reviewing / approving PRs. In the cases where it's a larger change that impacts site structure or TBD / Open Source Program messaging, let's coordinate on those together w/ reviews.

Delivery of this issue: writing up in `COLLABORATION.md` the PR guidelines for who approves what. Let's not have each of us with write access simply self-approving anything we do. :)

**Comment by ALRubinger** [comment]
Aiming not for a heavy process, but for DRI-ship of who approves what kinds of things.

For instance:
* @dayhaysoos  for infra and tech things?
* @bobbilee19  or @chris-tbd  for docs content pages?
* me for site-wide messaging and project pages?
* @angiejones  for media and non-docs learn assets?
* Ebony on to-be-made Community Building content sections?

I don't have a perspective yet on the particulars, but I'd like to hear folks' thoughts on the issue. Then we can write it up and I think the whole exercise will be a great forcing function to give folks autonomy and alignment in one go.

**Comment by ALRubinger** [comment]
From @angiejones in Discord:

> add me as an alternate reviewer to doc content too. that'll give folks 3 options to hopefully get their PR merged quickly
every section should have back ups actually

**Comment by finn-tbd** [comment]
This is outdated and has long been figured out.
