### ISSUE TITLE
Audit Developer Site now that we have doc pages

### ISSUE THREAD

**Issue by bobbilee19** [TBD54566975/developer.tbd.website#390]
We have pages that are repeated and now that folks are on the developer docs we shouldn't need intro to product pages, for example: https://developer.tbd.website/projects/web5 should be removed maybe because we have a web5 intro page embedded within docs...I'm not saying remove all content, use pieces from it in the new page?

**Comment by ALRubinger** [comment]
Great idea; let's consider this audit as a starting point for the grander questions raised in #326 .

**Comment by dayhaysoos** [comment]
Closing just to clean up some of our issues. The website is very different now than it was at the time of this issue being opened.
