### ISSUE TITLE
Add page: "Forums Retired"

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/developer.tbd.website#391]
This will be a redirect for `forums.tbd.website`, as we are retiring our Discourse-hosted forums.

Explain that these are no longer running, and point folks to where they can get involved so they're no dead-ended (principally, GitHub and Discord).

**Comment by ALRubinger** [comment]
Assigning to me and @EbonyLouis to jam on ideas for what this page should contain; Ebony - got hot takes for pointers to where folks should be offered to go instead? Contributing page?

LEt's lock in on this and I'll draw up the copy. Even better if you have design/graphics ideas for this page.

**Comment by finn-tbd** [comment]
Outdated, closing
