### ISSUE TITLE
Update Web5 Quickstart w/ simplified did.create API call

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/developer.tbd.website#395]
Dependency on this being available in `web5-js`: 

* https://github.com/TBD54566975/web5-js/issues/31

**Comment by dayhaysoos** [comment]
I think this is going to get taken care of by @bobbilee19 in #398 and #409. @bobbilee19 

Please refer to #398 for updates that relate to this issue

**Comment by ALRubinger** [comment]
Pulling off phase 4 due to dependency

**Comment by dayhaysoos** [comment]
Actually, I think we can close this as it was done in Phase 3 @ALRubinger
