### ISSUE TITLE
Anchor links in docs don't scroll to anchor on new page

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/developer.tbd.website#396]
For instance:

https://deploy-preview-365--tbd-website-developer.netlify.app/docs/glossary#did-method---ion

Opening this as a new page does not scroll to the appropriate anchor on the page; it opens the page at the top.

**Comment by dayhaysoos** [comment]
Do you think this should be included in this Phase 4 sprint? This is something that I feel should be addressed before BTC Miami

**Comment by ALRubinger** [comment]
@dayhaysoos Yes, slated it for Phase 4 - all usability and bug fix tasks can be incrementally added by DRIs into a Phase. Up to you to balance these w/ the goals/priorities of the Phase.

**Comment by angiejones** [comment]
pretty important for the API docs

**Comment by ALRubinger** [comment]
Including as part of @kirahsapong design pass in #439

**Comment by ALRubinger** [comment]
@kirahsapong Do you have an update on status of this?

**Comment by ALRubinger** [comment]
Decoping Phase 4

**Comment by ALRubinger** [comment]
These are also broken, for instance:

https://developer.tbd.website/docs/glossary/#self-sovereign-identity-ssi

I can get here directly by copy/paste, but not if I make a button on the site link to it with the anchor in the URL.

@dayhaysoos can we raise priority of this and get it sorted?

**Comment by angiejones** [comment]
this is now working
