### ISSUE TITLE
Create Template Application from PWA model

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/developer.tbd.website#408]
From my understanding w/ @csuwildcat: we can follow a model similar to:

https://github.com/pwa-builder/pwa-starter

The current [Quickstart](https://developer.tbd.website/docs/web5/quickstart/) assumes the user has an existing project to work from. Let's also provide a path, aside from the Quickstart, which sets them up with a template which:

* Alleviates the conceptual load of having to kick off a new project
* Cuts the amount of instruction we have to do to help them set one up
* Cuts the time involved in setting up boilerplate
* Orients all new developers to a known, same starting point we can use to instruct them to "Web5 enable it" and set them up for making their own apps

**Comment by angiejones** [comment]
@leordev is this the stuff you're working on? if so, feel free to assign this one to yourself

**Comment by leordev** [comment]
No I'm not working on that at the moment. But let me add this to @ALRubinger and @dayhaysoos for prioritization.
