### ISSUE TITLE
Upgrade Docs to new Web5 Release

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/developer.tbd.website#409]
Dependencies: 
* https://github.com/TBD54566975/web5-js/issues/42
* https://github.com/TBD54566975/web5-quickstart-widgets/issues/2

Update docs:
* Quickstart should use new web5 dependency in `package.json` 
* In NPM installation instructions for Quickstart (ie. `npm install @tbd54566975/web5@0.4.0`
* In CDN import instructions in Quickstart (ie. `import { Web5 } from 'https://cdn.jsdelivr.net/npm/@tbd54566975/web5@0.4.0/dist/browser.mjs';`)
* Quickstart code snippits may have changed due to breaking API changes. Reconcile with the above dependency (https://github.com/TBD54566975/web5-quickstart-widgets/issues/2) to ensure that any code that changed as part of this new release is reflected in the docs.
* Other sections that are running on older versions - for instance "Build" docs, "Learn" docs, TODO app, etc

If we can externalize the version number used in the process to a single place to update versions for Web5; even better. Ideally we'd update the version in one place and it'd be used in the build and all places we reference it in the docs. If that can't be done along this, please make a new issue for externalizing the version number so we can handle later.

**Comment by ALRubinger** [comment]
@dayhaysoos @bobbilee19 New Web5 version is out - `0.6.0`. Ping me if you need guidance updating.

**Comment by dayhaysoos** [comment]
This is going to get addressed in #398

**Comment by ALRubinger** [comment]
In `main` alongside #398
