### ISSUE TITLE
Revamp API Docs for Web5

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/developer.tbd.website#436]
We currently have API docs in two locations:

* Autogen: https://tbd54566975.github.io/dwn-sdk-js/
  * History behind this and a comment thread is [here](https://github.com/TBD54566975/web5-js/issues/34) 
* NPM, hand-written: https://www.npmjs.com/package/@tbd54566975/web5

There's an alignment exercise to do to meet a quality bar desired by @csuwildcat and @angiejones. @csuwildcat can give more guidance if needed. @csuwildcat would like to review the approach and @angiejones will check +1 delivery.

Requirements: 
* This is versioned alongside Web5 (may or may not be in `web5-js` repo, but built in a way it may be updated and tagged alongside Web5 so docs are versioned) - @ALRubinger 
* Meets quality bar by examples:
  * Index: https://developer.mozilla.org/en-US/docs/Web/API
  * Content: https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API 

Dependency for final content:
* https://github.com/TBD54566975/web5-js/issues/56

Note that most aspects of this may and should be parallelized ahead of the dependent Web5 release.

* DRI DevRel and overall: @chris-tbd (for content, (w/ support @dayhaysoos and @bobbilee19)
* Support OSE: @csuwildcat 
* Support Programs: @dayhaysoos (for branching strategy and new page on site)
* Support Styling: @kirahsapong (available?)
* Acceptance: @angiejones

**Comment by michaelneale** [comment]
do we want to keep the DWN docs - they pre-date the web5js which I think is the api we want public? (that should simplify things).

**Comment by ALRubinger** [comment]
@michaelneale It's a great point I'll leave to @csuwildcat to make the call.

My opinion: DWN *is* a standalone library and some folks may wish to use it outside Web5, particularly contributors; if it has use to them we should make its API Docs available, provided they're 1) Useful 2) Up to date

**Comment by csuwildcat** [comment]
I'd categorize the DWN SDK as a very low level, decomposed toolkit that definitely yields a DWN, but is verbose enough that I would not spend time on its docs to expose them (beyond auto-generated ones), at least for this release.

**Comment by ALRubinger** [comment]
@csuwildcat So for DWN API, no action needed? We're currently pointing to autogen: https://tbd54566975.github.io/dwn-sdk-js/

And it's linked from here: https://developer.tbd.website/docs/api/

<img width="346" alt="image" src="https://user-images.githubusercontent.com/199891/236010869-f4f11ab1-851e-4bc9-96c3-fbd62bd6f07c.png">

**Comment by chris-tbd** [comment]
Outstanding questions from me:
- Should this page live on TBD Dev site? How important is this?
- Do we need to make the other API docs align with the styling and location?
- Are we okay with auto-generating docs and adding comments into code, or do we need to keep this API documentation separate?
- Who is has the "source of truth" for what should be covered in these docs? Obviously the code is our source of truth, but who is the person who will be our final check on what makes it in?

**Comment by ALRubinger** [comment]
> * Should this page live on TBD Dev site? How important is this?

No on-site requirement from me, but featured prominently (as it is currently) and linked off. @angiejones?

> * Do we need to make the other API docs align with the styling and location?

Nope. The others aren't aligned, and sometimes there's good reason for that; for instance Go has its own publishing location and styling that's most familiar to Go devs.

> * Are we okay with auto-generating docs and adding comments into code, or do we need to keep this API documentation separate?

@csuwildcat and @angiejones confirm - not autogen?

> * Who is has the "source of truth" for what should be covered in these docs? Obviously the code is our source of truth, but who is the person who will be our final check on what makes it in?

@csuwildcat for tech correctness, @angiejones for final +1.

**Comment by angiejones** [comment]
- I'd prefer the API docs live on TBD Dev site but if there's a good reason not to do that, I can be convinced to host them elsewhere
- These API docs do not need to align with the others
- As for autogenerate, it depends. The developers are adding type definitions so it's possible to autogenerate from there and manually enhance. Let me know your preference

**Comment by ALRubinger** [comment]
Descoping off Phase 4 - can be fast follow before Saturday per @csuwildcat @chris-tbd
