### ISSUE TITLE
Create link to dwn-server README: How to Start and Run a DWN Server

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/developer.tbd.website#437]
Dependencies: 

* https://github.com/TBD54566975/dwn-server/issues/16
* https://github.com/TBD54566975/dwn-server/issues/19

Add a link in the Docs section to the `dwn-server` guide for how to run. Make it kinda cool and promient; showing the value add to devs by doing this, maybe like "Run Your DWN Server" or "Connect to a hosted DWN Server" (we'll be standing those up). The CTA text can be determined by the DRIs of this; will be dependent on the instructions in the above dependency what's possible.

* DRI Programs for getting the link on the dev site: @dayhaysoos, @bobbilee19 can likely advise where from info arch perspective
* Support OSE: @michaelneale @mistermoe 
* Support design on link card/button/etc: @kirahsapong 

Surface as a card here:

![Image](https://github.com/TBD54566975/developer.tbd.website/assets/199891/73725e60-6bba-418e-8ab3-83e5475c2594)

**Comment by michaelneale** [comment]
Clarifications: Sync should be automatic (I think?). Also we will have some already-running DWN servers that can be used (this is for people that want their own).

**Comment by ALRubinger** [comment]
@michaelneale Awesome; admittedly I haven't seen how this works yet so counting on OSE to feed enough info to @chris-tbd as DRI to get this written up for anyone to take advantage.

**Comment by ALRubinger** [comment]
Will update this ticket:

* No longer a docs set on the Dev Site - instead is a link to `dwn-server` from Dev Site
* Will point to a tagged version of the `dwn-server` README from the Dev Site
* These docs still in flux will live in the `dwn-server` README

DRIs: @michaelneale @mistermoe 
Programs support for link: @dayhaysoos

**Comment by ALRubinger** [comment]
ALR to follow up with issue description edits

**Comment by chris-tbd** [comment]
@ALRubinger do you want me CC'd on this for any review?

**Comment by ALRubinger** [comment]
@chris-tbd DevRel review of OSE's `README` would be amazing and I'm sure they'd appreciate it! Yes will update issue description and include that; thank you!

**Comment by ALRubinger** [comment]
Updated ticket description to reflect that this has been descoped from a full guide on the Dev Site and is now centered in the `README` of the `dwn-server` repo; job on the Dev Site is to make a prominent link / card for it to that `README` for now. Can become a guide later when the project is more stable.

**Comment by michaelneale** [comment]
we will also have some guides (or be able to have some guides) on how to run in various environments (cloudy ones- although end users may be more interested in umbrel like stories)

**Comment by chris-tbd** [comment]
@ALRubinger or @michaelneale could you drop a link in here of OSE's `README`?

**Comment by ALRubinger** [comment]
> @ALRubinger or @michaelneale could you drop a link in here of OSE's `README`?

https://github.com/TBD54566975/dwn-server/blob/main/README.md

**Comment by ALRubinger** [comment]
This is done in `phase-4`: 0a005639bc0693b874386a7c7a65c80e582db827
