### ISSUE TITLE
Blog Post and Link to Starter Template: DWAs and Starter App

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/developer.tbd.website#438]
Perhaps Dependency?

* https://github.com/TBD54566975/dwa-starter/issues/7

Note: the dependency above is necessary to close this ticket, but not to start. @dcrousso has made lots of progress already in `main` of https://github.com/TBD54566975/dwa-starter.

Update: @csuwildcat may be making a template for DWAs based on his music app. TBD if this is done in time.

Deliverable: A Guide/Tutorial for the "why" and "how" of creating DWAs. The repo itself is already built to be fairly self-explanatory; it walks a user through a wizard.

DRI: @dayhaysoos 
Support OSE:  @csuwildcat 
Content +1: @angiejones

**Comment by dayhaysoos** [comment]
@chris-tbd to add notes and context

**Comment by chris-tbd** [comment]
Spoke with @angiejones about this, we're going to re-do this item as a blog post to explain DWAs, how you'd map a PWA to a DWA, and and where to get started. I'll follow this up after BTC Miami with an existing Asana item for a guide on DWAs. @ALRubinger Would you prefer to repurpose this item for that, or create a new item?

**Comment by ALRubinger** [comment]
Sounds great @chris-tbd - real nice descoping.

Repurpose away - issue is yours to evolve. If we make a more formal guide later we can create a new issue for that.

**Comment by ALRubinger** [comment]
@chris-tbd Descoping from Phase 4 but can go in whenever you're ready to `main`
