### ISSUE TITLE
Create Contributor landing page

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/developer.tbd.website#440]
Software dependencies: none.

@EbonyLouis top flesh out requirements for this page

Will require `CONTRIBUTING.md` be updated for each project we reference. With signoff there by each Project Lead. Most important projects:

* `web5-js`
* `dwn-sdk-js`
* `dwn-server`
*  `ssi-sdk`
*  `ssi-service`
* ...others as raised by OSE; likely ask in Discord :)

Starts to address ideas raised in:
* https://github.com/TBD54566975/open-source-playbook/issues/17.

Support Programs: @dayhaysoos 
Support design (if available): @kirahsapong, @bobbilee19

**Comment by EbonyLouis** [comment]
Repos to highlight: 

- `web5-js`
- `dwn-sdk-js`
- `dwn-server`
- `ssi-sdk`
- `ssi-service`
- `ssi-playground`
- `developer.tbd.website`
- `ssi-admin-ui`

**Comment by EbonyLouis** [comment]
Update: We are going to use the same PR we have open for the [feedback widget](https://github.com/TBD54566975/developer.tbd.website/pull/449)

The feedback widget will have a link to this contributing landing page. It will also live in the side bar in docs. Open to hearing if anyone feels it should live somewhere else 

At the bottom of the page we are also going to reuse the 'join the community' component that we have in the docs/index page. 
This should be ready to preview by tomorrow morning.

**Comment by EbonyLouis** [comment]
Update: we'll leave the 'thank you' section out until we hear from Julie on potential liability. The [hackmd](https://hackmd.io/_J1S7dG1SeC3kAa-drm4jQ?both) is revised, and will live at `open-source/contributing `. Nick will do it by EOD

**Comment by ALRubinger** [comment]
Done in 507ec11d3286b19132928c942b8586c8150c25d4
