### ISSUE TITLE
Create Feedback Widget for Docs section

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/developer.tbd.website#442]
Dependency:

*  https://github.com/TBD54566975/developer.tbd.website/issues/441

Rough idea:

A floating widget on the bottom right on pages in the docs section of the Dev Site, which when expanded asks something like "Issue with this? Way to make it better? Let us know!"

Link will be to create a new issue (from a template @ALRubinger can provide) about the page this references, section, what could have been better, what was expected, etc.

Deliverables:

* Design of widget in "minimized" mode
* Design of the expanded widget including copy and the link to the new issue template

Support Design (if available): @kirahsapong @bobbilee19 
Support Programs: @dayhaysoos

**Comment by dayhaysoos** [comment]
I think the real issue is the amount of spacing that the feedback widgets creates between the rest of the elements of the page. All that space to the left is kind of awkward. @EbonyLouis suggested making this thinner and allowing it to expand, so I'm going to try that.

![Image](https://github.com/TBD54566975/developer.tbd.website/assets/1852675/a23a6785-2e1c-4851-a582-b1f0e4ab8e6d)

**Comment by dayhaysoos** [comment]
New updated component with the expand functionality

Before:

![Image](https://github.com/TBD54566975/developer.tbd.website/assets/1852675/8a324ba9-61a7-4ef4-8792-d07802abdf71)

After:



![Image](https://github.com/TBD54566975/developer.tbd.website/assets/1852675/f9852706-e2a9-45cc-bce4-4c8ad21c1d21)

The arrow also pulses.

Where should we go from here? Should the "Was this page helpful" text be smaller?

Where should this be placed?


Check out the deploy preview, I'm about to push

**Comment by EbonyLouis** [comment]
hmm yea still not a fan the border is too thick, the borders on the docs index page is thinner and lighter in color. we need spacing as well. hoping on the call early with Kirah if you want to join @dayhaysoos

**Comment by ALRubinger** [comment]
Noting from call - my brilliant idea to make it a collapsable thing that floats on the page is trash. I believe in the call we agreed that a component on the bottom of every docs page where it's embedded right into the content at the end worked well.

**Comment by ALRubinger** [comment]
Example from [Expo](https://docs.expo.dev/tutorial/create-your-first-app/), at the bottom:

<img width="853" alt="image" src="https://github.com/TBD54566975/developer.tbd.website/assets/199891/6df1ca0d-4fbb-4e3f-b5a4-dd61c6e78c08">

**Comment by EbonyLouis** [comment]
Yes, it looks so much better being a full section. There's some spacing and sizing issues but I'm not sure if you are just leaving that for Kirah to do, or if you would like me to call them out?

**Comment by dayhaysoos** [comment]
@EbonyLouis please call them out, Kirah's work is going to be in a different branch

**Comment by dayhaysoos** [comment]
Oohh that feedback isn't particular to the feedback widget, that's the design stuff Kirah will be doing (regarding the next steps stuff)

I can adjust the font of the "was this page helpful" text

**Comment by ALRubinger** [comment]
Done in 413ad8751fdfcd688c8c351ea61fa5ae8ef2b099
