### ISSUE TITLE
Update TODO App support on Dev Site to Web5 0.6.x

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/developer.tbd.website#446]
Dependencies: 

* https://github.com/TBD54566975/web5-tutorials/issues/2
* https://github.com/TBD54566975/web5-tutorials/issues/7
* https://github.com/TBD54566975/incubating-web5-labs/issues/49

Update the dependencies, links, and the tutorial itself on the Dev Site to the newly-released version.

**Comment by angiejones** [comment]
@ALRubinger is this for the post 0.6.0 (i.e 0.7.0) version?

**Comment by ALRubinger** [comment]
@angiejones Nope, it's for the work currently underway to bring it up to `0.6.x`; fast-follow with hopefully minimal changes for `0.7.x` as part of all docs updates for the new version in:

https://github.com/TBD54566975/developer.tbd.website/issues/435

**Comment by ALRubinger** [comment]
This is now in @angiejones review as https://github.com/TBD54566975/developer.tbd.website/pull/447

**Comment by ALRubinger** [comment]
Done as detailed in PR #447
