### ISSUE TITLE
[FEEDBACK]: footer overlaps with highlight videos in a Learn post

### ISSUE THREAD

**Issue by jiyoontbd** [TBD54566975/developer.tbd.website#451]
### Type

Site Bug Report

### Feedback

In pages like [this](https://developer.tbd.website/learn/discussions/decentralized-identity/) within the Learn tab, there's highlight videos that overlap with each other (if more than 1), as well as with the footer.  I can't access the controls of the video on the left side. 

### Screenshots

![image](https://github.com/TBD54566975/developer.tbd.website/assets/118510103/7bb83fc8-2e15-4ac4-9792-988dd12cb817)

### developer.tbd.website URL

https://developer.tbd.website/learn/discussions/decentralized-identity/

### Browser

Chrome

**Comment by EbonyLouis** [comment]
Thank you for pointing this out!
