### ISSUE TITLE
[FEEDBACK]: Web5 Quickstart Output

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/developer.tbd.website#452]
### Type

Feedback - Improvement Suggestion

### Feedback

From @jiyoontbd in [Discord](https://discord.com/channels/937858703112155166/949067751803191397/1105672024115912755):

> in web5 quickstart page step 4: https://developer.tbd.website/docs/web5/quickstart/#4-write-dwn-records
>
> i think it could be neat for folks walking through the quickstart to see a console log that actually prints the destructured record object stored in the DWN. 
> the most obvious (and not the prettiest) way would be to call console.log('write result', JSON.stringify(record, null, 4)) instead of console.log('write result', record) as shown in the screenshot #1 
>
> as a side note, the collapsible code block below the "Run!" button in this step shows the whole object returned from the await web5.dwn.records.create(...) method, not just the destructured record object - see screenshot #2

### Screenshots

![](https://cdn.discordapp.com/attachments/949067751803191397/1105672024321429596/image.png)

![](https://cdn.discordapp.com/attachments/949067751803191397/1105672024652795914/image.png)

### developer.tbd.website URL

https://discord.com/channels/937858703112155166/949067751803191397/1105672024115912755

### Browser

Chrome

**Comment by finn-tbd** [comment]
@blackgirlbytes can you validate that this still needs to be done or close it if it doesn't? ty
