### ISSUE TITLE
[FEEDBACK]: Unexpected response in Web5 Quickstart on delete

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/developer.tbd.website#454]
### Type

Docs Bug Report

### Feedback

From @jiyoontbd in [Discord](https://discord.com/channels/937858703112155166/949067751803191397/1105679982061162566): 

> ok, now in step 7, deleting records https://developer.tbd.website/docs/web5/quickstart/#7-delete-dwn-records
>
> i would have expected the last line to throw an error because i'm trying to access a deleted record's text, but instead, i got Hello, I'm updated! string 🤔 is this expected behavior, or am i calling the wrong method in the last line? 

```
const updateResult = await record.update({data: "Hello, I'm updated!"});
console.log('Update result: \n', await record.data.text());


const deleteResult = await record.delete();

console.log('Delete result: ', deleteResult);

console.log('Trying to read deleted record: \n', await record.data.text());
```

### Screenshots

Paste relevant images or screenshots here

### developer.tbd.website URL

https://developer.tbd.website/docs/web5/quickstart/#7-delete-dwn-records

### Browser

Chrome

**Comment by ALRubinger** [comment]
@kirahsapong with 🔥: https://discord.com/channels/937858703112155166/949067751803191397/1105685544626827316

**Comment by bobbilee19** [comment]
Not seeing this anymore are we? @ALRubinger @kirahsapong When i run web5-app with the quickstart steps I'm seeing delete work.

**Comment by ALRubinger** [comment]
@bobbilee19 The issue could simply be out of date; if you've verified all is working and logging correctly from prior fixes, cool to close

**Comment by jiyoontbd** [comment]
Yep! I just tested it again with the latest doc on https://developer.tbd.website/docs/web5/quickstart/ and everything works as I expect. i.e. reading `await record.data.text()` on a deleted record throws an error :)

**Comment by ALRubinger** [comment]
Thank you @jiyoontbd!
