### ISSUE TITLE
Proposing: Raise prominence of Web5 SDK API, DWN-Server, and DWA Starter Template

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/developer.tbd.website#456]
Proposing we raise visibility on Docs Home "Getting Started" page of:

* Web5 SDK API Reference #436
* DWN Server Guide #437 
* DWA Starter Template (if ready) #438 

Right under "Quickstart", in the same way? Or as @csuwildcat suggests - columns in a row?

WDYT @angiejones? What I've heard from you: give prominence to these only if they meet a stability / quality bar.

Near the promo we do for Quickstart:

![Image](https://github.com/TBD54566975/developer.tbd.website/assets/199891/1153517c-ce4c-467c-b801-a48f9979f2a0)

**Comment by ALRubinger** [comment]
Determined from call: leave it as-is; we want to bump priority of Web5 SDK API Reference and (if ready) DWA Starter template instead. Updating ticket for @angiejones feedback.

**Comment by michaelneale** [comment]
I would even suggest that 
![image](https://github.com/TBD54566975/developer.tbd.website/assets/14976/01441cd5-083f-4db6-a3b7-fe23d4fba372)
could almost be the home page for a while - as its so crisp and clear for developers. 

Elastic had that for a while as their home page - a snippet of code.

**Comment by ALRubinger** [comment]
Ty and will take that into the work @angiejones and I will do w/ Brand/marketing in refreshing the Home. Agree in principle about driving people into the deeper sections to get involved, showing the code. We'll work on the how.

Also - colors are good. :)

**Comment by ALRubinger** [comment]
Direction from @angiejones: 

* dwa-starter and dwn-server, when available, to be surfaced on Sidebar, not Home Page. Sidebar page for these has simple: heading, brief blurb, and button like seen on Docs Section Home to link out to GitHub.

**Comment by angiejones** [comment]
> Direction from @angiejones:
> 
> * dwa-starter and dwn-server, when available, to be surfaced on Sidebar, not Home Page. Sidebar page for these has simple: heading, brief blurb, and button like seen on Docs Section Home to link out to GitHub.

![image](https://github.com/TBD54566975/developer.tbd.website/assets/15972783/566f4c22-647e-4c6d-b283-b6ea52784078)

**Comment by angiejones** [comment]
preview link for guide on Hosting DWN: 
https://deploy-preview-470--tbd-website-developer.netlify.app/docs/web5/build/decentralized-web-nodes/host-dwn-server

**Comment by michaelneale** [comment]
looks good to me.
