### ISSUE TITLE
Add contributor page to sidebar

### ISSUE THREAD

**Issue by EbonyLouis** [TBD54566975/developer.tbd.website#461]
Currently we have a link to this page in the feedback section. However for visibility it should also be in the sidebar. 

I know you and Chris are doing a lot with the sidebar so per our discussions this can be done last.

**Comment by angiejones** [comment]
would prefer it not be on the sidebar, as every link on the sidebar provides education.

I think having it at the bottom of every page in the widget is sufficient. It can also go here on the Docs index page if you'd like



![Image](https://github.com/TBD54566975/developer.tbd.website/assets/15972783/8ae7f5a8-0466-4419-8cf1-968826ef22eb)
