### ISSUE TITLE
Create doc component with instructions on installing and importing Web5 JS

### ISSUE THREAD

**Issue by angiejones** [TBD54566975/developer.tbd.website#493]
Most of the guides and tutorials have a prereq for installing and importing Web5. I don't want us to repeat this everywhere, nor point to the Quickstart.

Instead, let's create a Component that we can embed in the guides.

**Comment by rishabhpathak359** [comment]
I would like to work on this,but can u pls elaborate it?

**Comment by MasterK0927** [comment]
Hey team, I will like to contribute in this project repo

**Comment by angiejones** [comment]
> I would like to work on this,but can u pls elaborate it?

The instructions under **Install** and **Import** are provided on the [API Reference Guide](https://developer.tbd.website/api/web5-js#install). We'd like this to be made into a [component](https://github.com/TBD54566975/developer.tbd.website/tree/main/site/src/components) so that we can place it on any page and only have to update it in one spot if necessary.

let me know if you'd still like to do it

**Comment by MasterK0927** [comment]
Yeah I am willing to take this project. It will be great of you if you will prefer me.

**Comment by rishabhpathak359** [comment]
@angiejones yes i would still work on it as i was the first one to ask

**Comment by angiejones** [comment]
> @angiejones yes i would still work on it as i was the first one to ask

I'm so sorry. you have first dibs on [this one](https://github.com/TBD54566975/developer.tbd.website/issues/821) if you want it. please reply on the [new issue](https://github.com/TBD54566975/developer.tbd.website/issues/821) if you'd like me to assign it to you

**Comment by angiejones** [comment]
> > @angiejones yes i would still work on it as i was the first one to ask
> 
> I'm so sorry. @rishabhpathak359 you have first dibs on [this one](https://github.com/TBD54566975/developer.tbd.website/issues/821) if you want it. please reply on the #821 if you'd like me to assign it to you

@rishabhpathak359 going to hold this issue for you for one more day 🙏🏾

**Comment by leordev** [comment]
Hey @MasterK0927 just checking in! 😊 Do you need any help with this one?

**Comment by finn-tbd** [comment]
This has been completed
