### ISSUE TITLE
Styling on Docs Home is off

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/developer.tbd.website#496]
Spotted by @decentralgabe:

![image](https://github.com/TBD54566975/developer.tbd.website/assets/199891/f6f9813d-940d-4038-8a1f-4164737a9be0)

And reported [via Discord](https://discord.com/channels/937858703112155166/949067751803191397/1110654156240343121)

**Comment by angiejones** [comment]
page has been redone and image has been intentionally removed
