### ISSUE TITLE
Update DID API Docs

### ISSUE THREAD

**Issue by angiejones** [TBD54566975/developer.tbd.website#511]
There's some disparity in the `did` [API docs](https://developer.tbd.website/api/web5-js/did)

- Parameter doesn't match description (e.g. the first parameter says `did` but the field name shows `method`)
- Code snippet isn't calling the right method

This is seen in:

- ~getKeys()~
- getMethodAPI()
- getServices()
- resolve()
- getDidDocument()

Notes from @frankhinek:

- DID class has changed
-- Remove `manager` property
-- Only methods to document are: `create` and `resolve`

**Comment by mistermoe** [comment]
There is no `getKeys` method anymore
