### ISSUE TITLE
Reduce Maintenance Overhead

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/developer.tbd.website#533]
Umbrella issue for work related to making Web5 (and other projects) upgrades on the Developer Site simpler. From [Discord thread](https://discord.com/channels/937858703112155166/1111754777307660388):

- [x] #532 
- [ ] Step 2 - Introduce Comprehensive Automated Test Suite (issue to come)
- [ ] Step 3 - Inject tested code into written docs (issue to come)
- [ ] Step 4 - Automate wherever possible (issue to come)

**Comment by angiejones** [comment]
@dayhaysoos can we close this one?
