### ISSUE TITLE
Update Quickstart: Instantiation

### ISSUE THREAD

**Issue by angiejones** [TBD54566975/developer.tbd.website#538]
https://developer.tbd.website/docs/web5/quickstart/#1-instantiate-web5

Need to update the description of the title and description of Step 1: Instantiate Web5

It now instantiates Web5 and also provides a class instance representing the decentralized identifier that was created or attained connection to

**Comment by bobbilee19** [comment]
https://github.com/TBD54566975/developer.tbd.website/issues/538
