### ISSUE TITLE
Optimize Design for Mobile

### ISSUE THREAD

**Issue by michaelneale** [TBD54566975/developer.tbd.website#540]
### Type

Suggestion to Improve

### Feedback

Would be good to optimise some content for mobile phones, for those you use time in queues to read up on docs. 

### Screenshots

![image](https://github.com/TBD54566975/developer.tbd.website/assets/14976/31ef3f75-60a0-4d5c-8674-99b19f8a420e)

### Browser

Chrome

**Comment by ALRubinger** [comment]
Likely some quick wins we can get, as well as more comprehensive design review of site components to uniformly apply.

**Comment by finn-tbd** [comment]
This is coming with a larger planned refresh.

**Comment by ALRubinger** [comment]
And we got some quick wins with a smaller UX stream of work awhile back
