### ISSUE TITLE
[FEEDBACK]: thoughts on improving the protocol tutorial page

### ISSUE THREAD

**Issue by jiyoontbd** [TBD54566975/developer.tbd.website#558]
### Type

Docs Bug Report

### Feedback

- in the grey note box, right above `Protocol Basics` heading
- type.ts link https://github.com/TBD54566975/dwn-sdk-js/blob/main/src/interfaces/protocols/types.ts goes to 404. where does this file live now? https://github.com/TBD54566975/dwn-sdk-js/blob/v0.0.21/src/interfaces/protocols/types.ts 

- under `Protocol Basics` heading
    - maybe `actions` should be `$actions` throughout, since the `$` is important part of the keyword.
    - the protocol code: 
        - all `schema` fields: should probably be a link? like `http://social-media.xyz/schema/message` for message type, and similarly shaped for other types
        - `types.image.schema` - does it make sense for JPEG data format to have a schema? 
        - `structure.image.$actions` - `anyone read` action object may be redundant?
    - worth looking over the whole `structures` section of the protocol with diane to make sure we're doing it right? 

- under `Protocols in Practice` heading
    ```javascript
    // currently in the doc:
    const response = await web5.dwn.protocols.configure(myDid.id, protocolObject);

    // but the above should change to:
    const { protocol, status } = await web5.dwn.protocols.configure({
        message: {
        definition: protocolDefinition // reference protocolDefinition in the earlier section with a variable
        }
    });

    // currently in the doc:
    const { record } = await web5.dwn.protocols.query({
    from: 'did:example:alice',
    message: {
        filter: {
            protocol: 'social-media',
        },
    },
    });

    // but the above should be... removed altogether. 
    // we cannot query another DWN's protocol, until permissions are implemented, which Diane is currently working on. also, there's a bug in the protocols.query() where it currently ignores the from field altogether anyway.

    // currently in the doc:
    const { record } = await web5.dwn.records.create({
    data: 'Hello, world!',
    message: {
        recipient: 'did:example:alice'
        schema: 'message',
        dataFormat: 'text/plain',
        protocol: 'social-media',
    },
    });

    await record.send('did:example:alice')

    // but the above should change to:
    const { record, status: createStatus } =
    await web5.dwn.records.create({
      data: 'Hello, world!',
      message: {
        recipient: aliceDid,
        schema: 'http://messageschema',
        dataFormat: 'text/plain',
        protocol: protocolDefinition.protocol, // or, "http://social-media.xyz", and not 'social-media'
        protocolPath: 'message'
      },
    });

    const { status: sendStatus } = await record.send(aliceDid)
    if (sendStatus.code === 202) {
        console.log('send to alice success!!')
    }
    else {
        console.log('send failed!', sendStatus.code, sendStatus.detail)
    }
    ```

- other thoughts around improving this tutorial
    - i think we should **not** make the assumption in the doc that the person following the tutorial already has an "Alice" who has the protocol configured. 
    - instead, we should show them how to set up both an Alice and a Bob, each with their own DWN, and walk through setting up the protocol for Alice, then setting up the same protocol for Bob, then Bob sending a message to Alice
    - it would be great to show some code snippets of how to construct and send records that showcase the "nesting" of types, like maybe Bob can send Alice a `message`, and then Alice can send back to Bob a `reply`, in response to the message (since reply is nested in message in the protocol structure)

### Screenshots

Paste relevant images or screenshots here

### developer.tbd.website URL

https://developer.tbd.website/docs/web5/learn/protocols/

### Browser

N/A

**Comment by chris-tbd** [comment]
PR merged and fixed
