### ISSUE TITLE
[FEEDBACK]: Open Source Page Event Section Out of Date & Doc Site Fails to Start on Localhost

### ISSUE THREAD

**Issue by okhaimie-dev** [TBD54566975/developer.tbd.website#571]
### Type

General Feedback

### Feedback

The upcoming event on the "Open Source" page is outdated. I wanted to create a PR to update this but I am running into an issue when trying to build the docusaurus site on my local host. I keep getting a 404 not found page after I install the application dependencies and run an `npm start`.

Here is the guide I followed to build the localhost [README](https://github.com/TBD54566975/developer.tbd.website/blob/main/site/README.md)

### Screenshots

Paste relevant images or screenshots here

![CleanShot 2023-06-27 at 19 17 46](https://github.com/TBD54566975/developer.tbd.website/assets/57156589/fcb67b0b-56d8-4312-82dd-4f628583afb7)

![CleanShot 2023-06-27 at 19 22 44](https://github.com/TBD54566975/developer.tbd.website/assets/57156589/ff31eb3a-2a47-4bff-ad64-756f5f376f21)

### developer.tbd.website URL

https://developer.tbd.website/open-source/contributing/

### Browser

Chrome

**Comment by EbonyLouis** [comment]
@okhaimie-dev thank you!, I was working on updating it yesterday evening and instead decided to table it for today. I know we're working on going from `npm` to `pnpm` however I don't think that PR has been merged yet. I'll look into what's going on here and get it updated today.  Thanks again! 🤗
