### ISSUE TITLE
ChatGPT like doc assistant on home page using ChatGPT plugin

### ISSUE THREAD

**Issue by michaelneale** [TBD54566975/developer.tbd.website#573]
### Type

Suggestion to Improve

### Feedback

Now there is a ChatGPT plugin, it may be interesting to have this accessable for anyone right in the doc site, perhaps below the quickstart? 

This can act as a documentation helper or even code writing assistant.

### Screenshots

Paste relevant images or screenshots here
![image](https://github.com/TBD54566975/developer.tbd.website/assets/14976/21f3b544-9baf-4253-a03b-ccde107d0b87)

**Comment by angiejones** [comment]
this would be soooo dope! I'm envisioning it right up top as a search bar in the header. so from anywhere on the site, people can query stuff

**Comment by michaelneale** [comment]
@angiejones so a search bar box - and then the response pops down below it? (trying to visualise it - do you have any sketching skills?)

**Comment by angiejones** [comment]
response could appear in a [Drawer component](https://codyhouse.co/ds/components/app/drawer)

**Comment by michaelneale** [comment]
nice. Adding https://github.com/openai/openai-cookbook/blob/main/examples/How_to_call_functions_for_knowledge_retrieval.ipynb as some ideas on how I may do it.

**Comment by michaelneale** [comment]
done here: https://github.com/TBD54566975/developer.tbd.website/pull/593
