### ISSUE TITLE
[USE CASE]: Stand up a remote, publicly-addressable DWN Server

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/developer.tbd.website#598]
### Developer Value Added

Fulfill the Web5 promise of "own your own data" by running and maintaining their own DWN node and storing their personal information on it, independent of any 3rd-party service providers.

### Use Case

Developer should be able to use software+instructions to:

* Stand up a `dwn-server` via Docker or a Node process (there are some good starting points for this in the emerging [`README`](https://github.com/TBD54566975/dwn-server/blob/main/README.md)
* Expose this to the public internet (`README` notes using the [`ngrok`](ngrok) agent for example)
* Set up sync so the DWN Server participates in the Web5 network. Our [sync guide](https://developer.tbd.website/docs/web5/learn/sync) notes a sync agent, and that this is transparent with DWNs created through the Web5 API. For standing up remote DWN servers - how to sync?
* Send messages from a Web5 webapp to the user's DID
  * Note: dependency on creating a publicly-resolvable DID? Available now, or document?
  * As part of this, stand up an example app to send simple messages to a DID so the user doesn't have to create their own? Or host on an embedded page on the dev site a "message sender" app to simply send messages anywhere?
*  See server logs or other confirmation on the running DWN that the message has been received and processed
* Optionally: use the remote DWN server to send ACK message back to the originator, so it can be shown as received by the initial sending app

### Dependencies

* Readiness of DWN Server via the OSE team
* Example "sender" application as noted above, hosted and embedded in Developer Site
* #600 
  * Documentation showing the user how to create a publicly-addressable DID (`did:ion`)

**Comment by finn-tbd** [comment]
done
