### ISSUE TITLE
API Doc: Update records.create to include published and datePublished attributes

### ISSUE THREAD

**Issue by bobbilee19** [TBD54566975/developer.tbd.website#599]
For the [records.create](https://developer.tbd.website/api/web5-js/dwn/records#createrequest) API, include fields under message for published and datePublished.

- published is optional and boolean
- datePublished is optional and string. if omitted, and published is specified, then the datePublished will be the current timestamp.

Code snippet for your reference:
```
const {record} = await web5.dwn.records.create({
    data: "a published record",
    message: {
        dataFormat: "text/plain",
        published: true,
        datePublished: dateToPublish,
    }
});
```

**Comment by bobbilee19** [comment]
@angiejones what should the `value`'s be set to?

**Comment by bobbilee19** [comment]
Here's what I have so far...

```
 {
                                    data: {
                                        type: 'boolean',
                                        isOptional: true,
                                        field: 'published',
                                        value: '',
                                    },
                                },
                                {
                                    data: {
                                        type: 'string',
                                        isOptional: true,
                                        field: 'datePublished',
                                        value: '',
                                    },
                                },          
```

**Comment by angiejones** [comment]
> Here's what I have so far...
> 
> ```
>  {
>   data: {
>       type: 'boolean',
>       isOptional: true,
>       field: 'published',
>       value: '',
>   },
> },
> {
>   data: {
>       type: 'string',
>       isOptional: true,
>       field: 'datePublished',
>       value: '',
>   },
> },          
> ```

hey @bobbilee19 , review the Publishing Records guide you wrote and I think you'll find the answers for these. The code snippet I added was for your reference, but feel free to add it as another example in the API doc
