### ISSUE TITLE
[FEEDBACK]: Incorrect instruction in web5 quickstart docs

### ISSUE THREAD

**Issue by blackgirlbytes** [TBD54566975/developer.tbd.website#606]
### Type

Docs Bug Report

### Feedback

The documentation instructs users to run `src/index.js`, but the `index.js file` is not located inside a src directory. It is actually located at the root of the project. This inconsistency in the documentation may confuse users who are trying to run the application.

I suggested either encouraging users to store the index.js file in a src directory first or just telling them to run `node index.js`

### Screenshots

<img width="1070" alt="Screenshot 2023-07-15 at 12 47 53 PM" src="https://github.com/TBD54566975/developer.tbd.website/assets/22990146/df601b68-ba06-4a1d-a801-e278858cbc7a">

<img width="710" alt="Screenshot 2023-07-15 at 12 50 21 PM" src="https://github.com/TBD54566975/developer.tbd.website/assets/22990146/04358837-a36f-4b38-81ee-f1c4e9a1fb14">
<img width="689" alt="Screenshot 2023-07-15 at 12 51 16 PM" src="https://github.com/TBD54566975/developer.tbd.website/assets/22990146/c7fe0eb5-ad92-430f-906c-a3e2d1bf41a0">

### developer.tbd.website URL

https://developer.tbd.website/docs/web5/quickstart

### Browser

Chrome

### Relevant log output

```shell
node src/index.js
node:internal/modules/cjs/loader:1073
  throw err;
  ^

Error: Cannot find module '/workspaces/asl/src/index.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1070:15)
    at Module._load (node:internal/modules/cjs/loader:923:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by angiejones** [comment]
thank you @blackgirlbytes!
