### ISSUE TITLE
Community Issue: Discord Series in Notion

### ISSUE THREAD

**Issue by EbonyLouis** [TBD54566975/developer.tbd.website#608]
[Here]( https://hackmd.io/WEOxkwj8SZu7hL3Yb943rw) is the work that has been done so far

## The Goal:

- [ ] - Expand on this series 
- [ ] - Add it into notion
- [ ] - Send it out in a custom welcome message 
- [ ] - Link it in our #getting-started channel 

Our fellow community member, Oladipo Yuusuf, has some great ideas about laying this series out in the format a new member would instinctively follow when joining.

**Comment by Civil-captain** [comment]
Hey @EbonyLouis I'll like to take up this issue.

**Comment by EbonyLouis** [comment]
I'm looking forward to seeing it, again feel free to reach out with any questions.

**Comment by EbonyLouis** [comment]
@all-contributors please add @Civil-captain for content
