### ISSUE TITLE
Revamp SSI docs

### ISSUE THREAD

**Issue by decentralgabe** [TBD54566975/developer.tbd.website#620]
SSI docs have a lot of room for improvement:

## 1. API Docs
Today our API docs render the latest swagger doc from the SSI service. Instead, we should switch to a release-based model that points to the docs from a recent release. This will allow us to annotate the content that's in the swagger with more helpful information to make the docs more usable.

As a reference, see the [MATTR docs](https://learn.mattr.global/api-reference/v2.0.0) which I think do a pretty good job of this. Well organized categories, detailed descriptions and examples, and overall it just feels a lot more approachable than what we've got today. Similarly, the [Microsoft Entra docs](https://learn.microsoft.com/en-us/azure/active-directory/verifiable-credentials/issuance-request-api) are a lot more approachable, human-readable and interactive.

## 2. Project homepage

From landing on the dev site, getting to docs from the SSI service is 3 clicks away on [the projects page](https://developer.tbd.website/projects/web5), but clicking on the SSI project just points to GitHub. I believe we should have an easier to access homepage that's a one stop jumping off point for all things SSI. 

There is also a separate [docs tab](https://developer.tbd.website/docs/ssi/run-ssi-service) so it is confusing on where I do actually find out what information is pertinent for learning about the SSI service.

I'd like to see something like homepage -> projects -> project specific homepage, where that homepage has all associated information.

### SSI Specific

We have one tutorial and it quickly gets out of date, it should similarly be tagged to a release of the SSI Service to avoid this issue.

One tutorial is not sufficient given the rich complexity of the service. I can identify at least 8 tutorials we should have, if not more:

1. Create a DID
2. Create a Schema
3. Create and issue a Credential
4. Revoke a Credential
5. Verify a Credential
6. Set up a Presentation Exchange Request, Verify a Presentation Submission
7. Set up a Credential Manifest Request, Verify a Credential Manifest and Issue Credential(s)
8. Set up a DID Well Known Configuration

Other ideas can include connecting to a HSM, using different databases, integrating into different transport systems (like OIDC or Web5) or configuring a cloud provider. Lots of opportunity for content here.

### More General

More broadly, there is room to have rich educational material on the site, useful to both technical and less-technical audiences. [Trinsic does a really good job](https://docs.trinsic.id/learn/) at this with the entire "learn" section on their site.

Similarly, the ["concepts" and "tutorials"](https://learn.microsoft.com/en-us/azure/active-directory/verifiable-credentials/verifiable-credentials-configure-tenant) section on Microsoft Entra's site are informative and helpful.

**Comment by angiejones** [comment]
we intentionally have not covered the independent SDKs like dwn or ssi. Our focus is on the Web5 SDK with plans to cover SSI functionality when it's integrated into web5.js.

If this plan isn’t ideal, I'm very happy to discuss.

**Comment by decentralgabe** [comment]
I believe SSI should be covered separately from its usage within the Web5 SDK, since the SSI Service is designed as a standalone product that can be run by any individual/organization that wants a full management suite for DIDs + VCs.

I cannot speak to relative prioritization, only that it would be valuable to have such documentation as we begin to see more usage of the service. Maybe @michaelneale or @frankhinek have a better sense of relative prioritization (or if there's a way we can do both).

**Comment by angiejones** [comment]
> I believe SSI should be covered separately from its usage within the Web5 SDK, since the SSI Service is designed as a standalone product that can be run by any individual/organization that wants a full management suite for DIDs + VCs.
> 
> I cannot speak to relative prioritization, only that it would be valuable to have such documentation as we begin to see more usage of the service. Maybe @michaelneale or @frankhinek have a better sense of relative prioritization (or if there's a way we can do both).

Fair enough. Will begin looking into coverage for the SSI service. Thanks, @decentralgabe!

**Comment by michaelneale** [comment]
yes I think this is distinct in many ways: the ssi service is something to be stood up primarily by those who wish to issue VCs to their users, and typically server side developers and integrators.
