### ISSUE TITLE
Query Guide: Add descriptions of filter types

### ISSUE THREAD

**Issue by bobbilee19** [TBD54566975/developer.tbd.website#622]
Here are the properties that records can be filtered on. Update the [Query Guide](https://developer.tbd.website/docs/web5/build/decentralized-web-nodes/query-from-dwn) to discuss each one

```
export type RecordsQueryFilter = {
  attester?: string;
  recipient?: string;
  protocol?: string;
  protocolPath?: string;
  contextId?: string;
  schema?: string;
  recordId?: string;
  parentId?: string;
  dataFormat?: string;
  dateCreated?: RangeCriterion;
};
```

**Comment by ianpatton** [comment]
+1

It would be great to detail options for sorting as well.

**Comment by angiejones** [comment]
> +1
> 
> It would be great to detail options for sorting as well.

These are already documented 😊
https://developer.tbd.website/docs/web5/build/decentralized-web-nodes/query-from-dwn/#sorting-query-results
