### ISSUE TITLE
Consider DocSearch

### ISSUE THREAD

**Issue by angiejones** [TBD54566975/developer.tbd.website#641]
I really like this site's [Search feature](https://enhance.dev/docs/learn/starter-project/pages). Should we consider adding [docsearch](https://docsearch.algolia.com/) to our dev site?

**Comment by dayhaysoos** [comment]
Hey Angie, Doc Search is free for open source projects but it needs to be approved by Algolia. I've already submitted an application to get API keys, so we'll have to wait for the Algolia team to review our application. Once we get the API keys setting it up would be a matter of minutes as Docusaurus already supports Doc Search under the hood.
