### ISSUE TITLE
Styling Idea Change for Prerequisites

### ISSUE THREAD

**Issue by bobbilee19** [TBD54566975/developer.tbd.website#657]
I've already done this to the schema guide in my new PR -- so in this PR im going to edit a few places where I think this will look great too!

OLD way of doing things...
<img width="483" alt="Screenshot 2023-08-11 at 9 28 06 PM" src="https://github.com/TBD54566975/developer.tbd.website/assets/2551955/b52391df-c1d6-43a7-8ea0-bc8a100e0780">

SUGGESTED new way of doing things...
<img width="480" alt="Screenshot 2023-08-11 at 9 27 48 PM" src="https://github.com/TBD54566975/developer.tbd.website/assets/2551955/bc83f5b8-d5e5-413f-ae64-71dbab59f089">

**Comment by bobbilee19** [comment]
OLD way of doing things...
<img width="483" alt="Screenshot 2023-08-11 at 9 28 06 PM" src="https://github.com/TBD54566975/developer.tbd.website/assets/2551955/b52391df-c1d6-43a7-8ea0-bc8a100e0780">

SUGGESTED new way of doing things...
<img width="480" alt="Screenshot 2023-08-11 at 9 27 48 PM" src="https://github.com/TBD54566975/developer.tbd.website/assets/2551955/bc83f5b8-d5e5-413f-ae64-71dbab59f089">

**Comment by bobbilee19** [comment]
I've already done this to the schema guide in my new PR -- so in this PR im going to edit a few places where I think this will look great too!

**Comment by bobbilee19** [comment]
<img width="485" alt="Screenshot 2023-08-11 at 9 32 27 PM" src="https://github.com/TBD54566975/developer.tbd.website/assets/2551955/935ef024-3c2f-48cc-aedf-9044bdd64c5c">

<img width="471" alt="Screenshot 2023-08-11 at 9 32 05 PM" src="https://github.com/TBD54566975/developer.tbd.website/assets/2551955/fa123270-d88c-4ea8-8323-135e7fe4b7e1">

**Comment by bobbilee19** [comment]
<img width="460" alt="Screenshot 2023-08-11 at 9 39 43 PM" src="https://github.com/TBD54566975/developer.tbd.website/assets/2551955/70f6919a-e319-4542-ae55-f3b86c642309">

<img width="462" alt="Screenshot 2023-08-11 at 9 38 50 PM" src="https://github.com/TBD54566975/developer.tbd.website/assets/2551955/01c36bdf-c210-4dca-a490-47799557b9d0">
15-be2c-79ce0b98972d">

**Comment by angiejones** [comment]
opened https://github.com/TBD54566975/developer.tbd.website/issues/661 to create as a reusable component
