### ISSUE TITLE
Create component for SSI Service Prereq

### ISSUE THREAD

**Issue by angiejones** [TBD54566975/developer.tbd.website#661]
since we're repeating the same thing over and over, I suggest making this a component and just embedding it in these guides. That way if we ever need to make any changes to this, we will only need to do so in one place

![image](https://github.com/TBD54566975/developer.tbd.website/assets/15972783/d29f89f9-ac0d-424e-9765-c9f8e63d007c)

**Comment by ShavonHarris-Dev** [comment]
I'll take this!

**Comment by blackgirlbytes** [comment]
yay! I assigned you @ShavonHarris-Dev . We can work on this together.

**Comment by blackgirlbytes** [comment]
wait I assigned you, but then I got nervous 😆 I'll wait for Ebony or Angie to confirm you can be assigned to this and then we can work on it together 😄

**Comment by angiejones** [comment]
> @ShavonHarris-Dev YAY!
> 
> wait I assigned you, but then I felt uncertain because I'm not sure of the rules since this doesn't have a hacktoberfest or good first issue label 😆 , but this definitely seems doable.
> 
> I'll wait for Ebony or Angie to confirm you can be assigned to this and then we can work on it together 😄
> 
> If they say yes, maybe we can see if they can also count this as a Hacktoberfest issue too!

thanks! I've added it to Hacktoberfest and assigned to Shavon
