### ISSUE TITLE
ChatGPT codeblocks blacked out on docs pages

### ISSUE THREAD

**Issue by angiejones** [TBD54566975/developer.tbd.website#671]
hey @kirahsapong when Chad shows code on the /docs sections of the site, the codeblock is blacked out

to recreate:
1. go to https://developer.tbd.website/docs/#search
2.  enter "show me how to connect to web5"

<img width="578" alt="image" src="https://github.com/TBD54566975/developer.tbd.website/assets/15972783/147dd46f-c12e-4bd7-913c-9da620f478e6">

**Comment by michaelneale** [comment]
@angiejones was there some style change recently as it was ok 12 hours ago

**Comment by michaelneale** [comment]
@angiejones @kirahsapong https://github.com/TBD54566975/developer.tbd.website/pull/672

**Comment by michaelneale** [comment]
I checked on the main page only, oops. Still broken on docs https://developer.tbd.website/docs/#search
