### ISSUE TITLE
Bug: code snippet not found

### ISSUE THREAD

**Issue by angiejones** [TBD54566975/developer.tbd.website#707]
![Screenshot_20230904_143654_Chrome](https://github.com/TBD54566975/developer.tbd.website/assets/15972783/6831c2bb-0c02-40ee-b9a7-3e0195fcb431)

https://developer.tbd.website/docs/web5/build/decentralized-web-nodes/query-from-dwn/#descending-order

**Comment by dayhaysoos** [comment]
Hey @angiejones, just fixed this. 

I might look into something that would allow us to catch these errors before we deploy
