### ISSUE TITLE
Add Incubation Project to README.md

### ISSUE THREAD

**Issue by EbonyLouis** [TBD54566975/developer.tbd.website#731]
## Current State:
Currently, we have one incubation project listed [here](https://github.com/TBD54566975#). We need to add our second incubation project, the tbLEND protocol.

<img width="865" alt="Screenshot 2023-09-19 at 4 28 49 PM" src="https://github.com/TBD54566975/developer.tbd.website/assets/55366651/ba4524ee-e919-4b5c-a0ce-a99af2c87feb">

## Task:
Please add our tbLEND project to the chart [here](https://github.com/TBD54566975#) in our org's README. 
- For the description, see this [overview of the project](https://photos.onedrive.com/share/177DEE71378DB3AD!9886?cid=177DEE71378DB3AD&resId=177DEE71378DB3AD!9886&authkey=!APppAVFUzYZ2LIY&ithint=video&e=fddgt9).
- Discord channel link: https://discord.com/channels/937858703112155166/1149083370408640626 
- As there is no repo yet, use the Discord link for the project's name, similar to how the "credential selector" links to its project.
- Project Lead: @ianpatton

## Picking Up This Issue:
- If you'd like to work on this, please comment "picking this up" below, and I'll assign the issue to you 

## Questions:
- If you need assistance or clarification, feel free to comment below.
- Feeling overwhelmed? Join our [`#hack-together` channel](https://discord.gg/tbd) and collaborate with a buddy.
- New to open-source? Check out our [Hacktober `#getting-started` channel](https://discord.gg/tbd).
- [Leaderboard](https://github.com/TBD54566975/developer.tbd.website/issues/721): Check your ranking after finishing this task.

## Resources:
- READMEs are written in Markdown. If you're unfamiliar, here's a [Markdown cheatsheet](https://www.markdownguide.org/cheat-sheet/) to help.
> Tip: Use the "Preview" tab at the top when editing the README to ensure the format aligns with your expectations.

Good Luck! 🍁

**Comment by Pratham271** [comment]
picking this up

**Comment by Pratham271** [comment]
Also I want to ask that should I add a 3rd table next to the previous 2 tables or make it in the new line

**Comment by EbonyLouis** [comment]
@Pratham271 Thank you so much for your enthusiasm and readiness to contribute!

I'd like to note that Hacktoberfest officially kicks off on **October 1st**. Contributions made before the event may not be eligible for the challenge. However, if you're keen on this specific issue, feel free to start working on it, but I'd recommend holding off on submitting your PR until the event begins. 

> make sure you're registered, registration [opens September 26th.](https://hacktoberfest.com/) 

Also stay tuned our [Hacktoberfest channels ](https://discord.com/channels/937858703112155166/1151216855957123104) in discord will be live this Thursday. That's where you'll find all the updates leading up to and during Hacktoberfest. I'm super excited to see your contributions!


**To claify**, I would love it to be right next to "credential selector" the same way "Web5" and "tbDEX" are in the chart above it.  - thanks!

**Comment by angiejones** [comment]
@Pratham271 are you still interested in taking this one?

**Comment by hanzalahwaheed** [comment]
Hello! I'd like to work on it if available! Thank You!

**Comment by Lymah123** [comment]
Hello, I would like to work on the issue. Thank you!

**Comment by Pratham271** [comment]
Yes I am working on it

**Comment by parag477** [comment]
Hey I am also willing to work on this. Please assign me this @EbonyLouis

**Comment by blackgirlbytes** [comment]
@Pratham271 hey!! How are things going with this PR? Do you need any assistance?

**Comment by Pratham271** [comment]
I generated a pr for this issue today but it the readme files are on another repo

**Comment by EbonyLouis** [comment]
@Pratham271 yes, send me a link to your PR please

**Comment by Pratham271** [comment]
https://github.com/TBD54566975/.github/pull/8
Here is the link to that pr, please check and let me know if I have to change something
