### ISSUE TITLE
Invalid DOM property `class` on /docs page

### ISSUE THREAD

**Issue by dayhaysoos** [TBD54566975/developer.tbd.website#742]
## Objective:
Somewhere within the docs page there is an element that has `class` instead of `className` (for react). We need to find that and replace it with the appropriate attribute.

## Picking Up This Issue:
- If you'd like to work on this, please comment "picking this up" below, and I'll assign the issue to you 

## Questions:
- If you need assistance or clarification, feel free to comment below.
- Feeling overwhelmed? Join our [`#hack-together` channel](https://discord.gg/tbd) and collaborate with a buddy.
- New to open-source? Check out our [Hacktober `#getting-started` channel](https://discord.gg/tbd).
- [Leaderboard](https://github.com/TBD54566975/developer.tbd.website/issues/721): Check your ranking after finishing this task.

### Resources:
- **Docusaurus Documentation**: Familiarize yourself with how Docusaurus works. Here's the [official documentation](https://docusaurus.io/docs).
- **Creating a Pull Request**: If you're new to GitHub and unsure how to create a pull request, follow this [step-by-step guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request).

Remember, communication is key! If you have any questions or face any challenges, we're here to help so please don't hesitate to reach out.

Good Luck! 🍁

**Comment by Tiensuperman** [comment]
picking this up, I was wondering if there's a specific Folder / File in /docs that this problem is occurring in? or do I have to figure it out myself as part of the challenge?

**Comment by rishabhpathak359** [comment]
picking this up

**Comment by EbonyLouis** [comment]
@Tiensuperman yay! I'l assign it to you now.

I'd also like to note that Hacktoberfest officially kicks off on **October 1st**. Contributions made before the event may not be eligible for the challenge. **However, feel free to start working on it, but I'd recommend holding off on submitting your PR until the event begins.** 

> to be eligible for Hacktoberfest's official prizes make sure you're registered, registration [opens September 26th.](https://hacktoberfest.com/) 

@dayhaysoos are you able to provide exactly where this problem is happening in the docs?

**Comment by EbonyLouis** [comment]
@rishabhpathak359 Hey there! Thanks for your enthusiasm to contribute. 😊 Someone got in just a bit ahead of you on this issue, but don't worry! We have other open `Hacktoberfest` tagged issues that you might find interesting. 
- [developer.tbd.website](https://github.com/TBD54566975/developer.tbd.website/issues?q=is%3Aopen+is%3Aissue+label%3Ahacktoberfest+no%3Aassignee)
- [web5-js](https://github.com/TBD54566975/web5-js/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22)
- [dwn-server](https://github.com/TBD54566975/dwn-server/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22)
- [dwn-sdk-js](https://github.com/TBD54566975/dwn-sdk-js/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee)

Also, we'll be adding more issues throughout the month of October, so there will be plenty of opportunities to jump in. If for any reason the current assignee can't proceed with this one, I'll definitely keep you in mind and reach out. keep an eye on our `events-and-updates` channel in [discord](https://discord.gg/tbd). Thanks for being a part of our Hacktoberfest journey! 

I know that this is the second issue, sorry,  if you want some help finding an issue that works for you feel free to message me in discord.

**Comment by dayhaysoos** [comment]
Hey @Tiensuperman,

Sorry for not clarifying. This error shows up specifically on the /docs url (but you'll only see it locally).

So if you spin up the dev environment and navigate to:

http://localhost:3000/docs/

You'll see the errors.

Lemme know if you have any more questions!

**Comment by Tiensuperman** [comment]
Should I wait until the start of Hacktoberfest to fix this issue??

**Comment by EbonyLouis** [comment]
@Tiensuperman yes, you can start working on it but wait until the 1st or after to submit your PR
