### ISSUE TITLE
Each Child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by dayhaysoos** [TBD54566975/developer.tbd.website#743]
### Background: 
The ApiDetails.jsx component has a map that needs to pass the key prop to the elements it's iterating through.

### Objective:
- Fix this error message that is originating in the `ApiDetails.jsx` component, the path to the component is `/site/src/components/ApiDetails.jsx`
> Hint: <React.Fragment>...</React.Fragment> 

```
react.development.js:220 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `ApiDetails`. See https://reactjs.org/link/warning-keys for more information.
    at ApiDetails (webpack-internal:///./src/components/ApiDetails.jsx:8:20)
    at eval (webpack-internal:///../node_modules/.pnpm/@mdx-js+react@1.6.22_react@17.0.2/node_modules/@mdx-js/react/dist/esm.js:154:30)
    at section
    at eval (webpack-internal:///../node_modules/.pnpm/@mdx-js+react@1.6.22_react@17.0.2/node_modules/@mdx-js/react/dist/esm.js:154:30)
    at wrapper (webpack-internal:///../node_modules/.pnpm/@mdx-js+react@1.6.22_react@17.0.2/node_modules/@mdx-js/react/dist/esm.js:149:25)
    at eval (webpack-internal:///../node_modules/.pnpm/@mdx-js+react@1.6.22_react@17.0.2/node_modules/@mdx-js/react/dist/esm.js:154:30)
    at MDXContent (webpack-internal:///./api/web5-js/index.mdx:19:1339)
    at MDXProvider (webpack-internal:///../node_modules/.pnpm/@mdx-js+react@1.6.22_react@17.0.2/node_modules/@mdx-js/react/dist/esm.js:139:46)
    at MDXContent (webpack-internal:///../node_modules/.pnpm/@docusaurus+theme-classic@2.4.1_react-dom@17.0.2_react@17.0.2_typescript@5.1.6/node_modules/@docusaurus/theme-classic/lib/theme/MDXContent/index.js:13:25)
    at div
```

## Picking Up This Issue:
- If you'd like to work on this, please comment "picking this up" below, and I'll assign the issue to you 

## Questions:
- If you need assistance or clarification, feel free to comment below.
- Feeling overwhelmed? Join our [`#hack-together` channel](https://discord.gg/tbd) and collaborate with a buddy.
- New to open-source? Check out our [Hacktober `#getting-started` channel](https://discord.gg/tbd).
- [Leaderboard](https://github.com/TBD54566975/developer.tbd.website/issues/721): Check your ranking after finishing this task.

### Resources:
- **Docusaurus Documentation**: Familiarize yourself with how Docusaurus works. Here's the [official documentation](https://docusaurus.io/docs).
- **Creating a Pull Request**: If you're new to GitHub and unsure how to create a pull request, follow this [step-by-step guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request).

Remember, communication is key! If you have any questions or face any challenges, we're here to help so please don't hesitate to reach out.

Good Luck! 🍁

**Comment by pateldivyesh1323** [comment]
@dayhaysoos I would like to work on this.

**Comment by rishabhpathak359** [comment]
@dayhaysoos picking this up

**Comment by EbonyLouis** [comment]
@pateldivyesh1323 yay! I'l assign it to you now.

I'd also like to note that Hacktoberfest officially kicks off on **October 1st**. Contributions made before the event may not be eligible for the challenge. **However, feel free to start working on it, but I'd recommend holding off on submitting your PR until the event begins.** 

> to be eligible for Hacktoberfest's official prizes make sure you're registered, registration [opens September 26th.](https://hacktoberfest.com/) 

Reach out if you need any help 🥳

**Comment by EbonyLouis** [comment]
@rishabhpathak359 Hey there! Thanks for your enthusiasm to contribute. 😊 Someone got in just a bit ahead of you on this issue, but don't worry! We have other open `Hacktoberfest` tagged issues that you might find interesting. 
- [developer.tbd.website](https://github.com/TBD54566975/developer.tbd.website/issues?q=is%3Aopen+is%3Aissue+label%3Ahacktoberfest+no%3Aassignee)
- [web5-js](https://github.com/TBD54566975/web5-js/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22)
- [dwn-server](https://github.com/TBD54566975/dwn-server/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22)
- [dwn-sdk-js](https://github.com/TBD54566975/dwn-sdk-js/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee)

Also, we'll be adding more issues throughout the month of October, so there will be plenty of opportunities to jump in. If for any reason the current assignee can't proceed with this one, I'll definitely keep you in mind and reach out. keep an eye on our `events-and-updates` channel in [discord](https://discord.gg/tbd). Thanks for being a part of our Hacktoberfest journey!
