### ISSUE TITLE
Error: Invalid DOM property `frameborder`. Did you mean `frameBorder`?

### ISSUE THREAD

**Issue by dayhaysoos** [TBD54566975/developer.tbd.website#744]
### Background:
This error is coming from our `/blog` page. 

```
Warning: Invalid DOM property `frameborder`. Did you mean `frameBorder`?
```

### Objective:
- Please update it to `frameBorder`
> Tip: at first glance it can be hard to tell, the 'b' in 'border' needs to be capitalized.

## Picking Up This Issue:
- If you'd like to work on this, please comment "picking this up" below, and I'll assign the issue to you 

## Questions:
- If you need assistance or clarification, feel free to comment below.
- Feeling overwhelmed? Join our [`#hack-together` channel](https://discord.gg/tbd) and collaborate with a buddy.
- New to open-source? Check out our [Hacktober `#getting-started` channel](https://discord.gg/tbd).
- [Leaderboard](https://github.com/TBD54566975/developer.tbd.website/issues/721): Check your ranking after finishing this task.

### Resources:
- **Docusaurus Documentation**: Familiarize yourself with how Docusaurus works. Here's the [official documentation](https://docusaurus.io/docs).
- **Creating a Pull Request**: If you're new to GitHub and unsure how to create a pull request, follow this [step-by-step guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request).

Remember, communication is key! If you have any questions or face any challenges, we're here to help so please don't hesitate to reach out.

Good Luck! 🍁

**Comment by comeworkwith-me** [comment]
Hey Team TBD, picking this up!

**Comment by EbonyLouis** [comment]
@comeworkwith-me assigned 🥳 I'm super excited that you're contributing to open source with us. Reach out if you have any questions.

As I've mentioned on the other tickets Hacktoberfest officially kicks off on **October 1st**. Contributions made before the event may not be eligible for the challenge. **However, feel free to start working on it, but I'd recommend holding off on submitting your PR until the event begins.** 

> to be eligible for Hacktoberfest's official prizes make sure you're registered, registration [opens September 26th.](https://hacktoberfest.com/)

**Comment by Nikhil-Gaikwad-Dev** [comment]
Hello, as this issue is still open can I work on it.   
picking this up

**Comment by EbonyLouis** [comment]
@comeworkwith-me Hey, would you still like to work on this issue?

**Comment by comeworkwith-me** [comment]
@EbonyLouis yes.

**Comment by EbonyLouis** [comment]
@Nikhil-Gaikwad-Dev thank you! Let's let @comeworkwith-me get a chance to work on this. Let me know if you want any help finding another open issue to work on.
