### ISSUE TITLE
Create an Incubation Projects Highlight Page 🚀

### ISSUE THREAD

**Issue by EbonyLouis** [TBD54566975/developer.tbd.website#746]
### Background:
[TBD Incubation Projects](https://developer.tbd.website/open-source/incubation) are managed by community contributors. As we grow, we need a dedicated page to showcase and highlight these projects.

### Objective:
Create an `Incubation Projects Highlight Page` for our Docusaurus site.

### Task Details:
1. **Page Location**: Create the new highlight page at `site/src/pages/community/incubation-projects`.

2. **Projects**: 
   - Start by featuring the `Credential Selector` project. Here's a link to the [project](https://github.com/TBD54566975/incubation-verifiable-credential-selector).
   - Here's a link to their [Discord channel](https://discord.com/channels/937858703112155166/1024468662469525645) if you need anything clarified. 

3. **Design**: 
   - Be creative in laying out the page! 
   > Stick with the website's color scheme. 
   - Ensure it's easy to add new projects in the future.

## Picking Up This Issue:
- If you'd like to work on this, please comment "picking this up" below, and I'll assign the issue to you 

## Questions:
- If you need assistance or clarification, feel free to comment below.
- Feeling overwhelmed? Join our [`#hack-together` channel](https://discord.gg/tbd) and collaborate with a buddy.
- New to open-source? Check out our [Hacktober `#getting-started` channel](https://discord.gg/tbd).
- [Leaderboard](https://github.com/TBD54566975/developer.tbd.website/issues/721): Check your ranking after finishing this task.

### Resources:
- **Docusaurus Documentation**: Familiarize yourself with how Docusaurus works. Here's the [official documentation](https://docusaurus.io/docs).
  
- **Components**: Feel free to utilize existing components in our codebase to maintain consistency and speed up development. Check out our components at `site/src/components`. 
  
- **Website Colors**: Ensure you're aligned with our brand colors and overall design aesthetic. Reference our existing pages and components for guidance.

Remember, communication is key! If you have any questions or face any challenges, we're here to help so please don't hesitate to reach out.

Good Luck! 🍁

**Comment by ALRubinger** [comment]
This is awesome. 

Dummy content for ~3 incubation projects should suffice to close this out - we can add the real info for our sponsoring orgs.

Info to be showcased for each Incubation Project:

* Sponsoring organization(s): Place for logos, org names and URLs
* Project Description: 3-4 sentences (lorum ipsum for this issue is fine)
* Link(s) to GitHub

**Comment by syedzubeen** [comment]
picking this up

**Comment by EbonyLouis** [comment]
@syedzubeen yay! I'l assign it to you now.

I'd also like to note that Hacktoberfest officially kicks off on **October 1st**. Contributions made before the event may not be eligible for the challenge. **However, feel free to start working on it, but I'd recommend holding off on submitting your PR until the event begins.** 

> to be eligible for Hacktoberfest's official prizes make sure you're registered, registration [opens September 26th.](https://hacktoberfest.com/)

**Comment by parag477** [comment]
Hey @EbonyLouis I am also willing to work on this issue. Can you please assign me this issue.

**Comment by EbonyLouis** [comment]
Hey @syedzubeen are you still interested in working on this issue?

**Comment by syedzubeen** [comment]
Hey @EbonyLouis 
Unassigning myself 'cause I'm caught up with stuff and am not actively finding time to work on this right now.

**Comment by Pratham271** [comment]
can i work on this now

**Comment by blackgirlbytes** [comment]
hey @parag477!!! Did you still want to work on this issue? If so, let me know so I can assign you.

**Comment by angiejones** [comment]
gonna assign to @Pratham271

**Comment by leordev** [comment]
Hey @Pratham271  just checking in! 😊 Do you need any help with this one?

**Comment by Pratham271** [comment]
Just tell me the projects which need to be added and the look of the page

**Comment by EbonyLouis** [comment]
@Pratham271 all the details can be found above in the original issue comment

**Comment by KhoiUna** [comment]
> @Pratham271 all the details can be found above in the original issue comment 
> 
> 

@EbonyLouis can I work on this for Hacktoberfest?

**Comment by EbonyLouis** [comment]
@Pratham271 I know you have a few issues that you are currently working on. With Hacktoberfest coming to a close I've assigned Khoiuna, to help get this issue to the finish line.

**Comment by KhoiUna** [comment]
@Pratham271 have you started working on it? If yes, may I see the code repo/progress?

**Comment by Pratham271** [comment]
Where should I share that to you

**Comment by KhoiUna** [comment]
> Where should I share that to you

You can comment here @Pratham271

**Comment by Pratham271** [comment]
---
hide_table_of_contents: true
---

import metacontent from '@site/src/content/global-meta';
import { content } from '@site/src/content/incubation-projects/incubation-project-index/incubation-projects';

<head>
  <title>{content.meta.title}</title>
  <meta property="og:description" content={metacontent.description} />
  <meta name="description" content={metacontent.description} />
  <meta property="og:title" content={content.meta.title} />
  <meta
    property="og:url"
    content={'https://developer.tbd.website/' + content.meta.path}
  />
  <link
    rel="apple-touch-icon"
    href="https://developer.tbd.website/img/tbd-fav-icon-main.png"
  />
</head>

<div className="prose prose-pink mb-13.5">

<content.ListOfProjects />

<Divider />

</div>

**Comment by Pratham271** [comment]
I have created an incubation-project file similar to projects file to make the design uniform and I have created multiple files to support this file if this is fine to you we can create a pr and if you want to make some changes we can do that as well

**Comment by EbonyLouis** [comment]
@Pratham271 , @KhoiUna , To make it easier I can give you both access to a tbd discord stage where you can screen share and work together. Just ping me on discord in the `hack-together` channel or any channel and I'll grant you both permissions. 

My Discord username: @ebonyl-tbd 
Discord Invite link: https://discord.gg/tbd

**Comment by KhoiUna** [comment]
> I have created an incubation-project file similar to projects file to make the design uniform and I have created multiple files to support this file if this is fine to you we can create a pr and if you want to make some changes we can do that as well

Can I see your fork? Can you post the URL here?
