### ISSUE TITLE
Update Button Link for Incubation Projects Page

### ISSUE THREAD

**Issue by EbonyLouis** [TBD54566975/developer.tbd.website#747]
### Background:
We're in the process of creating a new `Incubation Projects Highlight Page` for our Docusaurus site see [Issue #746  - Create an Incubation Projects Highlight Page](https://github.com/TBD54566975/developer.tbd.website/issues/746). Once that page is completed, we need to update a button link to point to this new page.

### Objective:
Update the `buttonUrl` property of the "Incubation Projects" button to direct users to the new `Incubation Projects Highlight Page`.

### Task Details:
> **Note**: Ensure [Issue #746  - Create an Incubation Projects Highlight Page](https://github.com/TBD54566975/developer.tbd.website/issues/746) is completed before starting on this task, as the button should point to the newly created page.

1. **File Location**: Update the button in `site/src/pages/community/index.js` on line 213.
  
2. **Modification**:
   - Change the `buttonUrl` value from its current link `../open-source/incubation` to the new `incubation-projects` page location `../community/incubation-project`.

```markdown
<Button
    heroText="Incubation Projects"
    buttonUrl="../community/incubation-project"
    buttonText="Discover More"
    bodyText="TBD Incubation projects are managed by community contributors."
    themeColor="cyan"
    primary
/>
```
## Picking Up This Issue:
- If you'd like to work on this, please comment "picking this up" below, and I'll assign the issue to you 

## Questions:
- If you need assistance or clarification, feel free to comment below.
- Feeling overwhelmed? Join our [`#hack-together` channel](https://discord.gg/tbd) and collaborate with a buddy.
- New to open-source? Check out our [Hacktober `#getting-started` channel](https://discord.gg/tbd).
- [Leaderboard](https://github.com/TBD54566975/developer.tbd.website/issues/721): Check your ranking after finishing this task.

### Resources:
- **Docusaurus Documentation**: Familiarize yourself with how Docusaurus works. Here's the [official documentation](https://docusaurus.io/docs).
- **Creating a Pull Request**: If you're new to GitHub and unsure how to create a pull request, follow this [step-by-step guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request).

Remember, communication is key! If you have any questions or face any challenges, we're here to help so please don't hesitate to reach out.

Good Luck! 🍁

**Comment by comeworkwith-me** [comment]
Hey Team TBD, picking this up!

**Comment by EbonyLouis** [comment]
@comeworkwith-me Your second issue yay! 🥳 Keep in mind that this issue can't be worked on until issue #746 is completed. Let me know if you'd still like to pick it up and I'll assign it to you. 

I'd also like to note that Hacktoberfest officially kicks off on **October 1st**. Contributions made before the event may not be eligible for the challenge. **However, feel free to start working on it, but I'd recommend holding off on submitting your PR until the event begins.** 

> to be eligible for Hacktoberfest's official prizes make sure you're registered, registration [opens September 26th.](https://hacktoberfest.com/)

**Comment by comeworkwith-me** [comment]
Yes, I'd still like to work on it @EbonyLouis 💯 🙂

**Comment by pateldivyesh1323** [comment]
@EbonyLouis picking this up

**Comment by rishabhpathak359** [comment]
@EbonyLouis picking this up

**Comment by Himanshu9901** [comment]
If this issue is not resolved yet, can I work on it ?

**Comment by comeworkwith-me** [comment]
This issued is assigned to me and being worked on @Himanshu9901 , thank you for double checking 💯

**Comment by aniketh-varma** [comment]
Hey @EbonyLouis @angiejones, can I pick this issue if it is idle?

**Comment by KhoiUna** [comment]
@EbonyLouis may I work on this if it's not resolved?

**Comment by EbonyLouis** [comment]
Hey @KhoiUna , @aniketh-varma this issue is being blocked by this issue: https://github.com/TBD54566975/developer.tbd.website/issues/746.

**Comment by KhoiUna** [comment]
> Hey @KhoiUna , @aniketh-varma this issue is being blocked by this issue: https://github.com/TBD54566975/developer.tbd.website/issues/746. 

Can I work on #746?
