### ISSUE TITLE
Add padding to the feedback widget

### ISSUE THREAD

**Issue by dayhaysoos** [TBD54566975/developer.tbd.website#748]
### Background: 
On mobile the styling of the feedback widget gets a little convoluted.

### Objective:
-  Add some more padding and margin, so that the words aren't hugging the borders 
-  The feedback widget is at the bottom of every page in our [docs](https://developer.tbd.website/docs/)

![file_720](https://github.com/TBD54566975/developer.tbd.website/assets/1852675/cf6c107c-15fb-4694-88ae-dbe73534bbf3)

## Picking Up This Issue:
- If you'd like to work on this, please comment "picking this up" below, and I'll assign the issue to you 

## Questions:
- If you need assistance or clarification, feel free to comment below.
- Feeling overwhelmed? Join our [`#hack-together` channel](https://discord.gg/tbd) and collaborate with a buddy.
- New to open-source? Check out our [Hacktober `#getting-started` channel](https://discord.gg/tbd).
- [Leaderboard](https://github.com/TBD54566975/developer.tbd.website/issues/721): Check your ranking after finishing this task.

### Resources:
- **Docusaurus Documentation**: Familiarize yourself with how Docusaurus works. Here's the [official documentation](https://docusaurus.io/docs).
- **Creating a Pull Request**: If you're new to GitHub and unsure how to create a pull request, follow this [step-by-step guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request).

Remember, communication is key! If you have any questions or face any challenges, we're here to help so please don't hesitate to reach out.

Good Luck! 🍁

**Comment by comeworkwith-me** [comment]
Hey Team TBD, picking this up!

**Comment by EbonyLouis** [comment]
@comeworkwith-me yayy! 

I'd like to note that Hacktoberfest officially kicks off on **October 1st**. Contributions made before the event may not be eligible for the challenge. However, feel free to start working on it, but I'd recommend holding off on submitting your PR until the event begins. 

> To be eligible for Hacktoberfest's official prizes make sure you're registered, registration [opens September 26th.](https://hacktoberfest.com/) 

Reach out if you need any help 🥳

**Comment by EbonyLouis** [comment]
@comeworkwith-me Hey there! It looks like another contributor has jumped in and made progress on this issue. Open source projects can be quite tricky in this way.

I understand you had this issue assigned, and I appreciate your commitment. I know you have some other issues assigned as well. So if you're looking for a replacement issue, we have some other good ones available. Feel free to let me know if you'd like assistance finding another one.

Thanks for wanting to contribute with us!

**Comment by Adityacodesinpython** [comment]
Hello Team TBD, picking this up!

**Comment by angiejones** [comment]
> Hey @EbonyLouis,
> 
> I'm confused, I picked this up for Octoberfest. I thought the issues were first come, first serve? I didn't know someone can come in and complete the issue you were assigned. I was actually waiting until October so this could count towards the event.

this was totally my fault. The user posted in our Discord that the work was already done, so I assigned it to them. I'm so very sorry for the mix up.

**Comment by angiejones** [comment]
> Hello Team TBD, picking this up!

Thank you but this has already been assigned.
