### ISSUE TITLE
Outdated twitter logo 

### ISSUE THREAD

**Issue by captain-Akshay** [TBD54566975/developer.tbd.website#753]
### Current State
![image](https://github.com/TBD54566975/developer.tbd.website/assets/59491379/f6924e4c-8d6c-472d-9a57-b7d90abc7ed0)

### Expected state
new twitter x logo 

it would be great if you could label it as hacktoberfest and assign it to me !
Thanks @EbonyLouis  @dayhaysoos

**Comment by adityaK87** [comment]
can I pick this issue.

**Comment by shailifadadu** [comment]
Hey!! I would also like to contribute to this issue. Can u assign me this??

**Comment by captain-Akshay** [comment]
@LynxSumit gonna raise it soon waiting for the event to start 😄

**Comment by lazyMonk1010** [comment]
hey i want to work on this isssue

**Comment by EbonyLouis** [comment]
@lazyMonk1010 Hey this issue has already been completed. We do have more open issues that might interest you. 

-[developer.tbd.website](https://github.com/TBD54566975/developer.tbd.website/issues?q=is%3Aopen+is%3Aissue+label%3Ahacktoberfest+no%3Aassignee)
-[web5-js](https://github.com/TBD54566975/web5-js/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) 
-[dwn-server](https://github.com/TBD54566975/dwn-server/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) 
-[dwn-sdk-js](https://github.com/TBD54566975/dwn-sdk-js/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee)
