### ISSUE TITLE
Alignment issue in the Header component

### ISSUE THREAD

**Issue by captain-Akshay** [TBD54566975/developer.tbd.website#759]
### Current state

![error](https://github.com/TBD54566975/developer.tbd.website/assets/59491379/c596e35c-6736-49ce-8399-61611b2e8692)

### Expected state

If this appears to be a legitimate issue, kindly categorize it under "hacktoberfest" and assign it to me for further attention. @EbonyLouis Thank you in advance!

**Comment by EbonyLouis** [comment]
@captain-Akshay Good find! I've assigned it to you 😄. 

I'd like to note that Hacktoberfest officially kicks off on **October 1st**. Contributions made before the event may not be eligible for the challenge. However, feel free to start working on it, but I'd recommend holding off on submitting your PR until the event begins. 

> To be eligible for Hacktoberfest's official prizes make sure you're registered, registration [is now OPEN.](https://hacktoberfest.com/auth) 

Reach out if you need any help 🥳

**Comment by EbonyLouis** [comment]
@LynxSumit Hey thank you for the enthusiasm, lets give the original contributor a chance to resolve this issue. We have other open `Hacktoberfest` tagged issues that you might find interesting. 
- [developer.tbd.website](https://github.com/TBD54566975/developer.tbd.website/issues?q=is%3Aopen+is%3Aissue+label%3Ahacktoberfest+no%3Aassignee)
- [web5-js](https://github.com/TBD54566975/web5-js/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22)
- [dwn-server](https://github.com/TBD54566975/dwn-server/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22)
- [dwn-sdk-js](https://github.com/TBD54566975/dwn-sdk-js/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee)

Also, we'll be adding more issues throughout the month of October, so there will be plenty of opportunities to jump in. If for any reason the current assignee can't proceed with this one, I'll definitely keep you both in mind and reach out. keep an eye on our `events-and-updates` channel in [discord](https://discord.gg/tbd). Thanks for spending Hacktoberfest with us! 🍁

**Comment by angiejones** [comment]
this bug was driving me crazy! thanks for looking into it
