### ISSUE TITLE
[DOC]: No documentation about running docker file for local development

### ISSUE THREAD

**Issue by captain-Akshay** [TBD54566975/developer.tbd.website#760]
The Problem:
Developers rely on Docker containers for local development to ensure consistency across environments, ease of deployment, and efficient collaboration. However, a common pain point in this process is the lack of proper documentation for Dockerfile setups. Without clear and concise documentation, developers face the following challenges:

If you consider it an legitimate issue then please assign it to me!

**Comment by angiejones** [comment]
Hi! We have instructions on how to run our site locally, which is the most effective way to develop and contribute. Docker is more for deploying in our infra, I would not expect anyone to deploy our website aside from us.

**Comment by captain-Akshay** [comment]
Oh you are absolutely correct but there is one more feature of using Docker in origination repo is that if any contributor face any version issue, installation issue or environment issue then fixing them would take a great deal of time !
That's why dockerfile come handy for local development @angiejones
