### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by captain-Akshay** [TBD54566975/developer.tbd.website#771]
there are few typo in the readme.md

![image](https://github.com/TBD54566975/developer.tbd.website/assets/59491379/13d36cfa-7b4c-4f2c-8e32-8c3e3f459868)

- "succesfully" should be "successfully."
- "imposter" should be "impostor."

# I would like to work on this one 
Thanks in advance 😅😅!

**Comment by captain-Akshay** [comment]
Thanks

**Comment by shailifadadu** [comment]
Hey!! I would like to solve the typos in your README. Can u assign this issue to me??

**Comment by lazyMonk1010** [comment]
hey i want to solve this issue , please do assign me this

**Comment by EbonyLouis** [comment]
Hey @lazyMonk1010 and @shailifadadu this issue has already been completed. However we have some other open issues that might interest you. 

-[developer.tbd.website](https://github.com/TBD54566975/developer.tbd.website/issues?q=is%3Aopen+is%3Aissue+label%3Ahacktoberfest+no%3Aassignee)
-[web5-js](https://github.com/TBD54566975/web5-js/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) 
-[dwn-server](https://github.com/TBD54566975/dwn-server/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) 
-[dwn-sdk-js](https://github.com/TBD54566975/dwn-sdk-js/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee)
