### ISSUE TITLE
Misplacement of arrow in the official website 

### ISSUE THREAD

**Issue by captain-Akshay** [TBD54566975/developer.tbd.website#772]
## Current State
Mobile version of website

![error_arrow](https://github.com/TBD54566975/developer.tbd.website/assets/59491379/55d0fe0d-8fbf-4c59-be9a-8a7b79226da1)

## Desired State

![fix_arrow](https://github.com/TBD54566975/developer.tbd.website/assets/59491379/460021c5-d9b4-48f6-b120-c7eb0faf8d63)

--------
# Please assign this one to me
Thanks in Advance!

**Comment by Adityacodesinpython** [comment]
Hello, Can I start working on this issue?

**Comment by angiejones** [comment]
> Hello, Can I start working on this issue?

yes, thank you!

**Comment by captain-Akshay** [comment]
@angiejones i wrote  assign it to me & i have actually worked the error 🥲

**Comment by angiejones** [comment]
> @angiejones i wrote assign it to me & i have actually worked the error out🥲

yes, so sorry! assigning to you now.

sorry about that @Adityacodesinpython

**Comment by captain-Akshay** [comment]
Thanks for such a quick response ☺️!

**Comment by philling1** [comment]
sorry I saw that you have had so many of your PR merged I am having issues having my PR merged I was told to remove a certain file from my PR "site/src/util/code-snippets-map.json" but don't know how to go about it and I have tried so many things and is not working.

**Comment by captain-Akshay** [comment]
@philling1 sorry to hear that.Message me on discord or twitter 
and do let me know where you gonna message coz notification is turned off 😅 😅

**Comment by philling1** [comment]
I was able to resolve the problem with the help of @angiejones but thank you anywhere for getting in touch

**Comment by DanAdewole** [comment]
I think this issue can be closed sinced it has been resolved already
