### ISSUE TITLE
Fix import statements on Web5 API Guide

### ISSUE THREAD

**Issue by angiejones** [TBD54566975/developer.tbd.website#774]
On the [Web5 API Reference Guide](https://developer.tbd.website/api/web5-js#import) home page, the CDN import statements are not correct:

<img width="840" alt="image" src="https://github.com/TBD54566975/developer.tbd.website/assets/15972783/e622bdd0-3531-48e1-8d46-0f8161cd84a2">

Those are the install statements. For Import, they should be:

> ```js
> import { Web5 } from 'https://unpkg.com/@web5/api@0.8.1/dist/browser.js';
> ```
> 
> or
> 
> ```js
> import { Web5 } from 'https://cdn.jsdelivr.net/npm/@web5/api@0.8.1/dist/browser.mjs'
> ```

Before picking up this issue, please note that it is not hardcoded in the doc. It needs to be fixed in the [SrcScript widget](https://github.com/TBD54566975/developer.tbd.website/blob/main/site/src/components/ScriptSrc.jsx) but don't break the Install instructions

**Comment by Chetax** [comment]
I would like to work on this, please assign it to me

**Comment by theavitw** [comment]
+1

**Comment by angiejones** [comment]
> I would like to work on this, please assign it to me

assigned. thank you!

**Comment by angiejones** [comment]
be careful not to break the Install instructions. And please don't remove the use of the version variable
https://github.com/Chetax/developer.tbd.website/commit/ea7b89506e51e4d1c7ddc7f7e38f8c8fd7662061

**Comment by sayanta2005** [comment]
Can I work on this issue?
