### ISSUE TITLE
No hover effect in the DeveloperDoc/Explore section

### ISSUE THREAD

**Issue by captain-Akshay** [TBD54566975/developer.tbd.website#776]
# Current State

The "Explore" section's cards ought to incorporate a hover effect to enhance user experience and increase visual appeal.
It's is not in sync like the other clickable component in the website.

[Screencast from 2023-10-01 20-09-03.webm](https://github.com/TBD54566975/developer.tbd.website/assets/59491379/07df0874-7b14-4661-95d2-6108593d6ada)

# Desired State

Addition of hover effect on the card 

### I would like to work on this one

**Comment by captain-Akshay** [comment]
i will pick this up!

**Comment by itsaman123** [comment]
hey @captain-Akshay , can you assign this issue to me? I would like to work with that issue.

**Comment by captain-Akshay** [comment]
@itsaman123, thank you for your interest and enthusiasm. I appreciate that you didn't attempt to submit a pull request without asking first 😅 😂. However, I've already fixed this particular issue. I hope you find many other open issues to work on, and please feel free to ask about them!

**Comment by philling1** [comment]
sorry has this been assigned to someone or can also work on it

**Comment by captain-Akshay** [comment]
@philling1 i appreciate the enthusiasm but i would have to say this is being resolved bu there are many open issue as well or create your own issue!!

**Comment by philling1** [comment]
ok thank you

**Comment by EbonyLouis** [comment]
Thank you @captain-Akshay.
@philling1 let me know if you need any help looking for another issue. I'll link some: 

-[developer.tbd.website](https://github.com/TBD54566975/developer.tbd.website/issues?q=is%3Aopen+is%3Aissue+label%3Ahacktoberfest+no%3Aassignee)
-[web5-js](https://github.com/TBD54566975/web5-js/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) 
-[dwn-server](https://github.com/TBD54566975/dwn-server/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) 
-[dwn-sdk-js](https://github.com/TBD54566975/dwn-sdk-js/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee)
