### ISSUE TITLE
Highlight line in Ascending Order snippet

### ISSUE THREAD

**Issue by angiejones** [TBD54566975/developer.tbd.website#779]
### Background:
Our code examples highlight the most relevant lines of the snippet. However, it's missing from this example in the [Query Records](https://developer.tbd.website/docs/web5/build/decentralized-web-nodes/query-from-dwn/#ascending-order) guide

<img width="853" alt="image" src="https://github.com/TBD54566975/developer.tbd.website/assets/15972783/737ced5a-4346-4ff6-9a88-2477f3fcf714">

### Objective:
Highlight this line:

```js
      dateSort: 'publishedAscending',
```

### Task Details:

Update `queryRecordsWithFilterAscending` function within [query-from-dwn.js](https://github.com/TBD54566975/developer.tbd.website/blob/main/site/code-snippets/web5/build/decentralized-web-nodes/query-from-dwn.js) file. Place the following code on the line above the line that should be highlighted:

```js
//highlight-next-line
``` 

## Picking Up This Issue:
- If you'd like to work on this, please comment "picking this up" below, and I'll assign the issue to you 

## Questions:
- If you need assistance or clarification, feel free to comment below.
- Feeling overwhelmed? Join our [`#hack-together` channel](https://discord.gg/tbd) and collaborate with a buddy.
- New to open-source? Check out our [Hacktober `#getting-started` channel](https://discord.gg/tbd).
- [Leaderboard](https://github.com/TBD54566975/developer.tbd.website/issues/721): Check your ranking after finishing this task.

### Resources:
- **Creating a Pull Request**: If you're new to GitHub and unsure how to create a pull request, follow this [step-by-step guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request).

Remember, communication is key! If you have any questions or face any challenges, we're here to help so please don't hesitate to reach out.

Good Luck! 🍁

**Comment by bkpecho** [comment]
picking this up
