### ISSUE TITLE
Typo in Docs[Glossary]

### ISSUE THREAD

**Issue by captain-Akshay** [TBD54566975/developer.tbd.website#781]
## Current State
- enabled should be enables.
- pesonal should be personal

![Screenshot from 2023-10-01 20-18-21](https://github.com/TBD54566975/developer.tbd.website/assets/59491379/85db05d7-c93c-4946-82eb-7623360cc198)
![Screenshot from 2023-10-01 20-17-42](https://github.com/TBD54566975/developer.tbd.website/assets/59491379/35177c46-819e-4a7f-a08f-37594fc1e0be)

i will like to work on fixing the issue :}

**Comment by ATREAY** [comment]
hey @captain-Akshay, can I work on this issue?

**Comment by captain-Akshay** [comment]
@ATREAY , thank you for your interest and enthusiasm. I appreciate that you didn't attempt to submit a pull request without asking first 😅 😂. However, I've already fixed this particular issue. I hope you find many other open issues to work on, and please feel free to ask about them!

**Comment by ATREAY** [comment]
Sure thing, @captain-Akshay! Just a quick request to close those issues you've already sorted out to keep things clear.

**Comment by captain-Akshay** [comment]
@ATREAY I'm currently awaiting the approval and merging of my pull request. Typically, once it's merged, the associated issue is promptly closed.
