### ISSUE TITLE
[Doc] Typo in Sync section 

### ISSUE THREAD

**Issue by captain-Akshay** [TBD54566975/developer.tbd.website#782]
### Typo:-
- environmnent should be environment 

![image](https://github.com/TBD54566975/developer.tbd.website/assets/59491379/74c38810-ba6c-4edf-9cb7-bc42a36a77f9)

--------------
i would like to work on this one!
thanks in advance!

**Comment by Developerayo** [comment]
Thanks @captain-Akshay! You can :)
