### ISSUE TITLE
[FEEDBACK]: I want to make changes in your footer, 

### ISSUE THREAD

**Issue by lazyMonk1010** [TBD54566975/developer.tbd.website#793]
### Type

Suggestion to Improve

### Feedback

Tell us what you're seeing!
I Want to change and update your footer, as its not syncing with the official website , so i want to update that , and also need to update twitter logo. and add different section for that .

### Screenshots

Paste relevant images or screenshots here

**Comment by EbonyLouis** [comment]
@lazyMonk1010 can you share photos to help me understand the changes you would like to make?
