### ISSUE TITLE
Hover state on the feedback button of docs doesn't fully match with the theme.

### ISSUE THREAD

**Issue by Aytida-dev** [TBD54566975/developer.tbd.website#794]
### Current state
The Feedback buttons of the Docs section when hovered doesn't change the text yellow as per the theme 
[Screencast from 2023-10-03 20-03-42.webm](https://github.com/TBD54566975/developer.tbd.website/assets/92716638/2f8bd40c-c68c-4637-aa7f-8cf4e98a1a29)

### Desired state 
Addition of hover effect on the text of the buttons.

### I would like to work on this issue.

**Comment by AnishTiwari16** [comment]
@Aytida-dev please assign this issue
