### ISSUE TITLE
Bug: Header Links are merging into each other 

### ISSUE THREAD

**Issue by pateldivyesh1323** [TBD54566975/developer.tbd.website#798]
## Screenshot

![image](https://github.com/TBD54566975/developer.tbd.website/assets/109150688/4fe79de8-6dfc-4992-9e0d-c1182bfa4859)

- If this is counted as a valid issue, I would like to work on this as a hacktoberfest participant

**Comment by GouravKumar13** [comment]
@pateldivyesh1323  can you please assign this to me

**Comment by parag477** [comment]
Can you please assign this issue to me?

**Comment by pateldivyesh1323** [comment]
Closing this as this looks fixed on latest pull.
![image](https://github.com/TBD54566975/developer.tbd.website/assets/109150688/ac55a385-16fc-4fa6-b1fa-d1b4880d338e)
