### ISSUE TITLE
Document infra for Feedback Widget

### ISSUE THREAD

**Issue by leordev** [TBD54566975/developer.tbd.website#799]
- How are we monitoring?
- What alerts do we have?
- How Devrels should consume the data?
- How to deploy changes?

**Comment by Lymah123** [comment]
Can I work on the issue?

**Comment by leordev** [comment]
@Lymah123 thanks for the interest but this is more of a documentation of our internal infra systems 😞

**Comment by Lymah123** [comment]
Oh! I see. 

Thank you @leordev!

**Comment by leordev** [comment]
@ALRubinger started this internal draft here: https://github.com/tbdeng/tbd-sites-helm/pull/2/files#

**Comment by leordev** [comment]
Marking this issue as done since we finished the first iteration and created the follow up items in [our backlog](https://github.com/orgs/TBD54566975/projects/26) to keep track of what is needed to be added to our infra.
