### ISSUE TITLE
Fix error statuses on feedback-server-app

### ISSUE THREAD

**Issue by leordev** [TBD54566975/developer.tbd.website#801]
Right now we can see a bunch of errors in datadog, but they should not be server errors. 

eg: invalid csrf token, rejected CORS

**Comment by Developerayo** [comment]
@leordev can you help share the log?

**Comment by leordev** [comment]
Sure, a couple of examples:

cors
![image](https://github.com/TBD54566975/developer.tbd.website/assets/6147142/81b6fcbd-5089-4429-90b9-b44587b42cc6)

invalid csrf
![image](https://github.com/TBD54566975/developer.tbd.website/assets/6147142/9c129f26-abba-4119-b979-39003ae80694)


And BTW, this is what I mean by a single log creating multiple entries in datadog in this issue #800 -- in the above images you can see a single errors generating multiple logs.

**Comment by leordev** [comment]
I just checked the status of these errors. 

Invalid CSRF is throwing correctly (ForbiddenError = 403).

Invalid CORS is throwing 500. Only this one needs to be fixed. (working on it)
