### ISSUE TITLE
[USE CASE]: change twitter old logo to new one

### ISSUE THREAD

**Issue by Rahullkumr** [TBD54566975/developer.tbd.website#805]
### Developer Value Added

It is good to use new logo of the twitter website.

### Use Case

design new icon in yellow color and use it to replace the old icon.

**Comment by ALRubinger** [comment]
Thanks @Rahullkumr - did you mean to close this?

@angiejones - WDYT?

**Comment by Rahullkumr** [comment]
Someone has already sent the PR for `changing twitter's old icon` and it got merged.
#789

That's why I closed this issue

@ALRubinger Thanks for replying...
