### ISSUE TITLE
Update Links due to navigation issue for Projects Page

### ISSUE THREAD

**Issue by Smartmind12** [TBD54566975/developer.tbd.website#807]
Currently the buttons on the community page take you to the desired page but to the middle or bottom of the desired page and never to the top of the desired page as shown in the screenshots. This arises due to error in navigation.

Kindly request you to assign me this issue so that i can rectify the same.

![Screenshot 2023-10-04 at 3 33 47 PM](https://github.com/TBD54566975/developer.tbd.website/assets/91927689/c62aa2f9-9e5b-432d-97c7-6aba90558cf8)
![Screenshot 2023-10-04 at 3 34 50 PM](https://github.com/TBD54566975/developer.tbd.website/assets/91927689/b77cffc2-6cb7-49d6-aafe-77270c209b22)

**Comment by unkletayo** [comment]
@EbonyLouis I'd love to work on this

**Comment by Smartmind12** [comment]
> @EbonyLouis I'd love to work on this

Hey @unkletayo I am currently i=on this issue and would close the same during the weekend...so kindly take up and other open issue!

**Comment by angiejones** [comment]
this has been fixed
