### ISSUE TITLE
Update Links due to navigation issue for Open Source Page

### ISSUE THREAD

**Issue by Smartmind12** [TBD54566975/developer.tbd.website#808]
Currently the buttons on the community page take you to the desired page but to the middle or bottom of the desired page and never to the top of the desired page as shown in the screenshots. This arises due to error in navigation.

Kindly request you to assign me this issue so that i can rectify the same.

![Screenshot 2023-10-04 at 3 37 11 PM](https://github.com/TBD54566975/developer.tbd.website/assets/91927689/c107ede9-149a-481f-bbcc-1b685751fdb8)
![Screenshot 2023-10-04 at 3 37 36 PM](https://github.com/TBD54566975/developer.tbd.website/assets/91927689/85267d57-f751-4136-9674-cfa42f87acf5)

**Comment by EbonyLouis** [comment]
@Smartmind12 thank you, I hear you I'm not sure if you saw my comment on your PRs we want to avoid changing the URL. Can you see if Scroll Restoration solves the problem instead?

**Comment by Smartmind12** [comment]
> @Smartmind12 thank you, I hear you I'm not sure if you saw my comment on your PRs we want to avoid changing the URL. Can you see if Scroll Restoration solves the problem instead?

Sure @EbonyLouis I understand and i will try to do the needful!

**Comment by EbonyLouis** [comment]
@Smartmind12 thank you so much, I really appreciate it. Let me know if you need any help.

**Comment by Smartmind12** [comment]
> @Smartmind12 thank you so much, I really appreciate it. Let me know if you need any help.

@EbonyLouis I have done the needful and now the links open on the same tab and at the top of the page so scrolling issue is mitigated.

**Comment by Smartmind12** [comment]
Closed as solved by #836
