### ISSUE TITLE
New X(twitter) logo on the home page

### ISSUE THREAD

**Issue by Pratham271** [TBD54566975/developer.tbd.website#815]
<img width="1710" alt="Screenshot 2023-10-05 at 8 03 39 AM" src="https://github.com/TBD54566975/developer.tbd.website/assets/83640434/2e5c91dc-6fac-49c1-8895-1fdeb4f14eef">
The X(twitter) logo on the homepage is still the same we should update it there as well 
Can I work on this issue

**Comment by angiejones** [comment]
this has been fixed
