### ISSUE TITLE
New X(twitter) logo on connect page

### ISSUE THREAD

**Issue by Pratham271** [TBD54566975/developer.tbd.website#816]
<img width="1710" alt="Screenshot 2023-10-05 at 8 11 30 AM" src="https://github.com/TBD54566975/developer.tbd.website/assets/83640434/cfe7378d-1f85-45ec-bc14-10fe69643101">
The connect page also has the old X(twitter) logo which needs to be updated assign this task to me

**Comment by angiejones** [comment]
sorry this page is not a part of this open source project
