### ISSUE TITLE
[DOCS] Typo in blogs

### ISSUE THREAD

**Issue by captain-Akshay** [TBD54566975/developer.tbd.website#818]
### Typo in Blogs:-

- "Fortunately, the presentations of projects was recorded." should be "Fortunately, the presentations of the projects were recorded".
- "possibly brand" should be "possibly a brand"

### ScreenShots:-
![Screenshot from 2023-10-04 18-01-38](https://github.com/TBD54566975/developer.tbd.website/assets/59491379/dd0e6553-f999-42bd-b597-d00422c1edcb)

-------------------------------

![Screenshot from 2023-10-04 18-12-36](https://github.com/TBD54566975/developer.tbd.website/assets/59491379/aa49771e-219d-462e-8316-e1f54729d164)

**Comment by captain-Akshay** [comment]
I would love to work on this @EbonyLouis !

**Comment by EbonyLouis** [comment]
@captain-Akshay Thank you! 😊
