### ISSUE TITLE
Update 'Videos' Explore Card URL

### ISSUE THREAD

**Issue by EbonyLouis** [TBD54566975/developer.tbd.website#821]
### Background:
On our `/docs` page, there's an explore card which currently points to Vimeo. For better content alignment we want it to direct users to our YouTube channel instead.

### Task Details:
- Locate the 'Videos' explore card on the `/docs` page.
- Update the current Vimeo URL with our YouTube channel link: [https://www.youtube.com/@TBD54566975](https://www.youtube.com/@TBD54566975).
- Ensure the link is functional and correctly redirects to our YouTube channel.

## Picking Up This Issue:
- If you'd like to work on this, please comment "picking this up" below, and I'll assign the issue to you.

## Questions:
- If you need assistance or clarification, feel free to comment below.
- Feeling overwhelmed? Join our [`#hack-together` channel](https://discord.gg/tbd) and collaborate with a buddy.
- New to open-source? Check out our [Hacktober `#getting-started` channel](https://discord.gg/tbd).
- [Leaderboard](https://github.com/TBD54566975/developer.tbd.website/issues/721): Check your ranking after finishing this task.

### Resources:
- **Creating a Pull Request**: If you're new to GitHub and unsure how to create a pull request, follow this [step-by-step guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request).

Remember, communication is key! If you have any questions or face any challenges, we're here to help so please don't hesitate to reach out.

Good Luck! 🍁

**Comment by AniruddhaGawali** [comment]
i can help can you assign it to me

**Comment by Pratham271** [comment]
Picking this up

**Comment by philling1** [comment]
picking this up

**Comment by Petsamuel** [comment]
picking this up

**Comment by Himanshu9901** [comment]
Hey I tried to solve the issue and created a pull request, please assign it to me and check it.
