### ISSUE TITLE
[DOC]: Missing full-stop in the doc area

### ISSUE THREAD

**Issue by philling1** [TBD54566975/developer.tbd.website#826]
### Type

Docs Bug Report

### Feedback

I noticed that there is a missing full stop at the end of the message under the SSI Service API. Could you please consider me  adding it for proper punctuation and completeness?

![Screenshot 2023-2](https://github.com/TBD54566975/developer.tbd.website/assets/90944819/8131d4af-64f1-490f-9841-45b8e34dc7e7)
 
I am thinking that there should be a full-stop after Verifiable Credentials

### Screenshots

Paste relevant images or screenshots here

### developer.tbd.website URL

DOCS page

### Browser

Microsoft Edge

**Comment by philling1** [comment]
please can I work on it.

**Comment by EbonyLouis** [comment]
@philling1 🥳 it's been assigned to you, another great catch.

**Comment by philling1** [comment]
Ok thank you, let me get on with it.

**Comment by philling1** [comment]
I have opened a PR for this changes #826 and I have remove the Unwanted file from my previous PR on this issue. Please help me to review it and see if there is any further changes to my PR.

**Comment by philling1** [comment]
I don't know how I should remove this file  "site/src/util/code-snippets-map.json" from my PR could you please direct me on how to do that.
