### ISSUE TITLE
No hover effect on Create Credentials left sidebar

### ISSUE THREAD

**Issue by philling1** [TBD54566975/developer.tbd.website#828]
### Type

Docs Bug Report

### Feedback

There is no hover effect on the first four sidebar links of the Create Credentials sidebar under the SSI SERVICE Right side bar and the text colors are different from other sidebar links text.

![Create Credentials _ TBD and 10 more pages - Personal - Microsoft_ Edge 2023-10-06 10-10-59 (1)](https://github.com/TBD54566975/developer.tbd.website/assets/90944819/73c59bf7-c9e9-411a-aee6-4e123d79f36a)
  
I don't know if it was intentionally done but if not I would like to work on it and help make it look like the others

### Screenshots

Paste relevant images or screenshots here

### developer.tbd.website URL

DOCS page

### Browser

Microsoft Edge

**Comment by philling1** [comment]
Please can also work on this.

**Comment by EbonyLouis** [comment]
@philling1 Great catch! Thank you for working on this!

**Comment by philling1** [comment]
Ok thank you

**Comment by philling1** [comment]
I have opened a PR for this changes #848. Please help me to review it and see if there is any further changes to my PR.

**Comment by philling1** [comment]
I don't know how I should remove this file  "site/src/util/code-snippets-map.json" from my PR could you please direct me on how to do that.

**Comment by angiejones** [comment]
> I don't know how I should remove this file "site/src/util/code-snippets-map.json" from my PR could you please direct me on how to do that.


1. **Locate the Branch:** Make sure you are on the branch associated with your pull request. Use the `git checkout <branch_name>` command to switch to that branch.

2. **Use `git checkout` to Restore the File:** Run the following command to restore the file to its previous state:

   ```
   git checkout path/to/file
   ```

   Replace `path/to/file` with the actual path to the file you want to restore.

3. **Commit the Restoration:** After running the `git checkout` command, the file will be restored to its previous state. You can then commit this change using `git commit`:

   ```
   git commit -m "Restore <file_name> to previous state"
   ```

4. **Push the Changes:** Finally, push the changes to the branch on your GitHub fork or repository with:

   ```
   git push origin <branch_name>
   ```

**Comment by philling1** [comment]
ok thank you for the quick response let me try it now.

**Comment by philling1** [comment]
I have done as you said but the file is still showing when I created the PR for the issue

**Comment by philling1** [comment]
I have created a PR where I think I have resolved this issue could help to review it and merge it

**Comment by EbonyLouis** [comment]
@philling1 do you have a PR open for this issue?
