### ISSUE TITLE
[FEEDBACK]: Improving the footer

### ISSUE THREAD

**Issue by parag477** [TBD54566975/developer.tbd.website#829]
### Type

Suggestion to Improve

### Feedback

I am seeing that their is so much space between the footer and its components. So I want to make it even more prettier. That's why I am opening this issue.

### Screenshots

![Capture](https://github.com/TBD54566975/developer.tbd.website/assets/60110529/ae65f600-e74b-4874-8301-b374e40571b0)

### developer.tbd.website URL

https://developer.tbd.website/

### Browser

Chrome

**Comment by angiejones** [comment]
@parag477 is there a mockup of what you have in mind?

**Comment by parag477** [comment]
I don't have any mockup rn

**Comment by angiejones** [comment]
ok I don't see any issues with the spacing. not sure what you had in mind for improvement
