### ISSUE TITLE
Capitalization of letters for uniformity

### ISSUE THREAD

**Issue by Smartmind12** [TBD54566975/developer.tbd.website#832]
The starting letter of each sentence should be a capital letter so correction of the same is required. 
Kindly assign this issue to me to rectify the same.
![Screenshot 2023-10-06 at 11 09 23 PM](https://github.com/TBD54566975/developer.tbd.website/assets/91927689/870dcd8f-fbce-4521-9c96-98f8fb42ab3e)

**Comment by angiejones** [comment]
They aren't complete sentences and intentionally begin with lowercase letters

**Comment by Smartmind12** [comment]
> They aren't complete sentences and intentionally begin with lowercase letters

Hey @angiejones I believe these are complete sentences as they explain the terms and these sentences also have a full stop at the end indicating them to be a proper sentence. So either capitalization of letters is required or full stops need to be removed from the end of the lines.

**Comment by Smartmind12** [comment]
> > They aren't complete sentences and intentionally begin with lowercase letters
> 
> Hey @angiejones I believe these are complete sentences as they explain the terms and these sentences also have a full stop at the end indicating them to be a proper sentence. So either capitalization of letters is required or full stops need to be removed from the end of the lines.

So kindly let me know which is correct so that the needful is done.

**Comment by Smartmind12** [comment]
> > They aren't complete sentences and intentionally begin with lowercase letters
> 
> Hey @angiejones I believe these are complete sentences as they explain the terms and these sentences also have a full stop at the end indicating them to be a proper sentence. So either capitalization of letters is required or full stops need to be removed from the end of the lines. As seen below Capitalization and full-stops have been used.
> 
> ![Screenshot 2023-10-07 at 8 19 35 AM](https://user-images.githubusercontent.com/91927689/273358719-6b97c173-f3e6-4962-a258-79659b69efdf.png)
> 
> @angiejones Kindly let me know your thoughts so that the needful change can be implemented.

@angiejones Any updates on the above suggested solution?
