### ISSUE TITLE
[DOC]: Missing full-stop in the methods area

### ISSUE THREAD

**Issue by Smartmind12** [TBD54566975/developer.tbd.website#835]
At multiple instances across the web5-js docs and pages, I noticed that there is a missing full stop at the end of the message under the create(request) as done for the read(request) and other methods on the same page. Could you please consider me adding it for proper punctuation and completeness?

![Screenshot 2023-10-07 at 7 57 19 AM](https://github.com/TBD54566975/developer.tbd.website/assets/91927689/63896a44-ceb1-41dc-b055-07414b9b4058)
![Screenshot 2023-10-07 at 7 57 35 AM](https://github.com/TBD54566975/developer.tbd.website/assets/91927689/7edee1ea-92ff-4238-ada7-6374f41b12ec)

**Comment by captain-Akshay** [comment]
picking this up!

**Comment by Smartmind12** [comment]
> picking this up!

@captain-Akshay I am waiting for them to assign the issue s kindly work on another free issues!

**Comment by angiejones** [comment]
we'd like it without the full stops as they are phrases and not complete sentences. if anything, you can remove the full stop  for `read()`. however, keep in mind that the Hacktoberfest organizers consider these sorts of PRs [low quality](https://hacktoberfest.com/participation/) and may not include it in their program

**Comment by Smartmind12** [comment]
Hey @angiejones I know and completely understand as even i dont want this issue to be  part of hacktoberfest. I have already added good quality PRs for other open issues!
