### ISSUE TITLE
Typo in Web5 component 

### ISSUE THREAD

**Issue by Manish-KY** [TBD54566975/developer.tbd.website#838]
link :- https://developer.tbd.website/projects/web5/#components
### Typo 
full stop is missing in this two sections!

![image](https://github.com/TBD54566975/developer.tbd.website/assets/109498113/fdb23b2b-44f1-4120-a4bb-821f759c14a0)
------------------------------------------
![image](https://github.com/TBD54566975/developer.tbd.website/assets/109498113/3f5d4960-9764-4a16-8478-b66855bac6cb)

please assign this one to me

**Comment by Smartmind12** [comment]
Please note as @angiejones has mentioned earlier that no sentences in the hero-cards require a full stop since they are not full sentences.

**Comment by Manish-KY** [comment]
![image](https://github.com/TBD54566975/developer.tbd.website/assets/109498113/788f3024-36f8-4bef-b422-5ace8e80768c)
Other cards @angiejones

**Comment by Manish-KY** [comment]
i think the last one is not a full sentence so i can avoid the full stop there but the first one is !

**Comment by angiejones** [comment]
you can remove the full stops from all that have them
