### ISSUE TITLE
[DOC]: Typo in community Section 

### ISSUE THREAD

**Issue by captain-Akshay** [TBD54566975/developer.tbd.website#839]
### Full Stop missing in the community section!

![image](https://github.com/TBD54566975/developer.tbd.website/assets/59491379/6774046d-14b7-4ca0-ae22-078aeb147fde)
-------------------------------------------------------
![image](https://github.com/TBD54566975/developer.tbd.website/assets/59491379/4608f923-cef9-415b-89e9-7b6fb6a60af2)

i would like to work on this one !
@EbonyLouis  @angiejones

**Comment by Smartmind12** [comment]
Please note as @angiejones has mentioned earlier that no sentences in the hero-cards require a full stop since they are not full sentences.
