### ISSUE TITLE
[DOCs]: Full stop missing in the project seciton

### ISSUE THREAD

**Issue by captain-Akshay** [TBD54566975/developer.tbd.website#840]
#### Full stop missing 
Link:- https://developer.tbd.website/projects

![image](https://github.com/TBD54566975/developer.tbd.website/assets/59491379/d1dd0f6b-cd86-45a8-b380-4a4772d78540)

i would like to work on this one @EbonyLouis & @angiejones

**Comment by Smartmind12** [comment]
Please note as @angiejones has mentioned earlier that no sentences in the hero-cards require a full stop since they are not full sentences.
