### ISSUE TITLE
Uniformity by Updating colour of the buttons

### ISSUE THREAD

**Issue by Smartmind12** [TBD54566975/developer.tbd.website#841]
Across the website all buttons have a background colour of cyan however in 3 cases purple background has been observed as shown in the screenshots.
Kindly assign this to me so that i can bring uniformity across the website by updating colour scheme of the button to cyan.
![Screenshot 2023-10-07 at 6 48 05 PM](https://github.com/TBD54566975/developer.tbd.website/assets/91927689/7628758d-36b7-4032-96a5-60bf8a4bea44)
![Screenshot 2023-10-07 at 6 49 22 PM](https://github.com/TBD54566975/developer.tbd.website/assets/91927689/b2f9cc13-1470-4de7-8c50-6740331a8a8a)

**Comment by captain-Akshay** [comment]
@Smartmind12 you are right but i think the they have 3 colors scheme as there home page consist of cyan,yellow and purple to make it funky😅

**Comment by Smartmind12** [comment]
> @Smartmind12 you are right but i think the they have 3 colors scheme as there home page consist of cyan,yellow and purple to make it funky😅

However if you see all other buttons in all pages are cyan so that is not what was targeted to make funkyness i believe😂

**Comment by angiejones** [comment]
we did intentionally mix up the colors here to make the page more colorful 😊

**Comment by Smartmind12** [comment]
> we did intentionally mix up the colors here to make the page more colorful 😊

So @angiejones would you like me to add the purple colour to other buttons as well on other pages so that one button is cyan and the other is purple?!

**Comment by Smartmind12** [comment]
> > we did intentionally mix up the colors here to make the page more colorful 😊
> 
> So @angiejones would you like me to add the purple colour to other buttons as well on other pages so that one button is cyan and the other is purple?!

Hey @angiejones Is the above solution feasible for the other pages?? Any updates on the same?
