### ISSUE TITLE
typo in Web5js document

### ISSUE THREAD

**Issue by captain-Akshay** [TBD54566975/developer.tbd.website#842]
### Multiple typos in the sentence 

Link-https://developer.tbd.website/api/web5-js/

, used after bracket 
no full-stop at the end
"e.g." should be "e.g.,"

![image](https://github.com/TBD54566975/developer.tbd.website/assets/59491379/c08431c3-10f2-4a7b-a3d7-430301bda945)

**Comment by Smartmind12** [comment]
Hey @captain-Akshay Please note for your pt.2 adding of a fullstop i have already made an issue (#835)  regarding full-stops in the methods area for all pages under web5-js...however you are good to go for pt1 and pt3!

**Comment by captain-Akshay** [comment]
@Smartmind12 bro you changed your message and they can all see that so inappropriate. Your's was on Records page only was been clear in the first commit message but after my PR you changed it to multiple that's just lame and unprofessional!! Other wise i wouldn't have raised a issue!
@EbonyLouis

**Comment by Smartmind12** [comment]
> @Smartmind12 bro you changed your message and they can all see that so inappropriate. Your's was on Records page only & was been clear in the first commit message but after my issue you changed it to multiple that's just lame and unprofessional!! Other wise i wouldn't have raised a issue! @EbonyLouis

Mate first of all i had made the issue 11 hours ago and since the issue is observed on multiple instances across the web5 page and 5 sub pages so i changed it  to reduce it to only 1 issue and 1 PR instead of future multiple small issues like these. Secondly what i did was very professional to reduce such spamy instances of creating issues and PR just for full-stops. So please mind keep that in mind going forward!

**Comment by captain-Akshay** [comment]
> > @Smartmind12 bro you changed your message and they can all see that so inappropriate. Your's was on Records page only & was been clear in the first commit message but after my issue you changed it to multiple that's just lame and unprofessional!! Other wise i wouldn't have raised a issue! @EbonyLouis
> 
> Mate first of all i had made the issue 11 hours ago and since the issue is observed on multiple instances across the web5 page and 5 sub pages so i changed it to reduce it to only 1 issue and 1 PR instead of future multiple small issues like these. Secondly what i did was very professional to reduce such spamy instances of creating issues and PR just for full-stops for every single page. So please mind keep that in mind going forward!

I don't want to argue here
Actually yours was Just 'records page' coz you used 'is' everywhere which means singular and mine is about Web5 page document as a whole point one instance,
and changing it after my issue was raised is unprofessional buddy.And it's there call and they can see the changes you made to your issue.

**Comment by Smartmind12** [comment]
@captain-Akshay I too dont want to argue but my point was to reduce the number of issue pertaining to full stops. So if you want you can go ahead with the web5 page and i will do it on  rest of the pages!

**Comment by angiejones** [comment]
thank you but we'd like to keep the sentence as is
