### ISSUE TITLE
Adding dropdown in the Contribution Guide

### ISSUE THREAD

**Issue by Smartmind12** [TBD54566975/developer.tbd.website#843]
There is an alignment issue on the right hand-side navigation bar for the contribution page as seen in the screenshot below.

![Screenshot 2023-10-07 at 8 29 58 PM](https://github.com/TBD54566975/developer.tbd.website/assets/91927689/240aa73e-58c9-43b3-b100-3976f4e6fb70)

Kindly assign this issue to me so that i can rectify this problem.

**Comment by Smartmind12** [comment]
I just realized the above (Caveats for code snippets) is a sub part of the Contributing Code snippets so adding a drop down would make it easier to recognize.

**Comment by angiejones** [comment]
hi, this is consistent with the rest of the site. every page with a right menu displays it this way
