### ISSUE TITLE
[DOCS]: Issue in the Next Step section of various pages

### ISSUE THREAD

**Issue by captain-Akshay** [TBD54566975/developer.tbd.website#844]
there are few places in the docs where full-stop is given or bullet point is missed 
![image](https://github.com/TBD54566975/developer.tbd.website/assets/59491379/71079877-cd99-4eb2-9719-f047afa6b052)
![Screenshot from 2023-10-08 07-31-09](https://github.com/TBD54566975/developer.tbd.website/assets/59491379/80a57abe-c8e1-49cc-9899-c78ca0dba52e)
![Screenshot from 2023-10-08 07-31-18](https://github.com/TBD54566975/developer.tbd.website/assets/59491379/82bbf4e6-097a-427e-9fc9-032e31c45caa)

I would like to fix it all in all this pages:-

**Comment by CBID2** [comment]
Hi @captain-Akshay! :) I'm CBID2, and heard about how awesome this project's docs is through @blackgirlbytes. Can you assign this issue to me please? :)
