### ISSUE TITLE
[DOC]: Typo in Docs page under SSI Service Verifiable Presentations

### ISSUE THREAD

**Issue by philling1** [TBD54566975/developer.tbd.website#851]
### Type

Docs Bug Report

### Feedback

I would like to report an issue regarding an error in the text: 'Simliar to credential issuance under the SSI Service page of Verifiable Presentations.

![tbd3](https://github.com/TBD54566975/developer.tbd.website/assets/90944819/36baf1c4-e787-4d63-ad15-0e792d240a65)

The word 'Simliar' should be corrected to 'Similar, and I would like to correct it.

### Screenshots

Paste relevant images or screenshots here

### developer.tbd.website URL

DOCS page

### Browser

Microsoft Edge

**Comment by philling1** [comment]
Please I would also like to work on this

**Comment by Lymah123** [comment]
Has anyone started working on this?

**Comment by philling1** [comment]
yes I am already working on it

**Comment by EbonyLouis** [comment]
Hi @philling1 as I mentioned on your last PR this kind of contribution is something that you can work on but it won't be counted as a successfully merged PR for Hacktoberfest based on their[ guidelines](https://hacktoberfest.com/participation/#spam).

**Comment by philling1** [comment]
ohh woww ok what about the one of fixing the hover effect on the create credentials sidebar that a PR on that you haven't review

**Comment by EbonyLouis** [comment]
@philling1 yes that one will count! I merged your last typo PR and put a `hacktoberfest-accepted` label on it since you already completed it. However going forward I won't be able to for just typo changes, my apologies I wasn't aware until now.

**Comment by philling1** [comment]
Ok thank you, But what I am more worried about is the error this "site/src/util/code-snippets-map.json" file is going to give me next when I create a PR for this issue and my head will start spinning.

**Comment by philling1** [comment]
I have created a PR for this
