### ISSUE TITLE
Typo in SSI Project section

### ISSUE THREAD

**Issue by captain-Akshay** [TBD54566975/developer.tbd.website#860]
Similar #838 
Full stop should be removed from this section given below .

![image](https://github.com/TBD54566975/developer.tbd.website/assets/59491379/b014e57c-1128-4155-833f-9c5372e8c6dd)

Full Stop to be removed as hero box are not full sentences!

![image](https://github.com/TBD54566975/developer.tbd.website/assets/59491379/6f8462f2-0b42-4eca-828e-03e11b708b51)

**Comment by captain-Akshay** [comment]
the Tbdex section dont have full stop in this section
![image](https://github.com/TBD54566975/developer.tbd.website/assets/59491379/506659ed-1f16-43ff-bd4b-2ac1e377261a)

**Comment by captain-Akshay** [comment]
i would like to work on this one

**Comment by Smartmind12** [comment]
@captain-Akshay Since these are low quality issue please merge (#860 #863 and #862) all the period related issues into 1 issue and then pull a single PR and not multiple PRs.

**Comment by captain-Akshay** [comment]
@Smartmind12 the only reason to do this and so should as well because it's highly recommended every other org that when we are working on one file we should keep one branch .. and if you know pull request very well then you would know that from one branch you can push one pull request and it's also help if i mess up any file as it's becomes easier to track!

**Comment by Smartmind12** [comment]
> @Smartmind12 the only reason to do this and so should as well because it's highly recommended every other org that when we are working on one file we should keep one branch .. and if you know pull request very well then you would know that from one branch you can push one pull request and it's also help if i mess up any file as it's becomes easier to track!

Hey @captain-Akshay every organization does that when you are making changes in the core code of the repo. They do not do it for trivial changes like capitalization or spell error or punctuation since these changes do not have impact when seen in the broader picture. Hence all orgs recommend to cut down the trivial issues in 1 pr and if u know about a pr the u would know u can make multiple commits and it also helps maintainers to track better than having different PRs for punctuation and i hope @angiejones will agree to this too!

**Comment by captain-Akshay** [comment]
Alright if she recommends to that way then all good but she didn't had any issue earlier when I changes various typos in different pages ..

**Comment by captain-Akshay** [comment]
And the core code of this website is there text content and data format @Smartmind12 that's why there are so many typo issues .. that's why making different pr for different file make sense.

**Comment by angiejones** [comment]
please address in #863
