### ISSUE TITLE
Typo in WEB5 project section

### ISSUE THREAD

**Issue by captain-Akshay** [TBD54566975/developer.tbd.website#863]
similar to #838 
I think full stop should not be there in that section as well !

![image](https://github.com/TBD54566975/developer.tbd.website/assets/59491379/82333a61-8ed8-4ac8-8902-a95a3886d3a3)

## It should be like this:-
![image](https://github.com/TBD54566975/developer.tbd.website/assets/59491379/c55e7620-474c-4ab2-914f-edd46897a5b8)

**Comment by leordev** [comment]
Hey @captain-Akshay just checking in! 😊 Do you need any help with this one?

**Comment by aniketh-varma** [comment]
Hi @angiejones @leordev, can I work on this issue, if it has not been addressed yet?

**Comment by captain-Akshay** [comment]
Sorry to say @aniketh-varma it's already been fixed !
