### ISSUE TITLE
Change of Name

### ISSUE THREAD

**Issue by Pratham271** [TBD54566975/developer.tbd.website#864]
<img width="1710" alt="Screenshot 2023-10-11 at 9 00 05 AM" src="https://github.com/TBD54566975/developer.tbd.website/assets/83640434/e63ecaa5-0b0d-4af7-ad84-d6c6fb8ad09e">
We are still using twitter but it should be changed to X or X previously known twitter. I would like to work on this one

**Comment by angiejones** [comment]
please change it to `X (fka Twitter)`

**Comment by aniketh-varma** [comment]
Hey @angiejones, I see this issue has been idle for a couple of days. Can I pick this up?

**Comment by leordev** [comment]
@aniketh-varma thanks for offering your help! Sure thing go for it, I'm assigning it to you!

**Comment by Pratham271** [comment]
This one is already completed I have merged the pull request for this one

**Comment by leordev** [comment]
@Pratham271 oh, I did not know. Can you please share the PR with me?
