### ISSUE TITLE
Proper Indentation 

### ISSUE THREAD

**Issue by Pratham271** [TBD54566975/developer.tbd.website#865]
<img width="246" alt="Screenshot 2023-10-11 at 9 02 22 AM" src="https://github.com/TBD54566975/developer.tbd.website/assets/83640434/04b6bae9-1c74-41b5-b678-4872335ebcb2">
proper indentation is required in the contribution section. I would like to work on this one too

**Comment by Smartmind12** [comment]
Hey Pratham is already closed since the identation for submodules is constant for all the other pages as well and its a repeat of #843 so kindly close this issue!
