### ISSUE TITLE
Capitalize Word

### ISSUE THREAD

**Issue by Pratham271** [TBD54566975/developer.tbd.website#866]
<img width="855" alt="Screenshot 2023-10-11 at 9 31 44 AM" src="https://github.com/TBD54566975/developer.tbd.website/assets/83640434/7f746433-d6dc-491f-938c-cc9c24d778c0">
The first word should always be capitalize but in the actors they are not. I would like to fix this one

**Comment by Smartmind12** [comment]
Hey @Pratham271 This is a repeat issue as of #832 please close this issue!
