### ISSUE TITLE
Typo in components

### ISSUE THREAD

**Issue by Pratham271** [TBD54566975/developer.tbd.website#867]
<img width="1588" alt="Screenshot 2023-10-11 at 9 33 55 AM" src="https://github.com/TBD54566975/developer.tbd.website/assets/83640434/75f5f9fe-ed28-40a0-a56b-c8d3735835a1">
Some components have full stop, others don't but there should be a uniformity. If this is available I want to work on this one

**Comment by Smartmind12** [comment]
Hey @Pratham271 This is an repeat issue as of #838 so please close this issue!
