### ISSUE TITLE
Broken links in the Docs and Blogs Page

### ISSUE THREAD

**Issue by Smartmind12** [TBD54566975/developer.tbd.website#868]
The following links are to be updated or removed to avoid confusion and 404: 
broken link > Source site
1. https://localhost:5173 > https://developer.tbd.website/docs/web5/build/apps/todo-app-tutorial/
2. existing docs > https://developer.tbd.website/open-source/contributing/
3. Verifiable Credentials JSON Schema > https://developer.tbd.website/blog/ssi-tbd-web5/
4. Governance Forums > https://developer.tbd.website/blog/announcing-the-incubation-program/
5. Contributions > https://developer.tbd.website/blog/web5-roadmap/
6. Forums > https://developer.tbd.website/blog/ssi-tbd-web5/
7.  Forum category > https://developer.tbd.website/blog/ssi-tbd-web5/
8. localhost:3000 > https://developer.tbd.website/docs/ssi/ssi-console/
9. jwt.io > https://developer.tbd.website/docs/ssi/create-credentials/
10. https://www.example.com/.well-known/did.json > https://developer.tbd.website/docs/ssi/create-did/
11. https://example.com/.well-known/did.json > https://developer.tbd.website/docs/ssi/create-did/
12. SSI SDK > https://developer.tbd.website/blog/web5-roadmap/
13. SSI Service > https://developer.tbd.website/blog/web5-roadmap/
14. Decentralized Web nodes > https://developer.tbd.website/blog/web5-roadmap/

Kindly assign me this issue so that i can update the links where necessary and remove links for example cases links.

**Comment by angiejones** [comment]
I'm sorry but I do not understand the issue

**Comment by angiejones** [comment]
for the localhost ones (numbers 1 and 8 above), please leave the text as is and just remove the hyperlink.

**Comment by Smartmind12** [comment]
Hey @angiejones Are there links for TBD forums and governance forums? if so can you share those links as i am unable to find them

**Comment by angiejones** [comment]
> 4\. https://developer.tbd.website/blog/announcing-the-incubation-program/

You can remove the TBD Forums wording and links. We no longer have a forum. For the governance forum, you can change that to point them to our Discord. 

Thanks so much for asking!

**Comment by leordev** [comment]
Hey @Smartmind12 just checking in! 😊 Do you need any help with this one?

**Comment by aniketh-varma** [comment]
Hey @angiejones @leordev, I see the issue has been idle for a while, can I pick this up?

**Comment by Smartmind12** [comment]
> Hey @Smartmind12 just checking in! 😊 Do you need any help with this one?

My commits are almost ready and i could not make a PR since i was travelling…i am returning today and will make the PR asap!

**Comment by Smartmind12** [comment]
Hey @angiejones I have done the needful...Kindly review the same!
