### ISSUE TITLE
Change of name in docs as well

### ISSUE THREAD

**Issue by Pratham271** [TBD54566975/developer.tbd.website#869]
![Screenshot_2023-10-11-12-07-34-73_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/TBD54566975/developer.tbd.website/assets/83640434/7a2a3055-9390-47db-9b8d-4ae4a0336dd9)
In the docs section also it is named as Twitter we can change it to X(fna Twitter) here also. I would like to work on this

**Comment by angiejones** [comment]
Please include as part of #864
