### ISSUE TITLE
typo in the blog

### ISSUE THREAD

**Issue by captain-Akshay** [TBD54566975/developer.tbd.website#876]
I think it should be $5K or the comma should be after $50,000 do let me know which one you want me to change ! 

![image](https://github.com/TBD54566975/developer.tbd.website/assets/59491379/6ef35e75-fcc3-44e7-8f09-0e72ccf997cd)

**Comment by captain-Akshay** [comment]
@angiejones i would lilke to work on this !

**Comment by blackgirlbytes** [comment]
Thanks @captain-Akshay! Looks like it's correct!

**Comment by blackgirlbytes** [comment]
Hi @captain-Akshay!!! Please remove the extra 0, but leave the comma as is! Thank you.
