### ISSUE TITLE
No hover effect

### ISSUE THREAD

**Issue by Pratham271** [TBD54566975/developer.tbd.website#880]
https://github.com/TBD54566975/developer.tbd.website/assets/83640434/cad9533a-e47e-4cac-8bd6-1ab71a570611

These links in the docs section have no hover effect. I would like to work on this

**Comment by blackgirlbytes** [comment]
Hey, looks like there is no hover effect on any internal links that are not buttons or menu items.. but that is a design choice! Will close this out!
