### ISSUE TITLE
Cursor-pointer

### ISSUE THREAD

**Issue by Pratham271** [TBD54566975/developer.tbd.website#881]
https://github.com/TBD54566975/developer.tbd.website/assets/83640434/023ab8d8-875a-489c-8e87-67d1ef46e9f9

In the api section the cursor on the expandable card should be of type pointer. I would like to work on this

**Comment by angiejones** [comment]
it already looks like a pointer cursor. I'm not sure I understand the purposed change.

**Comment by blackgirlbytes** [comment]
Hey @Pratham271 ! Thanks for noticing. Assigned it to you!

**Comment by YASHANT07** [comment]
i am interested please assign it to me..

**Comment by Pratham271** [comment]
It's completed already please close the completed issues

**Comment by angiejones** [comment]
> It's completed already please close the completed issues

When you submit a PR, reference the issue number. That way, it's very easy to close once merged
