### ISSUE TITLE
[DOCS] Typo in VC

### ISSUE THREAD

**Issue by captain-Akshay** [TBD54566975/developer.tbd.website#883]
full stop at the end of points should be removed as they are not full sentences:-

![Screenshot from 2023-10-13 12-28-55](https://github.com/TBD54566975/developer.tbd.website/assets/59491379/38ef3554-1f9a-4426-8f1d-1a1150b525e9)
Example of similar doc file
![image](https://github.com/TBD54566975/developer.tbd.website/assets/59491379/033528d7-1b25-4f44-af5a-1bdb7a0899c5)

**Comment by captain-Akshay** [comment]
i would like to work on this

**Comment by blackgirlbytes** [comment]
Hi @captain-Akshay! Thanks for noticing. Looks like the team decided we will the periods, so we will close this issue out for now.
