### ISSUE TITLE
Create missing Code Snippets and Tests

### ISSUE THREAD

**Issue by acekyd** [TBD54566975/developer.tbd.website#886]
Code is currently written directly in the Web5 -> API and Web5 -> Build sections. Update to the new code snippets and tests process.

Files:

- [Build: Write DWN Records](https://github.com/TBD54566975/developer.tbd.website/blob/v0.8.2-release/site/docs/web5/build/decentralized-web-nodes/write-to-dwn.mdx#L20)
- API: did [1](https://github.com/TBD54566975/developer.tbd.website/blob/v0.8.2-release/site/api/web5-js/did.mdx#L57), [2](https://github.com/TBD54566975/developer.tbd.website/blob/v0.8.2-release/site/api/web5-js/did.mdx#L97)
- [API: protocol](https://github.com/TBD54566975/developer.tbd.website/blob/v0.8.2-release/site/api/web5-js/dwn/protocol.mdx#L98)
- API: record [1](https://github.com/TBD54566975/developer.tbd.website/blob/v0.8.2-release/site/api/web5-js/dwn/record.mdx#L79), [2](https://github.com/TBD54566975/developer.tbd.website/blob/v0.8.2-release/site/api/web5-js/dwn/record.mdx#L110), [3](https://github.com/TBD54566975/developer.tbd.website/blob/v0.8.2-release/site/api/web5-js/dwn/record.mdx#L135), [4](https://github.com/TBD54566975/developer.tbd.website/blob/v0.8.2-release/site/api/web5-js/dwn/record.mdx#L176)
- API: records [1](https://github.com/TBD54566975/developer.tbd.website/blob/v0.8.2-release/site/api/web5-js/dwn/records.mdx#L137), [2](https://github.com/TBD54566975/developer.tbd.website/blob/v0.8.2-release/site/api/web5-js/dwn/records.mdx#L257), [3](https://github.com/TBD54566975/developer.tbd.website/blob/v0.8.2-release/site/api/web5-js/dwn/records.mdx#L407)

**Comment by CBID2** [comment]
I’ll try this :)

**Comment by angiejones** [comment]
Here's a few to choose from:

- Write DWN Records
- Update DWN Records
- Read DWN Records
- Make Records Public
- Delete DWN Records

@acekyd it's probably a good idea to make issues for each file

**Comment by angiejones** [comment]
full inventory: https://github.com/TBD54566975/developer.tbd.website/issues/979
