### ISSUE TITLE
Change of arrow direction

### ISSUE THREAD

**Issue by Pratham271** [TBD54566975/developer.tbd.website#888]
<img width="940" alt="Screenshot 2023-10-13 at 11 11 10 PM" src="https://github.com/TBD54566975/developer.tbd.website/assets/83640434/cd96b8ee-0957-433a-83c9-dad66565bde2">
In the blogs section the arrow of read more should not be in the upwards direction it either should be downwards or a right arrow

**Comment by Pratham271** [comment]
I want to work on this.

**Comment by angiejones** [comment]
it's ok, we will keep it as is
