### ISSUE TITLE
[DOCS] [Website] Typo of additon of Full stop

### ISSUE THREAD

**Issue by captain-Akshay** [TBD54566975/developer.tbd.website#894]
The statement, "Connect with us Everywhere," appears to lack completeness as it is not a fully-formed sentence. Therefore, it may be appropriate to consider the removal of the period at the end.

![image](https://github.com/TBD54566975/developer.tbd.website/assets/59491379/aa7ea215-ecd0-4063-aebb-34cb95cc52a0)

& it is in two different places.

**Comment by captain-Akshay** [comment]
I would like to work on this issue

**Comment by angiejones** [comment]
hiya @captain-Akshay, it is a complete sentence. we'd like to keep the period there
