### ISSUE TITLE
[DOC]: Missing full-stop

### ISSUE THREAD

**Issue by philling1** [TBD54566975/developer.tbd.website#895]
### Type

Suggestion to Improve

### Feedback

I had made changes to this issue before but it is not showing on the website after my PR has been merged

![Screenshot 2023-2](https://github.com/TBD54566975/developer.tbd.website/assets/90944819/0f26c3a5-03f5-4f0b-a944-874dca96bfa2)

There is supposed to be a full-stop at the end of Verifiable Credentials to show end of the sentence as used at the other API Reference messages

### Screenshots

Paste relevant images or screenshots here

### developer.tbd.website URL

DOCS page

### Browser

Microsoft Edge

**Comment by EbonyLouis** [comment]
@philling1 assigned 🎉 please create just one PR for this issue and the typo issue

**Comment by philling1** [comment]
Ok I have created a PR for this and the other issue was closed as it was not an issue but a slang

**Comment by ashutuptiwari** [comment]
Is this issue open?  If yes , assign it to me.

**Comment by philling1** [comment]
No it has already been assigned to me and I have created  a PR for it

**Comment by ashutuptiwari** [comment]
oh cool cool
