### ISSUE TITLE
[DOCS]: Typo in Docs 

### ISSUE THREAD

**Issue by philling1** [TBD54566975/developer.tbd.website#896]
### Type

Suggestion to Improve

### Feedback

I think there is misspelling of a word in the sentence; "It would be a really thicc wallet" under Docs > Learn > Agents

![tbd4](https://github.com/TBD54566975/developer.tbd.website/assets/90944819/1231ec14-265b-483a-90e2-c0442cc248a2)

I think the word was supposed to be "thick" instead of "thicc".  So I would like to make the necessary correction to it 

### Screenshots

Paste relevant images or screenshots here

### developer.tbd.website URL

DOCS page

### Browser

Microsoft Edge

**Comment by philling1** [comment]
Please assign this to me

**Comment by EbonyLouis** [comment]
@philling1 assigned 🥳

**Comment by angiejones** [comment]
it's meant to be thicc - it's slang :)
