### ISSUE TITLE
Make PackageJson component produce proper code block

### ISSUE THREAD

**Issue by angiejones** [TBD54566975/developer.tbd.website#897]
The second code block under [Quickstart -> Install Web5](https://developer.tbd.website/docs/web5/quickstart/#2-install-web5) is a plain `<pre>` section. It is lacking syntax highlights as well as the copy button.

<img width="849" alt="image" src="https://github.com/TBD54566975/developer.tbd.website/assets/15972783/de58d805-a3d6-4253-97bc-91fc125902a7">

Would be great if it resembled all the other code blocks on the site. To fix this, you'll need to modify the [return statement](https://github.com/TBD54566975/developer.tbd.website/blob/main/site/src/components/PackageJson.jsx#L18) in the component.

**Comment by Pratham271** [comment]
picking this up

**Comment by Pratham271** [comment]
<img width="1206" alt="Screenshot 2023-10-17 at 11 51 48 AM" src="https://github.com/TBD54566975/developer.tbd.website/assets/83640434/ca56dfc7-0088-4132-8f64-126c56472f54">
Is this the desired state that you wanted

**Comment by Tushar98644** [comment]
picking this up

**Comment by Pratham271** [comment]
This is already completed
