### ISSUE TITLE
typo in docs

### ISSUE THREAD

**Issue by Pratham271** [TBD54566975/developer.tbd.website#898]
https://github.com/TBD54566975/developer.tbd.website/assets/83640434/2a224aae-b654-4511-bbbe-d24d54b3c8fc

I've noticed a consistency problem with capitalization on your website. When a full stop is used to end a sentence, the following word should be capitalized, but it appears that lowercase letters are used instead. Also they are the complete sentences so they should end with a full stop.

**Comment by Pratham271** [comment]
I would like to work on this.

**Comment by angiejones** [comment]
@Pratham271 these are autogenerated from the [tbDEX project](https://github.com/TBD54566975/tbdex-js), so you'd need to file the issue there.
