### ISSUE TITLE
search icon not aligned

### ISSUE THREAD

**Issue by Pratham271** [TBD54566975/developer.tbd.website#901]
![mobile_view_search_icon](https://github.com/TBD54566975/developer.tbd.website/assets/83640434/1501563a-1f74-43d9-8513-7a48186eab7e)
The search icon in mobile view is not properly aligned

**Comment by Pratham271** [comment]
I would like to work on this

**Comment by leordev** [comment]
Hey @Pratham271  just checking in! 😊 Do you need any help with this one?

**Comment by Pratham271** [comment]
Can you tell me the file where the search icon is included or navbar is written

**Comment by Pratham271** [comment]
<img width="377" alt="Screenshot 2023-10-30 at 5 19 36 PM" src="https://github.com/TBD54566975/developer.tbd.website/assets/83640434/f5b16c3c-f370-4947-9840-57e611dc209a">
The search icon is not visible in the localhost version of the code

**Comment by Pratham271** [comment]
there is not a single file named navbar

**Comment by blackgirlbytes** [comment]
Old issue and site revamp happening. Closing!
