### ISSUE TITLE
Typo in homepage

### ISSUE THREAD

**Issue by Pratham271** [TBD54566975/developer.tbd.website#903]
<img width="786" alt="Screenshot 2023-10-17 at 1 12 59 PM" src="https://github.com/TBD54566975/developer.tbd.website/assets/83640434/8489705d-4c13-4ae1-8445-0d7413cedaa5">
I think it should be , instead of . 
It should be like Decentralized, Permissionless and Trustless

**Comment by Pratham271** [comment]
I would like to work on this

**Comment by hanzalahwaheed** [comment]
I think this is just them stating features of their Approach in a Bold manner and not a Typo.

**Comment by Pratham271** [comment]
I'm talking about the , and period but if they want it that way then it's fine

**Comment by hanzalahwaheed** [comment]
yes yes I believe its a slang and not a typo

**Comment by angiejones** [comment]
Hi thanks for looking into this. We intentionally used the periods for bold statements.
