### ISSUE TITLE
[FEEDBACK]:  Navbar Icons Allignment in Mobile View

### ISSUE THREAD

**Issue by hanzalahwaheed** [TBD54566975/developer.tbd.website#904]
### Type

Site Bug Report

### Feedback

The Navbar has a Responsive issue where the search icon is not properly aligned with the options icon. 

### Screenshots

![image](https://github.com/TBD54566975/developer.tbd.website/assets/101456741/10b20929-12a9-4438-84a5-37def6854e58)

### Browser

Chrome

**Comment by Pratham271** [comment]
It is a copy of #901 so close this one

**Comment by angiejones** [comment]
thanks so much. it'll be fixed in #901
