### ISSUE TITLE
Improve TBD Monthly Spotlight ✨

### ISSUE THREAD

**Issue by hanzalahwaheed** [TBD54566975/developer.tbd.website#905]
- The scroll can be improved to match the theme of the Website.
- The buttons can be of the same size despite the text inside.

![image](https://github.com/TBD54566975/developer.tbd.website/assets/101456741/4e917bf2-45ee-47f2-8eea-a391c1715f70)

**Comment by hanzalahwaheed** [comment]
Can I be assigned to work on this (if deemed necessary) under Hacktoberfest please.

**Comment by captain-Akshay** [comment]
![image](https://github.com/TBD54566975/developer.tbd.website/assets/59491379/51798603-ea79-425d-85d7-2a33e331937c)
i think browser specific would like to drop the version & details of your browser

**Comment by hanzalahwaheed** [comment]
Yes I use Brave Browser : [Version 1.59.117 Chromium: 118.0.5993.70 (Official Build) (64-bit)](https://brave.com/latest/)

**Comment by EbonyLouis** [comment]
@hanzalahwaheed  assigned 🎉 Thank you for calling this out, making the buttons the same size would be amazing!! Also fixing this issue on Brave browser is also nice.

**Comment by hanzalahwaheed** [comment]
@EbonyLouis Thanks for assigning me to the issue! I will start working on the buttons right away. Also, could you add the Hacktoberfest Lable for the issue please? :)
