### ISSUE TITLE
Link DID Document Glossary entry to guide

### ISSUE THREAD

**Issue by angiejones** [TBD54566975/developer.tbd.website#911]
There's an entry for [DID Document](https://developer.tbd.website/docs/glossary#did-document) in the glossary.  At the end of this entry, add a link to learn more from the [guide](https://developer.tbd.website/docs/web5/learn/did_document).

**Comment by captain-Akshay** [comment]
I would like to work on it

**Comment by Tushar98644** [comment]
@angiejones Hi i am newcomer , so would be great if you can assign the issue to me

**Comment by angiejones** [comment]
> @angiejones Hi i am newcomer , so would be great if you can assign the issue to me

welcome! I'll find another issue for you to work on. Thank you so much
