### ISSUE TITLE
Video card overflow 

### ISSUE THREAD

**Issue by Pratham271** [TBD54566975/developer.tbd.website#913]
![Screenshot_2023-10-21-12-31-15-16_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/TBD54566975/developer.tbd.website/assets/83640434/faf16635-4cb0-45f1-b784-96ecacf86d71)
In the mobile view the video in the blog is overflowing the screen

**Comment by Pratham271** [comment]
I would like to work on this

**Comment by angiejones** [comment]
good one! assigned

**Comment by Souradeephazra123** [comment]
Can you assign this issue to me ? I have already pull requested it .
