### ISSUE TITLE
Spacing issue

### ISSUE THREAD

**Issue by Pratham271** [TBD54566975/developer.tbd.website#914]
![Screenshot_2023-10-21-12-34-30-19_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/TBD54566975/developer.tbd.website/assets/83640434/2ff527e9-35d7-40c4-a601-0265b788cca9)
The complete titles of blogs are not visible in the mobile view due to extra padding or less space

**Comment by Pratham271** [comment]
I would like to work on this

**Comment by captain-Akshay** [comment]
this is a similar issue as this one! please close this one!
#912

**Comment by Pratham271** [comment]
But yours is more about spacing from the bottom but mine is a padding problem

**Comment by captain-Akshay** [comment]
You title is 'spacing issue '
And if I fixed it then your issue will also get fixed so you can close this one

**Comment by Pratham271** [comment]
Fix your one why are fixing mine

**Comment by angiejones** [comment]
@captain-Akshay and @Pratham271, I kindly ask that you all not fight over issues or be rude to any other contributors. I know you're both eager to help, but this goes against the culture of the TBD Community 🙏🏾
