### ISSUE TITLE
Typo in DOCs

### ISSUE THREAD

**Issue by captain-Akshay** [TBD54566975/developer.tbd.website#915]
Only this build docs have full stops in the description and every page in the build section dont have full stop in the bullet points.

![Screenshot from 2023-10-21 21-31-22](https://github.com/TBD54566975/developer.tbd.website/assets/59491379/f67846dd-fbff-4c1f-80fc-feb939942212)

![image](https://github.com/TBD54566975/developer.tbd.website/assets/59491379/4087991c-bd78-480b-a16f-9fba1587f7c0)

**Comment by captain-Akshay** [comment]
i would like to work on it!

**Comment by angiejones** [comment]
thank you, but it's ok
