### ISSUE TITLE
[FEEDBACK]: Dinger tutorial page has a broken link

### ISSUE THREAD

**Issue by shobitb** [TBD54566975/developer.tbd.website#916]
### Type

Docs Bug Report

### Feedback

In the [Learn More section on the Dinger tutorial page](https://developer.tbd.website/docs/web5/build/apps/dinger-tutorial/#-learn-more) it says 
> "Learn more about [DID authentication](https://developer.tbd.website/blog/did-authentication/&sa=D&source=docs&ust=1696216092697555&usg=AOvVaw1dujW2JHcAlpPUCjLunVn6)." 

and the DID authentication hyperlink goes to a Page Not Found.

I believe the correct link is

https://developer.tbd.website/blog/did-authentication

 instead of 

https://developer.tbd.website/blog/did-authentication/&sa=D&source=docs&ust=1696216092697555&usg=AOvVaw1dujW2JHcAlpPUCjLunVn6

### Screenshots

Paste relevant images or screenshots here

### developer.tbd.website URL

https://developer.tbd.website/docs/web5/build/apps/dinger-tutorial/#-learn-more

### Browser

Chrome

**Comment by aniketh-varma** [comment]
Hi @shobitb @EbonyLouis, I would like to work on this issue. Could you please assign this to me?
