### ISSUE TITLE
[FEEDBACK]: Records broken link

### ISSUE THREAD

**Issue by aniketh-varma** [TBD54566975/developer.tbd.website#919]
### Type

Site Bug Report

### Feedback

With reference to "Overview" section on this page: https://developer.tbd.website/api/web5-js/dwn/record/

![image](https://github.com/TBD54566975/developer.tbd.website/assets/55805574/f0f1d50c-9887-4e75-82cc-b656e9939a47)

There is a broken link on the word `Records`, it goes to: https://developer.tbd.website/api/web5-js/dwn/record/records, which is Page Not Found.

The correct link should be: https://developer.tbd.website/api/web5-js/dwn/records

### developer.tbd.website URL

https://developer.tbd.website/api/web5-js/dwn/record/

### Browser

Chrome

**Comment by aniketh-varma** [comment]
I would like to pick this up since I am working on a similar issue #825.

**Comment by EbonyLouis** [comment]
@aniketh-varma thank you for noticing this, its been assigned to you. 🥳
