### ISSUE TITLE
[FEEDBACK]: Make TBD Monthly Spotlight clickable

### ISSUE THREAD

**Issue by KhoiUna** [TBD54566975/developer.tbd.website#926]
### Type

Suggestion to Improve

### Feedback

Improve the UI to indicate that these cards are clickable.

Can I pick this one up for Hacktoberfest?

### Screenshots

![image](https://github.com/TBD54566975/developer.tbd.website/assets/63745633/a01b15e1-e650-4bc4-84ba-606f755e3742)

### developer.tbd.website URL

https://developer.tbd.website/community

### Browser

Firefox

**Comment by EbonyLouis** [comment]
@KhoiUna what do you mean by clickable? They should be already

**Comment by KhoiUna** [comment]
> @KhoiUna Hey sure what do you mean by clickable? 

I mean the cursor should change to a pointer when users hover over the card.

**Comment by EbonyLouis** [comment]
Thanks @KhoiUna you're right, right now its a arrow. Assigned 🥳

**Comment by KhoiUna** [comment]
@EbonyLouis I've submitted a pull request (https://github.com/TBD54566975/developer.tbd.website/pull/928)
