### ISSUE TITLE
[FEEDBACK]: dinger-completed project error

### ISSUE THREAD

**Issue by dnaicker86** [TBD54566975/developer.tbd.website#930]
### Type

Site Bug Report

### Feedback

On startup of the project the following error is displayed

### Screenshots

Paste relevant images or screenshots here
![image](https://github.com/TBD54566975/developer.tbd.website/assets/130728803/d660ead9-447d-4e99-a9e2-1ff808b344e5)

### Relevant log output

```shell
Unhandled Runtime Error
Error: Wrong tag

Call Stack
Object.decrypt
javascript\node_modules\.pnpm\@noble+ciphers@0.1.4\node_modules\@noble\ciphers\esm\chacha.js (293:0)
XChaCha20Poly1305.eval
javascript\node_modules\.pnpm\@web5+crypto@0.2.0\node_modules\@web5\crypto\dist\esm\crypto-primitives\xchacha20-poly1305.js (18:0)
Generator.next
<anonymous>
eval
javascript\node_modules\.pnpm\@web5+crypto@0.2.0\node_modules\@web5\crypto\dist\esm\crypto-primitives\xchacha20-poly1305.js (7:0)
new Promise
<anonymous>
__awaiter
javascript\node_modules\.pnpm\@web5+crypto@0.2.0\node_modules\@web5\crypto\dist\esm\crypto-primitives\xchacha20-poly1305.js (3:0)
XChaCha20Poly1305.decrypt
javascript\node_modules\.pnpm\@web5+crypto@0.2.0\node_modules\@web5\crypto\dist\esm\crypto-primitives\xchacha20-poly1305.js (14:0)
AppDataVault.eval
javascript\node_modules\.pnpm\@web5+agent@0.2.0\node_modules\@web5\agent\dist\esm\app-data-store.js (90:62)
Generator.next
<anonymous>
fulfilled
javascript\node_modules\.pnpm\@web5+agent@0.2.0\node_modules\@web5\agent\dist\esm\app-data-store.js (4:42)
```

**Comment by dnaicker86** [comment]
I think the application might have still been loading. The error seems to have gone away although a new error when trying to send a message occurs: `TypeError: Cannot read properties of undefined (reading 'send')`

![image](https://github.com/TBD54566975/developer.tbd.website/assets/130728803/dd7d5e75-0e95-44cd-9450-be73b719306e)

**Comment by blackgirlbytes** [comment]
ah interesting. can I have more info -- does the record.send() error show up on load or when you send a message to a user?

**Comment by theCuriousOne** [comment]
Run into the same issue. I believe  the root cause is that the protocol url and the schema are non existent/invalid (when viewed from browser I get 404 for both). There for the returned record in ```const record = await writeToDwn(ding);``` is ```undefined```

**Comment by blackgirlbytes** [comment]
I think this is fixed because I do a check to see if web5 is connected before it loads all the elements on the page, so no one can send a record before Web5 is fully initialized. If it still shows an issue, let me know.
