### ISSUE TITLE
[FEEDBACK]: Transition to icons in Header and Footer Section

### ISSUE THREAD

**Issue by DeepRahangdale** [TBD54566975/developer.tbd.website#932]
### Type

Suggestion to Improve

### Feedback

Adding a Pop-up Transition on Hovering To the Buttons in the Header Section and Icons in the Footer Section!!
will Enhance the User Experience!!

### Screenshots

Paste relevant images or screenshots here

**Comment by EbonyLouis** [comment]
@DeepRahangdale Hey, can you give me a little bit more information on this please. what would that look like?

**Comment by DeepRahangdale** [comment]
https://drive.google.com/file/d/1Gm2KpWL_40dTaTYSwiTKyI3HPI0nPcQw/view?usp=sharing

similar to this !!!
