### ISSUE TITLE
Create CodeSnippet component and tests for 'Update DWN Records'

### ISSUE THREAD

**Issue by angiejones** [TBD54566975/developer.tbd.website#937]
The code in the [Update DWN Records tutorial](https://developer.tbd.website/docs/web5/build/decentralized-web-nodes/write-to-dwn) are hard-coded. They need to be placed in <CodeSnippet> components and tests need to be written for them. See the README.md file for instructions on the CodeSnippet and test process.

**Comment by CBID2** [comment]
I'll do it :)
