### ISSUE TITLE
[FEEDBACK]: Add Link too TBD Shop

### ISSUE THREAD

**Issue by Smartmind12** [TBD54566975/developer.tbd.website#939]
### Type

Suggestion to Improve

### Feedback

Currently a cart icon is present for the TBD shop. However it is added in the connect us footer page which is inaccurate as its not a medium to connect on social media. It also creates an issue for first time users who do not know that the cart refers to the TBD shop.

I proposed to work on it by Add a Link of TBD shop next to TBD Home for better identification and highlighting purpose. 

### Screenshots

![Screenshot 2023-10-29 at 8 58 04 AM](https://github.com/TBD54566975/developer.tbd.website/assets/91927689/986354c4-c99c-4579-be84-cce432b075c4)

### developer.tbd.website URL

https://developer.tbd.website/

**Comment by KhoiUna** [comment]
This issue has been resolved!
