### ISSUE TITLE
[FEEDBACK]: Add NextJS 13 sample todo app to tutorials

### ISSUE THREAD

**Issue by KhoiUna** [TBD54566975/developer.tbd.website#941]
### Type

Suggestion to Improve

### Feedback

Add a tutorial of a Todo app using the new NextJS 13's `/app` dir since the current tutorials use VueJS and NextJS's `/pages` dir.

### Screenshots

Paste relevant images or screenshots here

### developer.tbd.website URL

https://developer.tbd.website/docs/web5/build/apps/todo-app-tutorial

### Browser

N/A

**Comment by KhoiUna** [comment]
@EbonyLouis can I work on this for Hacktoberfest?

**Comment by angiejones** [comment]
cc @acekyd

**Comment by acekyd** [comment]
Hi @KhoiUna! Yes you can! We love seeing the Web5 SDK used with different tools and context. Let me know if you need anything here or on [Discord](https://discord.com/invite/tbd).

**Comment by KhoiUna** [comment]
I submitted a [PR](https://github.com/TBD54566975/developer.tbd.website/pull/953). Hope it is valid for Hacktober!

**Comment by ALRubinger** [comment]
Closing via linked PR https://github.com/TBD54566975/developer.tbd.website/pull/953, let's reopen if we need to revisit
