### ISSUE TITLE
Duplicacy of code in video card fixes

### ISSUE THREAD

**Issue by Pratham271** [TBD54566975/developer.tbd.website#945]
The code is duplicated each time we add a video, and as @angiejones suggested we should make the changes standardized in the [Video component](https://github.com/TBD54566975/developer.tbd.website/blob/main/site/src/components/Video.jsx) and then use the `<Video>` component in the blog posts.

**Comment by Pratham271** [comment]
I'd love to work on this one

**Comment by EbonyLouis** [comment]
@Pratham271 assigned

**Comment by Pratham271** [comment]
@EbonyLouis we can't directly import the react components in mdx file can you guide me for the approach

**Comment by EbonyLouis** [comment]
@Pratham271 you can add components to mdx files, here's an example: `site/src/pages/open-source/contributing.mdx` if you look at the top of the file and the end of the file you'll see how it's done. Lmk if that helps

**Comment by Pratham271** [comment]
Thanks for the help

**Comment by ALRubinger** [comment]
@EbonyLouis Cool to close?
