### ISSUE TITLE
[FEEDBACK]: No Package.json from running npm install @web5/api

### ISSUE THREAD

**Issue by JenErsoz-Jones** [TBD54566975/developer.tbd.website#962]
### Type

Content Issue

### Feedback

Tell us what you're seeing!
Hello, in your documentation for quickstart, I had to run npm init to get a package.json file, simply running npm install @web5/api did not create a package.json file for me. 

### Screenshots

Paste relevant images or screenshots here

### developer.tbd.website URL

https://developer.tbd.website/docs/web5/quickstart/

**Comment by EbonyLouis** [comment]
@JenErsoz-Jones Thank you so much I will get this updated as well!

**Comment by JenErsoz-Jones** [comment]
@EbonyLouis thank you

**Comment by EbonyLouis** [comment]
resolved
