### ISSUE TITLE
[FEEDBACK]: touch command not working

### ISSUE THREAD

**Issue by JenErsoz-Jones** [TBD54566975/developer.tbd.website#963]
### Type

Content Issue

### Feedback

Tell us what you're seeing!
Hello, there is a command to enter `"touch index.js"` however this does not work unless installed. The documentation tells developers to install npm to run npm commands however does not tell developers to install touch to run the touch command. As can be seen from the output below:

At line:1 char:1
+ touch index.js
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (touch:Stri  
   ng) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException 

### Screenshots

Paste relevant images or screenshots here

### developer.tbd.website URL

https://developer.tbd.website/docs/web5/quickstart/

### Browser

N/A

**Comment by EbonyLouis** [comment]
@JenErsoz-Jones Thank you for pointing this out! From what I recall the `touch` command works on  Macs but if you are using Windows/Powershell then you would need to run this command: 

`New-Item index.js -ItemType File`

I'll add a note in the guide.

**Comment by JenErsoz-Jones** [comment]
Hi @EbonyLouis, yes, indeed I was using windows. Thanks.

**Comment by EbonyLouis** [comment]
resolved
