### ISSUE TITLE
[FEEDBACK]: node index.js command needs package.json configuration

### ISSUE THREAD

**Issue by JenErsoz-Jones** [TBD54566975/developer.tbd.website#964]
### Type

Docs Bug Report

### Feedback

Tell us what you're seeing!
To run the following command `node index.js` the package.json file needs to amended to include "type": "module", there is no mention of this on the quickstart page

node index.js        
(node:10532) Warning: To load an ES module, set "type": "module" in the package.json

### Screenshots

Paste relevant images or screenshots here

### developer.tbd.website URL

https://developer.tbd.website/docs/web5/quickstart/

### Browser

N/A

**Comment by EbonyLouis** [comment]
Hey @JenErsoz-Jones I might be misunderstanding you. I'm seeing it [here in step 2](https://developer.tbd.website/docs/web5/quickstart/#2-install-web5). Let me know if this addresses the problem you ran into. 
<img width="795" alt="Screenshot 2023-11-08 at 5 40 08 AM" src="https://github.com/TBD54566975/developer.tbd.website/assets/55366651/f5d15920-d85b-4e28-ae7f-b26ec213c2d5">

**Comment by JenErsoz-Jones** [comment]
@EbonyLouis thanks for pointing this out, yes this is the problem I ran into
