### ISSUE TITLE
[FEEDBACK]: input field on quickstart page disabled

### ISSUE THREAD

**Issue by JenErsoz-Jones** [TBD54566975/developer.tbd.website#965]
### Type

Docs Bug Report

### Feedback

Tell us what you're seeing!
https://developer.tbd.website/docs/web5/quickstart/#try-it the input field on the quickstart page under the try-it anchor is disabled.

### Screenshots

Paste relevant images or screenshots here

**Comment by EbonyLouis** [comment]
@JenErsoz-Jones Hey, thanks so much for taking the time to provide feedback. For clarity the way the quick start works, once you complete step 1 it will enable the other steps. You can't write to a DWN without first instantiating Web5 and creating your DID.  

I'll read through it and see if perhaps there's somewhere we can add messaging around this to clarify it.

**Comment by JenErsoz-Jones** [comment]
@EbonyLouis thanks for looking into this
