### ISSUE TITLE
Get rid of the `@web5/api/browser` bundle

### ISSUE THREAD

**Issue by leordev** [TBD54566975/developer.tbd.website#972]
We now know how to use `@web5/api` in docusaurus without using the `/browser` bundle.

Reference: https://github.com/TBD54566975/bundler-bonanza/pull/57

Now we need to replicate it here.

**Comment by Vikrant-Khedkar** [comment]
can you describe more

**Comment by angiejones** [comment]
@leordev this one is done, yeah? can we close?

**Comment by leordev** [comment]
Correct @angiejones
