### ISSUE TITLE
Untested code inventory

### ISSUE THREAD

**Issue by dayhaysoos** [TBD54566975/developer.tbd.website#979]
This is a list of things that are currently not being tested. It includes browser tests and code snippets throughout the site:

## Code snippets file paths
| Path                                                            | Lines                          | Issue |
|-----------------------------------------------------------------|--------------------------------|-------|
| /site/api/web5-js/did.mdx                                       | Lines 56, 97                   | [Issue 980](https://github.com/TBD54566975/developer.tbd.website/issues/980), [Issue 981](https://github.com/TBD54566975/developer.tbd.website/issues/981) |
| /site/api/web5-js/dwn/protocol.mdx                              | Line 98                        | [Issue 982](https://github.com/TBD54566975/developer.tbd.website/issues/982) |
| /site/api/web5-js/dwn/record.mdx                                | Lines 78, 110, 134, 175        | [Issue 986](https://github.com/TBD54566975/developer.tbd.website/issues/986), [Issue 985](https://github.com/TBD54566975/developer.tbd.website/issues/985), [Issue 984](https://github.com/TBD54566975/developer.tbd.website/issues/984), [Issue 983](https://github.com/TBD54566975/developer.tbd.website/issues/983) |
| /site/api/web5-js/dwn/records.mdx                               | Lines 137, 257, 428            | [Issue 988](https://github.com/TBD54566975/developer.tbd.website/issues/988), [Issue 989](https://github.com/TBD54566975/developer.tbd.website/issues/989) |
| /site/docs/web5/build/decentralized-web-nodes/read-from-dwn.mdx | Line 18                        | [Issue 990](https://github.com/TBD54566975/developer.tbd.website/issues/990) |
| /site/docs/web5/build/decentralized-web-nodes/write-to-dwn.mdx  | Lines 20, 35, 52               | [Issue 999](https://github.com/TBD54566975/developer.tbd.website/issues/999), [Issue 1000](https://github.com/TBD54566975/developer.tbd.website/issues/1000), [Issue 1001](https://github.com/TBD54566975/developer.tbd.website/issues/1001) |

## Tutorials without browser tests (within /examples/tutorials/)

| Tutorial             | Issue Link                                                       |
|----------------------|------------------------------------------------------------------|
| book-reviews         | [Issue #992](https://github.com/TBD54566975/developer.tbd.website/issues/992) |
| dinger-completed     | [Issue #993](https://github.com/TBD54566975/developer.tbd.website/issues/993) |
| dinger-started       | [Issue #994](https://github.com/TBD54566975/developer.tbd.website/issues/994) |
| shared-todo-completed| [Issue #995](https://github.com/TBD54566975/developer.tbd.website/issues/995) |
| shared-todo-starter  | [Issue #996](https://github.com/TBD54566975/developer.tbd.website/issues/996) |

**Note about Code Snippets**

This list excludes anything related to tutorials since those are getting their own "happy path" tests.

## Reconsider Quickstart content

https://developer.tbd.website/docs/web5/quickstart

The content at the bottom of the quick start is not accounted for. We have an untested index.txt file for users to download as well as a sandbox environment to see how web5 works:

https://moonlit-centaur-0d7b4f.netlify.app/

We need to determine if this is going to be updated, maintained and tested for future web5 releases.

Related issue https://github.com/TBD54566975/developer.tbd.website/issues/997

**Comment by angiejones** [comment]
Also [Write to DWN](https://github.com/TBD54566975/developer.tbd.website/blob/v0.8.2-release/site/docs/web5/build/decentralized-web-nodes/write-to-dwn.mdx) guide

**Comment by dayhaysoos** [comment]
@angiejones I was excluding things within the `build` directory assuming they were tutorials that had examples elsewhere.. I can update to include things in that directory as well

**Comment by ALRubinger** [comment]
@dayhaysoos With these now inventoried and reflected on the [Project Board](https://github.com/orgs/TBD54566975/projects/10), looks like we're clear to close this issue? Anything here not yet with its own issue?

**Comment by ALRubinger** [comment]
@dayhaysoos confirms this inventory is complete and this issue may be closed
