### ISSUE TITLE
createDid Code Snippet

### ISSUE THREAD

**Issue by dayhaysoos** [TBD54566975/developer.tbd.website#980]
path: /site/api/web5-js/did.mdx 

This should be a code snippet:

```js
const myDid = await web5.did.create('ion');
```

We can test the return value coming back from this method.

**Comment by blackgirlbytes** [comment]
I was going to remove this line, but I think for now..let's just leave it and replace it with the right way in the near future. I feel I would have to remove too much of the documentation if I were to remove this line

**Comment by ALRubinger** [comment]
From @blackgirlbytes, bumping to Phase 6

**Comment by angiejones** [comment]
I rewrote the guide and make new tests
