### ISSUE TITLE
Determine how did.resolve() code snippet should be handled

### ISSUE THREAD

**Issue by dayhaysoos** [TBD54566975/developer.tbd.website#981]
file path: /site/api/web5-js/did.mdx

Code Snippet: 

```js
const myDid = 'did:key:z6MkhvthBZDxVvLUswRey729CquxMiaoYXrT5SYbCAATc8V9';
const didDocument = await web5.did.resolve(myDid);
```

Due to the did key being hard coded, it will be tricky figuring out a way to test this. Could possibly leave it as is or write a test expecting the failure.

**Comment by angiejones** [comment]
just need to use the class level `myDid` variable. However, mark this test as skipped because `resolve()` is not enabled in Web5 right now. Should be in the next version though

**Comment by ALRubinger** [comment]
From @angiejones notes, bumping to Phase 6

**Comment by angiejones** [comment]
`resolve()` works now so we can re-enable this test
